GET https://link-search.api.cj.com/v2/link-search?advertiser-ids=joined&website-id=8125108&records-per-page=100&page-number=1
Accept: application/xml
Authorization: Bearer {{commission_junktion_token}}