<?php

namespace AwardWallet\Tests\FunctionalSymfony\Security;

use AwardWallet\MainBundle\Globals\StringHandler;
use AwardWallet\MainBundle\Security\TwoFactorAuthentication\TwoFactorAuthenticationService;

/**
 * @group frontend-functional
 * @group login
 */
class EmailOtcCest
{
    use \Awardwallet\Tests\Modules\AutoVerifyMocksTrait;
    use LoginTrait;

    public const MY_IP = '148.85.136.31';
    public const FAR_IP = '178.161.167.162';
    public const FAR_IP_2 = '198.199.104.203';
    public const FAR_IP_3 = '41.57.128.4';
    public const UNKNOWN_IP = '127.0.0.1'; // not known to geoip

    public function testEmailOtc(\TestSymfonyGuy $I)
    {
        $user = $this->createUser($I,
            ['RegistrationIP' => self::MY_IP, 'LastLogonIP' => self::MY_IP, "InBeta" => 1, "BetaApproved" => 1]);
        $I->seeInDatabase("Usr",
            ["UserID" => $user['userId'], "RegistrationIP" => self::MY_IP, "LastLogonIP" => self::MY_IP]);

        $I->wantToTest("first login, from Amherst");
        $I->setCookie("NDEnabled", "1");
        $I->setCookie("EnableEmailOtcCheck", "1");
        $I->haveServerParameter("REMOTE_ADDR", self::MY_IP);
        $this->loginUser($user, $I);
        $I->seeResponseContainsJson(["success" => true]);
        $I->seeCookie("AuthKey", "/login_check");
        $I->seeCookie("AuthKey", "/m/api/login_check");
        $I->seeInDatabase("Usr", ["UserID" => $user['userId'], "LastLogonIP" => self::MY_IP]);

        $I->wantToTest("login from far ip, Perm, with cookie");
        $I->haveServerParameter("REMOTE_ADDR", self::FAR_IP);
        $this->loginUser($user, $I);
        $I->seeResponseContainsJson(["success" => true]);
        $I->amOnPage("/contact"); // fire SessionListener by loading any page

        $I->wantToTest("login from another far ip, DO, without cookie");
        $I->haveServerParameter("REMOTE_ADDR", self::FAR_IP_2);
        $this->resetAuthCookie($I);
        $I->grabService('aw.manager.mobile_device_manager')->addDevice((int) $user['userId'], 'android',
            'keykey123', 'en', '3.18.0+10050', '127.0.0.1');
        $this->loginUser($user, $I);
        $I->seeResponseContainsJson([
            "success" => false,
            "otcRequired" => true,
            "otcInputLabel" => "One time access code from email",
            "otcShowRecovery" => false,
            "badCredentials" => false,
        ]);
        $I->dontSeeResponseContainsJson(["otcInputHint" => "(this is a 6-digit code generated by Google Authenticator or equivalent program)"]);

        $I->wantToTest("login with invalid otc");
        $this->loginUser($user, $I, "123");
        $I->seeResponseContainsJson([
            "success" => false,
            "otcRequired" => true,
            "message" => "The access code you've entered is not valid, please try again",
            "otcShowRecovery" => false,
            "badCredentials" => false,
        ]);

        $I->wantToTest("email with otc");
        $I->seeEmailTo($user['email'], 'AwardWallet Access Security Code');
        $mail = $I->grabLastMailMessageBody();
        $I->assertEquals(1, preg_match("#AwardWallet One Time Access Code:[\s\*]*(\d+)#ims", $mail, $matches));
        $code = $matches[1];
        $I->assertEquals(1, preg_match('#^\d{6}$#ims', $code));
        $I->seePushTo((int) $user['userId'], "/Your AwardWallet One Time Access Code is: {$code}/");

        $I->wantToTest("login with valid otc");
        $this->loginUser($user, $I, $code);
        $I->seeResponseContainsJson(["success" => true]);
        $I->amOnPage("/contact"); // fire SessionListener by loading any page

        $I->wantToTest("login with used valid otc");
        $I->haveServerParameter("REMOTE_ADDR", self::FAR_IP_3);
        $this->resetAuthCookie($I);
        $this->loginUser($user, $I, $code);
        $I->seeResponseContainsJson([
            "success" => false,
            "otcRequired" => true,
            "message" => "The access code you've entered is not valid, please try again",
            "otcShowRecovery" => false,
            "badCredentials" => false,
        ]);

        $I->wantToTest("login from same ip, without cookie");
        $I->haveServerParameter("REMOTE_ADDR", self::FAR_IP_2);
        $this->resetAuthCookie($I);
        $this->loginUser($user, $I);
        $I->seeResponseContainsJson(["success" => true]);

        $I->wantToTest("second login from far ip, Perm, without cookie, should match by ip");
        $I->haveServerParameter("REMOTE_ADDR", self::FAR_IP);
        $this->resetAuthCookie($I);
        $this->loginUser($user, $I);
        $I->seeResponseContainsJson(["success" => true]);
    }

    public function testMultipleCodes(\TestSymfonyGuy $I)
    {
        $user = $this->createUser($I,
            ['RegistrationIP' => self::MY_IP, 'LastLogonIP' => self::MY_IP, "InBeta" => 1, "BetaApproved" => 1]);
        $codes = [];

        for ($n = 0; $n < 15; $n++) {
            $code = StringHandler::getRandomString(ord('0'), ord('9'), 6);
            $I->haveInDatabase("OneTimeCode", [
                "UserID" => $user['userId'],
                'Code' => $code,
                'CreationDate' => date('Y-m-d H:i:s', time() - SECONDS_PER_DAY * ($n + 1)),
            ]);
            $codes[] = $code;
        }

        $I->assertEquals(15, $I->grabCountFromDatabase("OneTimeCode", ["UserID" => $user['userId']]));

        $I->wantToTest("first login, from Amherst");
        $I->setCookie("NDEnabled", "1");
        $I->setCookie("EnableEmailOtcCheck", "1");
        $I->haveServerParameter("REMOTE_ADDR", self::FAR_IP);
        $this->loginUser($user, $I);
        $I->seeResponseContainsJson([
            "success" => false,
            "otcRequired" => true,
            "otcInputLabel" => "One time access code from email",
            "otcShowRecovery" => false,
            "badCredentials" => false,
        ]);

        $I->assertEquals(10, $I->grabCountFromDatabase("OneTimeCode", ["UserID" => $user['userId']]));

        $this->loginUser($user, $I, $codes[13]);
        $I->seeResponseContainsJson([
            "success" => false,
            "otcRequired" => true,
            "otcInputLabel" => "One time access code from email",
            "otcShowRecovery" => false,
            "badCredentials" => false,
        ]);

        $this->loginUser($user, $I, $codes[5]);
        $I->seeResponseContainsJson(["success" => true]);
    }

    public function testUnknownIp(\TestSymfonyGuy $I)
    {
        $user = $this->createUser($I,
            ['RegistrationIP' => self::MY_IP, 'LastLogonIP' => self::MY_IP, "InBeta" => 1, "BetaApproved" => 1]);
        $I->setCookie("NDEnabled", "1");
        $I->setCookie("EnableEmailOtcCheck", "1");
        $I->haveServerParameter("REMOTE_ADDR", self::UNKNOWN_IP);
        $this->loginUser($user, $I);
        $I->seeResponseContainsJson([
            "success" => false,
            "otcRequired" => true,
            "otcInputLabel" => "One time access code from email",
            "otcShowRecovery" => false,
            "badCredentials" => false,
        ]);

        $code = $I->grabFromDatabase("OneTimeCode", "Code", ["UserID" => $user['userId']]);
        $this->resetAuthCookie($I);
        $this->loginUser($user, $I, $code);
        $I->seeResponseContainsJson(["success" => true]);
        $I->amOnPage("/page/about"); // fire session listener
        $I->seeInDatabase("UserIP", ["UserID" => $user['userId'], "IP" => self::UNKNOWN_IP]);
        $this->resetAuthCookie($I);
        $this->loginUser($user, $I);
        $I->seeResponseContainsJson(["success" => true]);
    }

    public function testLastLogonUnknownIp(\TestSymfonyGuy $I)
    {
        $user = $this->createUser($I,
            ['RegistrationIP' => self::FAR_IP, 'LastLogonIP' => self::UNKNOWN_IP, "InBeta" => 1, "BetaApproved" => 1]);
        $I->setCookie("NDEnabled", "1");
        $I->haveServerParameter("REMOTE_ADDR", self::MY_IP);
        $I->setCookie("EnableEmailOtcCheck", "1");
        $this->loginUser($user, $I);
        $I->seeResponseContainsJson([
            "success" => false,
            "otcRequired" => true,
            "otcInputLabel" => "One time access code from email",
            "otcShowRecovery" => false,
            "badCredentials" => false,
        ]);

        $I->haveInDatabase("UserIP", ["UserID" => $user['userId'], "IP" => self::MY_IP]);
        $this->loginUser($user, $I);
        $I->seeResponseContainsJson(["success" => true]);
    }

    public function testSwitchUsersWithCookie(\TestSymfonyGuy $I)
    {
        $user1 = $this->createUser($I,
            ['RegistrationIP' => self::MY_IP, 'LastLogonIP' => self::MY_IP, "InBeta" => 1, "BetaApproved" => 1]);
        $user2 = $this->createUser($I,
            ['RegistrationIP' => self::FAR_IP, 'LastLogonIP' => self::FAR_IP, "InBeta" => 1, "BetaApproved" => 1]);

        $I->setCookie("NDEnabled", "1");
        $I->haveServerParameter("REMOTE_ADDR", self::MY_IP);
        $this->loginUser($user1, $I);
        $I->seeResponseContainsJson(["success" => true]);

        $I->setCookie("NDEnabled", "1");
        $I->haveServerParameter("REMOTE_ADDR", self::FAR_IP);
        $this->loginUser($user2, $I);
        $I->seeResponseContainsJson(["success" => true]);

        $I->wantToTest("login as user1 from other ip, with cookie");
        $I->haveServerParameter("REMOTE_ADDR", self::FAR_IP);
        $this->loginUser($user1, $I);
        $I->seeResponseContainsJson(["success" => true]);

        $I->wantToTest("login as user2 from other ip, with cookie");
        $I->haveServerParameter("REMOTE_ADDR", self::FAR_IP_2);
        $this->loginUser($user2, $I);
        $I->seeResponseContainsJson(["success" => true]);
    }

    public function testDisabledOTC(\TestSymfonyGuy $I)
    {
        $user = $this->createUser($I,
            ['RegistrationIP' => self::MY_IP, 'LastLogonIP' => self::MY_IP, "InBeta" => 1, "BetaApproved" => 1]);
        $groupId = $I->shouldHaveInDatabase("SiteGroup", [
            "GroupName" => TwoFactorAuthenticationService::BYPASS_EMAIL_OTC_GROUP,
            "Description" => "Members of this group will not be sent a security code if they login from a new location",
        ]);
        $linkId = $I->haveInDatabase("GroupUserLink", ["SiteGroupID" => $groupId, "UserID" => $user['userId']]);
        $I->assertGreaterThan(0, $linkId);
        $I->haveServerParameter("REMOTE_ADDR", self::FAR_IP);
        $I->setXdebugCookie();
        $this->loginUser($user, $I);
        $I->seeResponseContainsJson(["success" => true]);
    }

    private function resetAuthCookie(\TestSymfonyGuy $I)
    {
        $I->resetCookie("AuthKey", "/login_check");
        $I->resetCookie("AuthKey", "/m/api/login_check");
    }
}
