<?php

namespace AwardWallet\Tests\FunctionalSymfony\Security;

use AwardWallet\MainBundle\Entity\Usr;

/**
 * @group frontend-functional
 * @group login
 */
class QuestionsCest
{
    use \Awardwallet\Tests\Modules\AutoVerifyMocksTrait;
    use LoginTrait;

    public const NEW_IP = '148.85.136.31';

    public function _before(\TestSymfonyGuy $I)
    {
        $I->resetLockout("ip", self::NEW_IP);
    }

    public function askQuestionAfterReset(\TestSymfonyGuy $I)
    {
        $user = $this->createUser($I, [
            "LastLogonDateTime" => date("Y-m-d", strtotime("-3 day")),
            "ChangePasswordDate" => date("Y-m-d", strtotime("-2 day")),
            "ChangePasswordMethod" => Usr::CHANGE_PASSWORD_METHOD_LINK,
        ]);
        $providerId = $I->createAwProvider();
        $accountId = $I->createAwAccount($user['userId'], $providerId, "balance.random", null,
            ["ErrorCode" => ACCOUNT_CHECKED]);
        $I->haveInDatabase("Answer",
            ["AccountID" => $accountId, "Question" => "How much is the fish?", "Answer" => "65.15", "Valid" => 1]);

        $I->haveServerParameter("REMOTE_ADDR", self::NEW_IP);

        $this->loginUser($user, $I);
        $I->seeResponseContainsJson([
            "success" => false,
            "otcRequired" => true,
            "otcInputLabel" => [
                ["question" => "How much is the fish?", "maskInput" => false],
            ],
            "otcShowRecovery" => false,
            "badCredentials" => false,
        ]);
        $I->dontSeeResponseContainsJson(["otcInputHint" => "(this is a 6-digit code generated by Google Authenticator or equivalent program)"]);

        $I->wantToTest("login with invalid answer");
        $this->loginUser($user, $I, "How much is the fish?=12");
        $I->seeResponseContainsJson([
            "success" => false,
            "otcRequired" => true,
            "message" => "The answer you provided does not match our records. Please try again.",
            "otcShowRecovery" => false,
            "badCredentials" => false,
        ]);

        $I->wantToTest("login with valid answer");
        $this->loginUser($user, $I, "How much is the fish?=65.15");
        $I->seeResponseContainsJson(["success" => true]);
    }

    public function askPasswordAfterReset(\TestSymfonyGuy $I)
    {
        $user = $this->createUser($I, [
            "LastLogonDateTime" => date("Y-m-d", strtotime("-3 day")),
            "ChangePasswordDate" => date("Y-m-d", strtotime("-2 day")),
            "ChangePasswordMethod" => Usr::CHANGE_PASSWORD_METHOD_LINK,
        ]);
        $providerId = $I->createAwProvider(null, null, ["ShortName" => "Test Provider"]);
        $I->createAwAccount($user['userId'], $providerId, "balance.random", "somepass",
            ["ErrorCode" => ACCOUNT_CHECKED]);

        $I->haveServerParameter("REMOTE_ADDR", self::NEW_IP);
        $this->loginUser($user, $I);
        $I->seeResponseContainsJson([
            "success" => false,
            "otcRequired" => true,
            "otcInputLabel" => [
                [
                    "question" => "What is the password for your Test Provider account balance.random?",
                    "maskInput" => true,
                ],
            ],
            "otcShowRecovery" => false,
            "badCredentials" => false,
        ]);

        $I->wantToTest("login with invalid password");
        $this->loginUser($user, $I, "What is the password for your Test Provider account balance.random?=wrongpass");
        $I->seeResponseContainsJson([
            "success" => false,
            "otcRequired" => true,
            "message" => "The answer you provided does not match our records. Please try again.",
            "otcShowRecovery" => false,
            "badCredentials" => false,
        ]);

        $I->wantToTest("login with valid password");
        $this->loginUser($user, $I, "What is the password for your Test Provider account balance.random?=somepass");
        $I->seeResponseContainsJson(["success" => true]);
    }

    public function askPasswordAndQuestion(\TestSymfonyGuy $I)
    {
        $user = $this->createUser($I, [
            "LastLogonDateTime" => date("Y-m-d", strtotime("-3 day")),
            "ChangePasswordDate" => date("Y-m-d", strtotime("-2 day")),
            "ChangePasswordMethod" => Usr::CHANGE_PASSWORD_METHOD_LINK,
        ]);
        $providerId = $I->createAwProvider(null, null, ["ShortName" => "Test Provider"]);
        $accountId = $I->createAwAccount($user['userId'], $providerId, "balance.random", "somepass",
            ["ErrorCode" => ACCOUNT_CHECKED]);
        $I->haveInDatabase("Answer",
            ["AccountID" => $accountId, "Question" => "How much is the fish?", "Answer" => "65.15", "Valid" => 1]);

        $I->haveServerParameter("REMOTE_ADDR", self::NEW_IP);
        $this->loginUser($user, $I);
        $I->seeResponseContainsJson([
            "success" => false,
            "otcRequired" => true,
            "otcInputLabel" => [
                ["question" => "How much is the fish?", "maskInput" => false],
                [
                    "question" => "What is the password for your Test Provider account balance.random?",
                    "maskInput" => true,
                ],
            ],
            "otcShowRecovery" => false,
            "badCredentials" => false,
        ]);
    }
}
