<?php
/**
 * AirlineInfo.
 *
 * PHP version 5
 *
 * @category Class
 * @author   Swagger Codegen team
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FlightStats, Inc. Trip Solutions API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flightstats.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model;

use AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\ObjectSerializer;

/**
 * AirlineInfo Class Doc Comment.
 *
 * @category Class
 * @description Information related to the airline of the departing flight in the leg of the trip for which this alert was generated
 * @author   Swagger Codegen team
 * @see     https://github.com/swagger-api/swagger-codegen
 */
class AirlineInfo implements ModelInterface, \ArrayAccess
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $swaggerModelName = 'AirlineInfo';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $swaggerTypes = [
        'airlineCode' => 'string',
        'airlineFsCode' => 'string',
        'airlineIataCode' => 'string',
        'checkinLink' => 'string',
        'baggageLink' => 'string',
        'termsOfCarriageLink' => 'string',    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $swaggerFormats = [
        'airlineCode' => null,
        'airlineFsCode' => null,
        'airlineIataCode' => null,
        'checkinLink' => null,
        'baggageLink' => null,
        'termsOfCarriageLink' => null,    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'airlineCode' => 'airlineCode',
        'airlineFsCode' => 'airlineFsCode',
        'airlineIataCode' => 'airlineIataCode',
        'checkinLink' => 'checkinLink',
        'baggageLink' => 'baggageLink',
        'termsOfCarriageLink' => 'termsOfCarriageLink',    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'airlineCode' => 'setAirlineCode',
        'airlineFsCode' => 'setAirlineFsCode',
        'airlineIataCode' => 'setAirlineIataCode',
        'checkinLink' => 'setCheckinLink',
        'baggageLink' => 'setBaggageLink',
        'termsOfCarriageLink' => 'setTermsOfCarriageLink',    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'airlineCode' => 'getAirlineCode',
        'airlineFsCode' => 'getAirlineFsCode',
        'airlineIataCode' => 'getAirlineIataCode',
        'checkinLink' => 'getCheckinLink',
        'baggageLink' => 'getBaggageLink',
        'termsOfCarriageLink' => 'getTermsOfCarriageLink',    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['airlineCode'] = $data['airlineCode'] ?? null;
        $this->container['airlineFsCode'] = $data['airlineFsCode'] ?? null;
        $this->container['airlineIataCode'] = $data['airlineIataCode'] ?? null;
        $this->container['checkinLink'] = $data['checkinLink'] ?? null;
        $this->container['baggageLink'] = $data['baggageLink'] ?? null;
        $this->container['termsOfCarriageLink'] = $data['termsOfCarriageLink'] ?? null;
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets airlineCode.
     *
     * @return string
     */
    public function getAirlineCode()
    {
        return $this->container['airlineCode'];
    }

    /**
     * Sets airlineCode.
     *
     * @param string $airlineCode the airline code for the departing flight in the leg of the trip for the alert. This code could be either IATA or FS. This is an account level configuration.
     * @return $this
     */
    public function setAirlineCode($airlineCode)
    {
        $this->container['airlineCode'] = $airlineCode;

        return $this;
    }

    /**
     * Gets airlineFsCode.
     *
     * @return string
     */
    public function getAirlineFsCode()
    {
        return $this->container['airlineFsCode'];
    }

    /**
     * Sets airlineFsCode.
     *
     * @param string $airlineFsCode the FlightStats airline code for the departing flight in the leg of the trip for the alert
     * @return $this
     */
    public function setAirlineFsCode($airlineFsCode)
    {
        $this->container['airlineFsCode'] = $airlineFsCode;

        return $this;
    }

    /**
     * Gets airlineIataCode.
     *
     * @return string
     */
    public function getAirlineIataCode()
    {
        return $this->container['airlineIataCode'];
    }

    /**
     * Sets airlineIataCode.
     *
     * @param string $airlineIataCode the IATA airline code for the departing flight in the leg of the trip for the alert
     * @return $this
     */
    public function setAirlineIataCode($airlineIataCode)
    {
        $this->container['airlineIataCode'] = $airlineIataCode;

        return $this;
    }

    /**
     * Gets checkinLink.
     *
     * @return string
     */
    public function getCheckinLink()
    {
        return $this->container['checkinLink'];
    }

    /**
     * Sets checkinLink.
     *
     * @param string $checkinLink a URL for web checkin for the first airline in the upcoming leg of the trip
     * @return $this
     */
    public function setCheckinLink($checkinLink)
    {
        $this->container['checkinLink'] = $checkinLink;

        return $this;
    }

    /**
     * Gets baggageLink.
     *
     * @return string
     */
    public function getBaggageLink()
    {
        return $this->container['baggageLink'];
    }

    /**
     * Sets baggageLink.
     *
     * @param string $baggageLink a URL for baggage information for the first airline in the upcoming leg of the trip
     * @return $this
     */
    public function setBaggageLink($baggageLink)
    {
        $this->container['baggageLink'] = $baggageLink;

        return $this;
    }

    /**
     * Gets termsOfCarriageLink.
     *
     * @return string
     */
    public function getTermsOfCarriageLink()
    {
        return $this->container['termsOfCarriageLink'];
    }

    /**
     * Sets termsOfCarriageLink.
     *
     * @param string $termsOfCarriageLink a URL for terms of carriage for the first airline in the upcoming leg of the trip
     * @return $this
     */
    public function setTermsOfCarriageLink($termsOfCarriageLink)
    {
        $this->container['termsOfCarriageLink'] = $termsOfCarriageLink;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     * @return bool
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int $offset Offset
     * @param mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }
}
