<?php
/**
 * Alerting.
 *
 * PHP version 5
 *
 * @category Class
 * @author   Swagger Codegen team
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FlightStats, Inc. Trip Solutions API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flightstats.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model;

use AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\ObjectSerializer;

/**
 * Alerting Class Doc Comment.
 *
 * @category Class
 * @author   Swagger Codegen team
 * @see     https://github.com/swagger-api/swagger-codegen
 */
class Alerting implements ModelInterface, \ArrayAccess
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $swaggerModelName = 'Alerting';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $swaggerTypes = [
        'directEmailDeliveries' => '\AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\DirectEmailDelivery[]',
        'directSmsViaEmailDeliveries' => '\AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\DirectSmsViaEmailDelivery[]',
        'directApiDeliveries' => '\AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\DirectApiDelivery[]',
        'travelerMessaging' => '\AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\TravelerMessaging[]',    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $swaggerFormats = [
        'directEmailDeliveries' => null,
        'directSmsViaEmailDeliveries' => null,
        'directApiDeliveries' => null,
        'travelerMessaging' => null,    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'directEmailDeliveries' => 'directEmailDeliveries',
        'directSmsViaEmailDeliveries' => 'directSmsViaEmailDeliveries',
        'directApiDeliveries' => 'directApiDeliveries',
        'travelerMessaging' => 'travelerMessaging',    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'directEmailDeliveries' => 'setDirectEmailDeliveries',
        'directSmsViaEmailDeliveries' => 'setDirectSmsViaEmailDeliveries',
        'directApiDeliveries' => 'setDirectApiDeliveries',
        'travelerMessaging' => 'setTravelerMessaging',    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'directEmailDeliveries' => 'getDirectEmailDeliveries',
        'directSmsViaEmailDeliveries' => 'getDirectSmsViaEmailDeliveries',
        'directApiDeliveries' => 'getDirectApiDeliveries',
        'travelerMessaging' => 'getTravelerMessaging',    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['directEmailDeliveries'] = $data['directEmailDeliveries'] ?? null;
        $this->container['directSmsViaEmailDeliveries'] = $data['directSmsViaEmailDeliveries'] ?? null;
        $this->container['directApiDeliveries'] = $data['directApiDeliveries'] ?? null;
        $this->container['travelerMessaging'] = $data['travelerMessaging'] ?? null;
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets directEmailDeliveries.
     *
     * @return \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\DirectEmailDelivery[]
     */
    public function getDirectEmailDeliveries()
    {
        return $this->container['directEmailDeliveries'];
    }

    /**
     * Sets directEmailDeliveries.
     *
     * @param \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\DirectEmailDelivery[] $directEmailDeliveries Configuration properties to set up email alerting for this trip
     * @return $this
     */
    public function setDirectEmailDeliveries($directEmailDeliveries)
    {
        $this->container['directEmailDeliveries'] = $directEmailDeliveries;

        return $this;
    }

    /**
     * Gets directSmsViaEmailDeliveries.
     *
     * @return \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\DirectSmsViaEmailDelivery[]
     */
    public function getDirectSmsViaEmailDeliveries()
    {
        return $this->container['directSmsViaEmailDeliveries'];
    }

    /**
     * Sets directSmsViaEmailDeliveries.
     *
     * @param \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\DirectSmsViaEmailDelivery[] $directSmsViaEmailDeliveries Configuration properties to set up SMS alerts, sent via an email gateway for this trip
     * @return $this
     */
    public function setDirectSmsViaEmailDeliveries($directSmsViaEmailDeliveries)
    {
        $this->container['directSmsViaEmailDeliveries'] = $directSmsViaEmailDeliveries;

        return $this;
    }

    /**
     * Gets directApiDeliveries.
     *
     * @return \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\DirectApiDelivery[]
     */
    public function getDirectApiDeliveries()
    {
        return $this->container['directApiDeliveries'];
    }

    /**
     * Sets directApiDeliveries.
     *
     * @param \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\DirectApiDelivery[] $directApiDeliveries Configuration properties to set up API alerting for this trip
     * @return $this
     */
    public function setDirectApiDeliveries($directApiDeliveries)
    {
        $this->container['directApiDeliveries'] = $directApiDeliveries;

        return $this;
    }

    /**
     * Gets travelerMessaging.
     *
     * @return \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\TravelerMessaging[]
     */
    public function getTravelerMessaging()
    {
        return $this->container['travelerMessaging'];
    }

    /**
     * Sets travelerMessaging.
     *
     * @param \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\TravelerMessaging[] $travelerMessaging Configuration properties to set up FlightStats Travler Profile alerting for this trip
     * @return $this
     */
    public function setTravelerMessaging($travelerMessaging)
    {
        $this->container['travelerMessaging'] = $travelerMessaging;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     * @return bool
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int $offset Offset
     * @param mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }
}
