<?php
/**
 * Alert.
 *
 * PHP version 5
 *
 * @category Class
 * @author   Swagger Codegen team
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FlightStats, Inc. Trip Solutions API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flightstats.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model;

use AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\ObjectSerializer;

/**
 * Alert Class Doc Comment.
 *
 * @category Class
 * @author   Swagger Codegen team
 * @see     https://github.com/swagger-api/swagger-codegen
 */
class Alert implements ModelInterface, \ArrayAccess
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $swaggerModelName = 'Alert';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $swaggerTypes = [
        'id' => 'string',
        'contactId' => 'string',
        'alertDetails' => '\AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\AlertDetails',
        'trip' => '\AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\AlertTrip',    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $swaggerFormats = [
        'id' => null,
        'contactId' => null,
        'alertDetails' => null,
        'trip' => null,    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'contactId' => 'contactId',
        'alertDetails' => 'alertDetails',
        'trip' => 'trip',    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'contactId' => 'setContactId',
        'alertDetails' => 'setAlertDetails',
        'trip' => 'setTrip',    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'contactId' => 'getContactId',
        'alertDetails' => 'getAlertDetails',
        'trip' => 'getTrip',    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['contactId'] = $data['contactId'] ?? null;
        $this->container['alertDetails'] = $data['alertDetails'] ?? null;
        $this->container['trip'] = $data['trip'] ?? null;
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }

        if ($this->container['contactId'] === null) {
            $invalidProperties[] = "'contactId' can't be null";
        }

        if ($this->container['alertDetails'] === null) {
            $invalidProperties[] = "'alertDetails' can't be null";
        }

        if ($this->container['trip'] === null) {
            $invalidProperties[] = "'trip' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets id.
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id.
     *
     * @param string $id A unique identifier for the alert
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets contactId.
     *
     * @return string
     */
    public function getContactId()
    {
        return $this->container['contactId'];
    }

    /**
     * Sets contactId.
     *
     * @param string $contactId Who the alert was intended for
     * @return $this
     */
    public function setContactId($contactId)
    {
        $this->container['contactId'] = $contactId;

        return $this;
    }

    /**
     * Gets alertDetails.
     *
     * @return \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\AlertDetails
     */
    public function getAlertDetails()
    {
        return $this->container['alertDetails'];
    }

    /**
     * Sets alertDetails.
     *
     * @param \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\AlertDetails $alertDetails alertDetails
     * @return $this
     */
    public function setAlertDetails($alertDetails)
    {
        $this->container['alertDetails'] = $alertDetails;

        return $this;
    }

    /**
     * Gets trip.
     *
     * @return \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\AlertTrip
     */
    public function getTrip()
    {
        return $this->container['trip'];
    }

    /**
     * Sets trip.
     *
     * @param \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\AlertTrip $trip trip
     * @return $this
     */
    public function setTrip($trip)
    {
        $this->container['trip'] = $trip;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     * @return bool
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int $offset Offset
     * @param mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }
}
