<?php
/**
 * ExceptionPolicyWaiver.
 *
 * PHP version 5
 *
 * @category Class
 * @author   Swagger Codegen team
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FlightStats, Inc. Trip Solutions API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flightstats.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model;

use AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\ObjectSerializer;

/**
 * ExceptionPolicyWaiver Class Doc Comment.
 *
 * @category Class
 * @description Information about an exception waiver
 * @author   Swagger Codegen team
 * @see     https://github.com/swagger-api/swagger-codegen
 */
class ExceptionPolicyWaiver implements ModelInterface, \ArrayAccess
{
    public const DISCRIMINATOR = null;

    public const WAIVER_MATCH_REASON_TICKET_STOCK = 'Ticket Stock';
    public const WAIVER_MATCH_REASON_TICKET_ISSUE_DATE = 'Ticket Issue Date';
    public const WAIVER_MATCH_REASON_TRAVEL_DATES = 'Travel Dates';
    public const WAIVER_MATCH_REASON_AFFECTED_AIRPORT = 'Affected Airport';
    public const WAIVER_MATCH_REASON_AIRLINES = 'Airlines';
    public const WAIVER_MATCH_REASON_SPECIFIC_FLIGHT = 'Specific Flight';
    public const WAIVER_MATCH_STATE_CHANGE_ADDED = 'Match Added';
    public const WAIVER_MATCH_STATE_CHANGE_REMOVED = 'Match Removed';
    public const WAIVER_MATCH_STATE_CHANGE_CHANGED = 'Match Changed';
    public const FLIGHT_LENGTH_SHORT_HAUL = 'Short Haul';
    public const FLIGHT_LENGTH_MEDIUM_HAUL = 'Medium Haul';
    public const FLIGHT_LENGTH_LONG_HAUL = 'Long Haul';
    public const FLIGHT_LENGTH_ULTRA_LONG_HAUL = 'Ultra-Long Haul';

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $swaggerModelName = 'ExceptionPolicyWaiver';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $swaggerTypes = [
        'waiverMatchReason' => 'map[string,string]',
        'waiverMatchStateChange' => 'string',
        'id' => 'int',
        'version' => 'int',
        'waiverUrl' => 'string',
        'name' => 'string',
        'description' => 'string',
        'category' => 'string',
        'publishedDate' => 'string',
        'waiverCode' => 'string',
        'endorsementBoxPolicy' => 'string',
        'cabinToCabinCode' => 'string',
        'waiveChangeFeeCode' => 'string',
        'airlineRelationships' => '\AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\AirlineRelationship[]',
        'specificFlights' => '\AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\SpecificFlight[]',
        'affectedAirportCodes' => 'string[]',
        'affectedAirportFsCodes' => 'string[]',
        'affectedAirportIataCodes' => 'string[]',
        'affectedCountryCodes' => 'string[]',
        'systemWide' => 'bool',
        'domesticFlightsOnly' => 'bool',
        'internationalFlightsOnly' => 'bool',
        'firstEffectiveTravelDate' => 'string',
        'lastEffectiveTravelDate' => 'string',
        'firstNewTravelDate' => 'string',
        'lastNewTravelDate' => 'string',
        'newTravelDatesDetails' => 'string',
        'ticketStocks' => 'string[]',
        'ticketedOnAfter' => 'string',
        'ticketedOnBefore' => 'string',
        'reissueTicketOnBefore' => 'string',
        'osiRequirements' => 'string',
        'additionalInfo' => 'string',
        'policyLinks' => '\AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\Link[]',
        'flightLength' => 'string',
        'refundsApplicable' => 'bool',    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $swaggerFormats = [
        'waiverMatchReason' => null,
        'waiverMatchStateChange' => null,
        'id' => null,
        'version' => null,
        'waiverUrl' => null,
        'name' => null,
        'description' => null,
        'category' => null,
        'publishedDate' => null,
        'waiverCode' => null,
        'endorsementBoxPolicy' => null,
        'cabinToCabinCode' => null,
        'waiveChangeFeeCode' => null,
        'airlineRelationships' => null,
        'specificFlights' => null,
        'affectedAirportCodes' => null,
        'affectedAirportFsCodes' => null,
        'affectedAirportIataCodes' => null,
        'affectedCountryCodes' => null,
        'systemWide' => null,
        'domesticFlightsOnly' => null,
        'internationalFlightsOnly' => null,
        'firstEffectiveTravelDate' => null,
        'lastEffectiveTravelDate' => null,
        'firstNewTravelDate' => null,
        'lastNewTravelDate' => null,
        'newTravelDatesDetails' => null,
        'ticketStocks' => null,
        'ticketedOnAfter' => null,
        'ticketedOnBefore' => null,
        'reissueTicketOnBefore' => null,
        'osiRequirements' => null,
        'additionalInfo' => null,
        'policyLinks' => null,
        'flightLength' => null,
        'refundsApplicable' => null,    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'waiverMatchReason' => 'waiverMatchReason',
        'waiverMatchStateChange' => 'waiverMatchStateChange',
        'id' => 'id',
        'version' => 'version',
        'waiverUrl' => 'waiverUrl',
        'name' => 'name',
        'description' => 'description',
        'category' => 'category',
        'publishedDate' => 'publishedDate',
        'waiverCode' => 'waiverCode',
        'endorsementBoxPolicy' => 'endorsementBoxPolicy',
        'cabinToCabinCode' => 'cabinToCabinCode',
        'waiveChangeFeeCode' => 'waiveChangeFeeCode',
        'airlineRelationships' => 'airlineRelationships',
        'specificFlights' => 'specificFlights',
        'affectedAirportCodes' => 'affectedAirportCodes',
        'affectedAirportFsCodes' => 'affectedAirportFsCodes',
        'affectedAirportIataCodes' => 'affectedAirportIataCodes',
        'affectedCountryCodes' => 'affectedCountryCodes',
        'systemWide' => 'systemWide',
        'domesticFlightsOnly' => 'domesticFlightsOnly',
        'internationalFlightsOnly' => 'internationalFlightsOnly',
        'firstEffectiveTravelDate' => 'firstEffectiveTravelDate',
        'lastEffectiveTravelDate' => 'lastEffectiveTravelDate',
        'firstNewTravelDate' => 'firstNewTravelDate',
        'lastNewTravelDate' => 'lastNewTravelDate',
        'newTravelDatesDetails' => 'newTravelDatesDetails',
        'ticketStocks' => 'ticketStocks',
        'ticketedOnAfter' => 'ticketedOnAfter',
        'ticketedOnBefore' => 'ticketedOnBefore',
        'reissueTicketOnBefore' => 'reissueTicketOnBefore',
        'osiRequirements' => 'osiRequirements',
        'additionalInfo' => 'additionalInfo',
        'policyLinks' => 'policyLinks',
        'flightLength' => 'flightLength',
        'refundsApplicable' => 'refundsApplicable',    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'waiverMatchReason' => 'setWaiverMatchReason',
        'waiverMatchStateChange' => 'setWaiverMatchStateChange',
        'id' => 'setId',
        'version' => 'setVersion',
        'waiverUrl' => 'setWaiverUrl',
        'name' => 'setName',
        'description' => 'setDescription',
        'category' => 'setCategory',
        'publishedDate' => 'setPublishedDate',
        'waiverCode' => 'setWaiverCode',
        'endorsementBoxPolicy' => 'setEndorsementBoxPolicy',
        'cabinToCabinCode' => 'setCabinToCabinCode',
        'waiveChangeFeeCode' => 'setWaiveChangeFeeCode',
        'airlineRelationships' => 'setAirlineRelationships',
        'specificFlights' => 'setSpecificFlights',
        'affectedAirportCodes' => 'setAffectedAirportCodes',
        'affectedAirportFsCodes' => 'setAffectedAirportFsCodes',
        'affectedAirportIataCodes' => 'setAffectedAirportIataCodes',
        'affectedCountryCodes' => 'setAffectedCountryCodes',
        'systemWide' => 'setSystemWide',
        'domesticFlightsOnly' => 'setDomesticFlightsOnly',
        'internationalFlightsOnly' => 'setInternationalFlightsOnly',
        'firstEffectiveTravelDate' => 'setFirstEffectiveTravelDate',
        'lastEffectiveTravelDate' => 'setLastEffectiveTravelDate',
        'firstNewTravelDate' => 'setFirstNewTravelDate',
        'lastNewTravelDate' => 'setLastNewTravelDate',
        'newTravelDatesDetails' => 'setNewTravelDatesDetails',
        'ticketStocks' => 'setTicketStocks',
        'ticketedOnAfter' => 'setTicketedOnAfter',
        'ticketedOnBefore' => 'setTicketedOnBefore',
        'reissueTicketOnBefore' => 'setReissueTicketOnBefore',
        'osiRequirements' => 'setOsiRequirements',
        'additionalInfo' => 'setAdditionalInfo',
        'policyLinks' => 'setPolicyLinks',
        'flightLength' => 'setFlightLength',
        'refundsApplicable' => 'setRefundsApplicable',    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'waiverMatchReason' => 'getWaiverMatchReason',
        'waiverMatchStateChange' => 'getWaiverMatchStateChange',
        'id' => 'getId',
        'version' => 'getVersion',
        'waiverUrl' => 'getWaiverUrl',
        'name' => 'getName',
        'description' => 'getDescription',
        'category' => 'getCategory',
        'publishedDate' => 'getPublishedDate',
        'waiverCode' => 'getWaiverCode',
        'endorsementBoxPolicy' => 'getEndorsementBoxPolicy',
        'cabinToCabinCode' => 'getCabinToCabinCode',
        'waiveChangeFeeCode' => 'getWaiveChangeFeeCode',
        'airlineRelationships' => 'getAirlineRelationships',
        'specificFlights' => 'getSpecificFlights',
        'affectedAirportCodes' => 'getAffectedAirportCodes',
        'affectedAirportFsCodes' => 'getAffectedAirportFsCodes',
        'affectedAirportIataCodes' => 'getAffectedAirportIataCodes',
        'affectedCountryCodes' => 'getAffectedCountryCodes',
        'systemWide' => 'getSystemWide',
        'domesticFlightsOnly' => 'getDomesticFlightsOnly',
        'internationalFlightsOnly' => 'getInternationalFlightsOnly',
        'firstEffectiveTravelDate' => 'getFirstEffectiveTravelDate',
        'lastEffectiveTravelDate' => 'getLastEffectiveTravelDate',
        'firstNewTravelDate' => 'getFirstNewTravelDate',
        'lastNewTravelDate' => 'getLastNewTravelDate',
        'newTravelDatesDetails' => 'getNewTravelDatesDetails',
        'ticketStocks' => 'getTicketStocks',
        'ticketedOnAfter' => 'getTicketedOnAfter',
        'ticketedOnBefore' => 'getTicketedOnBefore',
        'reissueTicketOnBefore' => 'getReissueTicketOnBefore',
        'osiRequirements' => 'getOsiRequirements',
        'additionalInfo' => 'getAdditionalInfo',
        'policyLinks' => 'getPolicyLinks',
        'flightLength' => 'getFlightLength',
        'refundsApplicable' => 'getRefundsApplicable',    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['waiverMatchReason'] = $data['waiverMatchReason'] ?? null;
        $this->container['waiverMatchStateChange'] = $data['waiverMatchStateChange'] ?? null;
        $this->container['id'] = $data['id'] ?? null;
        $this->container['version'] = $data['version'] ?? null;
        $this->container['waiverUrl'] = $data['waiverUrl'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['description'] = $data['description'] ?? null;
        $this->container['category'] = $data['category'] ?? null;
        $this->container['publishedDate'] = $data['publishedDate'] ?? null;
        $this->container['waiverCode'] = $data['waiverCode'] ?? null;
        $this->container['endorsementBoxPolicy'] = $data['endorsementBoxPolicy'] ?? null;
        $this->container['cabinToCabinCode'] = $data['cabinToCabinCode'] ?? null;
        $this->container['waiveChangeFeeCode'] = $data['waiveChangeFeeCode'] ?? null;
        $this->container['airlineRelationships'] = $data['airlineRelationships'] ?? null;
        $this->container['specificFlights'] = $data['specificFlights'] ?? null;
        $this->container['affectedAirportCodes'] = $data['affectedAirportCodes'] ?? null;
        $this->container['affectedAirportFsCodes'] = $data['affectedAirportFsCodes'] ?? null;
        $this->container['affectedAirportIataCodes'] = $data['affectedAirportIataCodes'] ?? null;
        $this->container['affectedCountryCodes'] = $data['affectedCountryCodes'] ?? null;
        $this->container['systemWide'] = $data['systemWide'] ?? null;
        $this->container['domesticFlightsOnly'] = $data['domesticFlightsOnly'] ?? null;
        $this->container['internationalFlightsOnly'] = $data['internationalFlightsOnly'] ?? null;
        $this->container['firstEffectiveTravelDate'] = $data['firstEffectiveTravelDate'] ?? null;
        $this->container['lastEffectiveTravelDate'] = $data['lastEffectiveTravelDate'] ?? null;
        $this->container['firstNewTravelDate'] = $data['firstNewTravelDate'] ?? null;
        $this->container['lastNewTravelDate'] = $data['lastNewTravelDate'] ?? null;
        $this->container['newTravelDatesDetails'] = $data['newTravelDatesDetails'] ?? null;
        $this->container['ticketStocks'] = $data['ticketStocks'] ?? null;
        $this->container['ticketedOnAfter'] = $data['ticketedOnAfter'] ?? null;
        $this->container['ticketedOnBefore'] = $data['ticketedOnBefore'] ?? null;
        $this->container['reissueTicketOnBefore'] = $data['reissueTicketOnBefore'] ?? null;
        $this->container['osiRequirements'] = $data['osiRequirements'] ?? null;
        $this->container['additionalInfo'] = $data['additionalInfo'] ?? null;
        $this->container['policyLinks'] = $data['policyLinks'] ?? null;
        $this->container['flightLength'] = $data['flightLength'] ?? null;
        $this->container['refundsApplicable'] = $data['refundsApplicable'] ?? null;
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public function getWaiverMatchReasonAllowableValues()
    {
        return [
            self::WAIVER_MATCH_REASON_TICKET_STOCK,
            self::WAIVER_MATCH_REASON_TICKET_ISSUE_DATE,
            self::WAIVER_MATCH_REASON_TRAVEL_DATES,
            self::WAIVER_MATCH_REASON_AFFECTED_AIRPORT,
            self::WAIVER_MATCH_REASON_AIRLINES,
            self::WAIVER_MATCH_REASON_SPECIFIC_FLIGHT,        ];
    }

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public function getWaiverMatchStateChangeAllowableValues()
    {
        return [
            self::WAIVER_MATCH_STATE_CHANGE_ADDED,
            self::WAIVER_MATCH_STATE_CHANGE_REMOVED,
            self::WAIVER_MATCH_STATE_CHANGE_CHANGED,        ];
    }

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public function getFlightLengthAllowableValues()
    {
        return [
            self::FLIGHT_LENGTH_SHORT_HAUL,
            self::FLIGHT_LENGTH_MEDIUM_HAUL,
            self::FLIGHT_LENGTH_LONG_HAUL,
            self::FLIGHT_LENGTH_ULTRA_LONG_HAUL,        ];
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getWaiverMatchStateChangeAllowableValues();

        if (!is_null($this->container['waiverMatchStateChange']) && !in_array($this->container['waiverMatchStateChange'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'waiverMatchStateChange', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getFlightLengthAllowableValues();

        if (!is_null($this->container['flightLength']) && !in_array($this->container['flightLength'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'flightLength', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets waiverMatchReason.
     *
     * @return map[string,string]
     */
    public function getWaiverMatchReason()
    {
        return $this->container['waiverMatchReason'];
    }

    /**
     * Sets waiverMatchReason.
     *
     * @param map[string,string] $waiverMatchReason A Map of Waiver criteria (Ticket Stock, Ticket Issue Date, Travel Dates, Affected Airport, Airlines, Specific Flight) used and it's corresponding match type (Match, Mismatch, Data Not In Waiver, Data Not In Trip, Excluded)
     * @return $this
     */
    public function setWaiverMatchReason($waiverMatchReason)
    {
        $allowedValues = $this->getWaiverMatchReasonAllowableValues();

        if (!is_null($waiverMatchReason) && array_diff($waiverMatchReason, $allowedValues)) {
            throw new \InvalidArgumentException(sprintf("Invalid value for 'waiverMatchReason', must be one of '%s'", implode("', '", $allowedValues)));
        }
        $this->container['waiverMatchReason'] = $waiverMatchReason;

        return $this;
    }

    /**
     * Gets waiverMatchStateChange.
     *
     * @return string
     */
    public function getWaiverMatchStateChange()
    {
        return $this->container['waiverMatchStateChange'];
    }

    /**
     * Sets waiverMatchStateChange.
     *
     * @param string $waiverMatchStateChange Whether the waiver eligibility for this trip is newly identified, no longer applies, or the nature of the eligibility has changed
     * @return $this
     */
    public function setWaiverMatchStateChange($waiverMatchStateChange)
    {
        $allowedValues = $this->getWaiverMatchStateChangeAllowableValues();

        if (!is_null($waiverMatchStateChange) && !in_array($waiverMatchStateChange, $allowedValues, true)) {
            throw new \InvalidArgumentException(sprintf("Invalid value for 'waiverMatchStateChange', must be one of '%s'", implode("', '", $allowedValues)));
        }
        $this->container['waiverMatchStateChange'] = $waiverMatchStateChange;

        return $this;
    }

    /**
     * Gets id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id.
     *
     * @param int $id Universally unique identifier for the waiver
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets version.
     *
     * @return int
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version.
     *
     * @param int $version The waiver version number
     * @return $this
     */
    public function setVersion($version)
    {
        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets waiverUrl.
     *
     * @return string
     */
    public function getWaiverUrl()
    {
        return $this->container['waiverUrl'];
    }

    /**
     * Sets waiverUrl.
     *
     * @param string $waiverUrl The publicly accessible link to view the latest waiver details
     * @return $this
     */
    public function setWaiverUrl($waiverUrl)
    {
        $this->container['waiverUrl'] = $waiverUrl;

        return $this;
    }

    /**
     * Gets name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name.
     *
     * @param string $name The waiver name
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description.
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description.
     *
     * @param string $description A human-readable description of the waiver
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets category.
     *
     * @return string
     */
    public function getCategory()
    {
        return $this->container['category'];
    }

    /**
     * Sets category.
     *
     * @param string $category A short description of the nature of the waiver
     * @return $this
     */
    public function setCategory($category)
    {
        $this->container['category'] = $category;

        return $this;
    }

    /**
     * Gets publishedDate.
     *
     * @return string
     */
    public function getPublishedDate()
    {
        return $this->container['publishedDate'];
    }

    /**
     * Sets publishedDate.
     *
     * @param string $publishedDate The date (yyyy-MM-dd) the waiver was published by the airline
     * @return $this
     */
    public function setPublishedDate($publishedDate)
    {
        $this->container['publishedDate'] = $publishedDate;

        return $this;
    }

    /**
     * Gets waiverCode.
     *
     * @return string
     */
    public function getWaiverCode()
    {
        return $this->container['waiverCode'];
    }

    /**
     * Sets waiverCode.
     *
     * @param string $waiverCode The waiver code
     * @return $this
     */
    public function setWaiverCode($waiverCode)
    {
        $this->container['waiverCode'] = $waiverCode;

        return $this;
    }

    /**
     * Gets endorsementBoxPolicy.
     *
     * @return string
     */
    public function getEndorsementBoxPolicy()
    {
        return $this->container['endorsementBoxPolicy'];
    }

    /**
     * Sets endorsementBoxPolicy.
     *
     * @param string $endorsementBoxPolicy Airline-provided waiver code
     * @return $this
     */
    public function setEndorsementBoxPolicy($endorsementBoxPolicy)
    {
        $this->container['endorsementBoxPolicy'] = $endorsementBoxPolicy;

        return $this;
    }

    /**
     * Gets cabinToCabinCode.
     *
     * @return string
     */
    public function getCabinToCabinCode()
    {
        return $this->container['cabinToCabinCode'];
    }

    /**
     * Sets cabinToCabinCode.
     *
     * @param string $cabinToCabinCode The waiver code to use when cabin to cabin
     * @return $this
     */
    public function setCabinToCabinCode($cabinToCabinCode)
    {
        $this->container['cabinToCabinCode'] = $cabinToCabinCode;

        return $this;
    }

    /**
     * Gets waiveChangeFeeCode.
     *
     * @return string
     */
    public function getWaiveChangeFeeCode()
    {
        return $this->container['waiveChangeFeeCode'];
    }

    /**
     * Sets waiveChangeFeeCode.
     *
     * @param string $waiveChangeFeeCode The waiver code to use to waive change fee
     * @return $this
     */
    public function setWaiveChangeFeeCode($waiveChangeFeeCode)
    {
        $this->container['waiveChangeFeeCode'] = $waiveChangeFeeCode;

        return $this;
    }

    /**
     * Gets airlineRelationships.
     *
     * @return \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\AirlineRelationship[]
     */
    public function getAirlineRelationships()
    {
        return $this->container['airlineRelationships'];
    }

    /**
     * Sets airlineRelationships.
     *
     * @param \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\AirlineRelationship[] $airlineRelationships List of airline relationships that were used to match against flights in the trip to waivers
     * @return $this
     */
    public function setAirlineRelationships($airlineRelationships)
    {
        $this->container['airlineRelationships'] = $airlineRelationships;

        return $this;
    }

    /**
     * Gets specificFlights.
     *
     * @return \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\SpecificFlight[]
     */
    public function getSpecificFlights()
    {
        return $this->container['specificFlights'];
    }

    /**
     * Sets specificFlights.
     *
     * @param \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\SpecificFlight[] $specificFlights List of specific flights called out in the waiver that were used to match flights in the trip
     * @return $this
     */
    public function setSpecificFlights($specificFlights)
    {
        $this->container['specificFlights'] = $specificFlights;

        return $this;
    }

    /**
     * Gets affectedAirportCodes.
     *
     * @return string[]
     */
    public function getAffectedAirportCodes()
    {
        return $this->container['affectedAirportCodes'];
    }

    /**
     * Sets affectedAirportCodes.
     *
     * @param string[] $affectedAirportCodes List of airport codes that were used to match trips where one or more flights is either departing from or arriving to one of these airports. This code could be either IATA or FS. This is an account level configuration.
     * @return $this
     */
    public function setAffectedAirportCodes($affectedAirportCodes)
    {
        $this->container['affectedAirportCodes'] = $affectedAirportCodes;

        return $this;
    }

    /**
     * Gets affectedAirportFsCodes.
     *
     * @return string[]
     */
    public function getAffectedAirportFsCodes()
    {
        return $this->container['affectedAirportFsCodes'];
    }

    /**
     * Sets affectedAirportFsCodes.
     *
     * @param string[] $affectedAirportFsCodes List of FlightStats airport codes that were used to match trips where one or more flights is either departing from or arriving to one of these airports
     * @return $this
     */
    public function setAffectedAirportFsCodes($affectedAirportFsCodes)
    {
        $this->container['affectedAirportFsCodes'] = $affectedAirportFsCodes;

        return $this;
    }

    /**
     * Gets affectedAirportIataCodes.
     *
     * @return string[]
     */
    public function getAffectedAirportIataCodes()
    {
        return $this->container['affectedAirportIataCodes'];
    }

    /**
     * Sets affectedAirportIataCodes.
     *
     * @param string[] $affectedAirportIataCodes List of IATA airport codes that were used to match trips where one or more flights is either departing from or arriving to one of these airports
     * @return $this
     */
    public function setAffectedAirportIataCodes($affectedAirportIataCodes)
    {
        $this->container['affectedAirportIataCodes'] = $affectedAirportIataCodes;

        return $this;
    }

    /**
     * Gets affectedCountryCodes.
     *
     * @return string[]
     */
    public function getAffectedCountryCodes()
    {
        return $this->container['affectedCountryCodes'];
    }

    /**
     * Sets affectedCountryCodes.
     *
     * @param string[] $affectedCountryCodes List of FlightStats country codes that were used to match trips where one or more flights is either departing from or arriving to an airport in one of these countries
     * @return $this
     */
    public function setAffectedCountryCodes($affectedCountryCodes)
    {
        $this->container['affectedCountryCodes'] = $affectedCountryCodes;

        return $this;
    }

    /**
     * Gets systemWide.
     *
     * @return bool
     */
    public function getSystemWide()
    {
        return $this->container['systemWide'];
    }

    /**
     * Sets systemWide.
     *
     * @param bool $systemWide True if this waiver is globally applicable and not limited to a set of airports
     * @return $this
     */
    public function setSystemWide($systemWide)
    {
        $this->container['systemWide'] = $systemWide;

        return $this;
    }

    /**
     * Gets domesticFlightsOnly.
     *
     * @return bool
     */
    public function getDomesticFlightsOnly()
    {
        return $this->container['domesticFlightsOnly'];
    }

    /**
     * Sets domesticFlightsOnly.
     *
     * @param bool $domesticFlightsOnly Indicates that only flights that both departed from and arrived at an airport within the same country were matched
     * @return $this
     */
    public function setDomesticFlightsOnly($domesticFlightsOnly)
    {
        $this->container['domesticFlightsOnly'] = $domesticFlightsOnly;

        return $this;
    }

    /**
     * Gets internationalFlightsOnly.
     *
     * @return bool
     */
    public function getInternationalFlightsOnly()
    {
        return $this->container['internationalFlightsOnly'];
    }

    /**
     * Sets internationalFlightsOnly.
     *
     * @param bool $internationalFlightsOnly Indicates that only flights that departed from and arrived at an airport from different countries were matched
     * @return $this
     */
    public function setInternationalFlightsOnly($internationalFlightsOnly)
    {
        $this->container['internationalFlightsOnly'] = $internationalFlightsOnly;

        return $this;
    }

    /**
     * Gets firstEffectiveTravelDate.
     *
     * @return string
     */
    public function getFirstEffectiveTravelDate()
    {
        return $this->container['firstEffectiveTravelDate'];
    }

    /**
     * Sets firstEffectiveTravelDate.
     *
     * @param string $firstEffectiveTravelDate The first travel date (yyyy-MM-dd) in which the waiver applies
     * @return $this
     */
    public function setFirstEffectiveTravelDate($firstEffectiveTravelDate)
    {
        $this->container['firstEffectiveTravelDate'] = $firstEffectiveTravelDate;

        return $this;
    }

    /**
     * Gets lastEffectiveTravelDate.
     *
     * @return string
     */
    public function getLastEffectiveTravelDate()
    {
        return $this->container['lastEffectiveTravelDate'];
    }

    /**
     * Sets lastEffectiveTravelDate.
     *
     * @param string $lastEffectiveTravelDate The last travel date (yyyy-MM-dd) in which the waiver applies. If not provided, a last travel date has not yet been specified.
     * @return $this
     */
    public function setLastEffectiveTravelDate($lastEffectiveTravelDate)
    {
        $this->container['lastEffectiveTravelDate'] = $lastEffectiveTravelDate;

        return $this;
    }

    /**
     * Gets firstNewTravelDate.
     *
     * @return string
     */
    public function getFirstNewTravelDate()
    {
        return $this->container['firstNewTravelDate'];
    }

    /**
     * Sets firstNewTravelDate.
     *
     * @param string $firstNewTravelDate The first allowed date (yyyy-MM-dd) on which a flight can be rescheduled with waived fees
     * @return $this
     */
    public function setFirstNewTravelDate($firstNewTravelDate)
    {
        $this->container['firstNewTravelDate'] = $firstNewTravelDate;

        return $this;
    }

    /**
     * Gets lastNewTravelDate.
     *
     * @return string
     */
    public function getLastNewTravelDate()
    {
        return $this->container['lastNewTravelDate'];
    }

    /**
     * Sets lastNewTravelDate.
     *
     * @param string $lastNewTravelDate The last allowed date (yyyy-MM-dd) on which a flight can be rescheduled with waived fees
     * @return $this
     */
    public function setLastNewTravelDate($lastNewTravelDate)
    {
        $this->container['lastNewTravelDate'] = $lastNewTravelDate;

        return $this;
    }

    /**
     * Gets newTravelDatesDetails.
     *
     * @return string
     */
    public function getNewTravelDatesDetails()
    {
        return $this->container['newTravelDatesDetails'];
    }

    /**
     * Sets newTravelDatesDetails.
     *
     * @param string $newTravelDatesDetails Policy related to new travel dates for rescheduled flights
     * @return $this
     */
    public function setNewTravelDatesDetails($newTravelDatesDetails)
    {
        $this->container['newTravelDatesDetails'] = $newTravelDatesDetails;

        return $this;
    }

    /**
     * Gets ticketStocks.
     *
     * @return string[]
     */
    public function getTicketStocks()
    {
        return $this->container['ticketStocks'];
    }

    /**
     * Sets ticketStocks.
     *
     * @param string[] $ticketStocks List of ticket stock numbers that were used to match trips where one of more ticket numbers match one of these ticket stocks
     * @return $this
     */
    public function setTicketStocks($ticketStocks)
    {
        $this->container['ticketStocks'] = $ticketStocks;

        return $this;
    }

    /**
     * Gets ticketedOnAfter.
     *
     * @return string
     */
    public function getTicketedOnAfter()
    {
        return $this->container['ticketedOnAfter'];
    }

    /**
     * Sets ticketedOnAfter.
     *
     * @param string $ticketedOnAfter The date (yyyy-MM-dd) used to match trips where the tickets were issued on/after this date
     * @return $this
     */
    public function setTicketedOnAfter($ticketedOnAfter)
    {
        $this->container['ticketedOnAfter'] = $ticketedOnAfter;

        return $this;
    }

    /**
     * Gets ticketedOnBefore.
     *
     * @return string
     */
    public function getTicketedOnBefore()
    {
        return $this->container['ticketedOnBefore'];
    }

    /**
     * Sets ticketedOnBefore.
     *
     * @param string $ticketedOnBefore The date (yyyy-MM-dd) used to match trips where the tickets were issued on/before this date
     * @return $this
     */
    public function setTicketedOnBefore($ticketedOnBefore)
    {
        $this->container['ticketedOnBefore'] = $ticketedOnBefore;

        return $this;
    }

    /**
     * Gets reissueTicketOnBefore.
     *
     * @return string
     */
    public function getReissueTicketOnBefore()
    {
        return $this->container['reissueTicketOnBefore'];
    }

    /**
     * Sets reissueTicketOnBefore.
     *
     * @param string $reissueTicketOnBefore The last date (yyyy-MM-dd) by which a ticket must be reissued to get fees waived
     * @return $this
     */
    public function setReissueTicketOnBefore($reissueTicketOnBefore)
    {
        $this->container['reissueTicketOnBefore'] = $reissueTicketOnBefore;

        return $this;
    }

    /**
     * Gets osiRequirements.
     *
     * @return string
     */
    public function getOsiRequirements()
    {
        return $this->container['osiRequirements'];
    }

    /**
     * Sets osiRequirements.
     *
     * @param string $osiRequirements Supplemental information required by airline to process waiver
     * @return $this
     */
    public function setOsiRequirements($osiRequirements)
    {
        $this->container['osiRequirements'] = $osiRequirements;

        return $this;
    }

    /**
     * Gets additionalInfo.
     *
     * @return string
     */
    public function getAdditionalInfo()
    {
        return $this->container['additionalInfo'];
    }

    /**
     * Sets additionalInfo.
     *
     * @param string $additionalInfo Additional policy and processing information
     * @return $this
     */
    public function setAdditionalInfo($additionalInfo)
    {
        $this->container['additionalInfo'] = $additionalInfo;

        return $this;
    }

    /**
     * Gets policyLinks.
     *
     * @return \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\Link[]
     */
    public function getPolicyLinks()
    {
        return $this->container['policyLinks'];
    }

    /**
     * Sets policyLinks.
     *
     * @param \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\Link[] $policyLinks List of external links to the airline's waiver policies
     * @return $this
     */
    public function setPolicyLinks($policyLinks)
    {
        $this->container['policyLinks'] = $policyLinks;

        return $this;
    }

    /**
     * Gets flightLength.
     *
     * @return string
     */
    public function getFlightLength()
    {
        return $this->container['flightLength'];
    }

    /**
     * Sets flightLength.
     *
     * @param string $flightLength If the airline specified short-haul flights only, this will read \"Short Haul\"
     * @return $this
     */
    public function setFlightLength($flightLength)
    {
        $allowedValues = $this->getFlightLengthAllowableValues();

        if (!is_null($flightLength) && !in_array($flightLength, $allowedValues, true)) {
            throw new \InvalidArgumentException(sprintf("Invalid value for 'flightLength', must be one of '%s'", implode("', '", $allowedValues)));
        }
        $this->container['flightLength'] = $flightLength;

        return $this;
    }

    /**
     * Gets refundsApplicable.
     *
     * @return bool
     */
    public function getRefundsApplicable()
    {
        return $this->container['refundsApplicable'];
    }

    /**
     * Sets refundsApplicable.
     *
     * @param bool $refundsApplicable True if airline policy supports refunds
     * @return $this
     */
    public function setRefundsApplicable($refundsApplicable)
    {
        $this->container['refundsApplicable'] = $refundsApplicable;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     * @return bool
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int $offset Offset
     * @param mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }
}
