<?php
/**
 * ImportFlight.
 *
 * PHP version 5
 *
 * @category Class
 * @author   Swagger Codegen team
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FlightStats, Inc. Trip Solutions API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flightstats.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model;

use AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\ObjectSerializer;

/**
 * ImportFlight Class Doc Comment.
 *
 * @category Class
 * @author   Swagger Codegen team
 * @see     https://github.com/swagger-api/swagger-codegen
 */
class ImportFlight implements ModelInterface, \ArrayAccess
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $swaggerModelName = 'ImportFlight';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $swaggerTypes = [
        'bookedAirlineCode' => 'string',
        'flightNumber' => 'string',
        'airlineConfirmationCode' => 'string',
        'departure' => '\AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\ImportAirportDetail',
        'arrival' => '\AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\ImportAirportDetail',    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $swaggerFormats = [
        'bookedAirlineCode' => null,
        'flightNumber' => null,
        'airlineConfirmationCode' => null,
        'departure' => null,
        'arrival' => null,    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'bookedAirlineCode' => 'bookedAirlineCode',
        'flightNumber' => 'flightNumber',
        'airlineConfirmationCode' => 'airlineConfirmationCode',
        'departure' => 'departure',
        'arrival' => 'arrival',    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'bookedAirlineCode' => 'setBookedAirlineCode',
        'flightNumber' => 'setFlightNumber',
        'airlineConfirmationCode' => 'setAirlineConfirmationCode',
        'departure' => 'setDeparture',
        'arrival' => 'setArrival',    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'bookedAirlineCode' => 'getBookedAirlineCode',
        'flightNumber' => 'getFlightNumber',
        'airlineConfirmationCode' => 'getAirlineConfirmationCode',
        'departure' => 'getDeparture',
        'arrival' => 'getArrival',    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['bookedAirlineCode'] = $data['bookedAirlineCode'] ?? null;
        $this->container['flightNumber'] = $data['flightNumber'] ?? null;
        $this->container['airlineConfirmationCode'] = $data['airlineConfirmationCode'] ?? null;
        $this->container['departure'] = $data['departure'] ?? null;
        $this->container['arrival'] = $data['arrival'] ?? null;
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['bookedAirlineCode'] === null) {
            $invalidProperties[] = "'bookedAirlineCode' can't be null";
        }

        if ($this->container['flightNumber'] === null) {
            $invalidProperties[] = "'flightNumber' can't be null";
        }

        if ($this->container['departure'] === null) {
            $invalidProperties[] = "'departure' can't be null";
        }

        if ($this->container['arrival'] === null) {
            $invalidProperties[] = "'arrival' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets bookedAirlineCode.
     *
     * @return string
     */
    public function getBookedAirlineCode()
    {
        return $this->container['bookedAirlineCode'];
    }

    /**
     * Sets bookedAirlineCode.
     *
     * @param string $bookedAirlineCode The IATA airline code. Support for sending an FS code is deprecated and is only supported with an account level configuration.
     * @return $this
     */
    public function setBookedAirlineCode($bookedAirlineCode)
    {
        $this->container['bookedAirlineCode'] = $bookedAirlineCode;

        return $this;
    }

    /**
     * Gets flightNumber.
     *
     * @return string
     */
    public function getFlightNumber()
    {
        return $this->container['flightNumber'];
    }

    /**
     * Sets flightNumber.
     *
     * @param string $flightNumber Flight number
     * @return $this
     */
    public function setFlightNumber($flightNumber)
    {
        $this->container['flightNumber'] = $flightNumber;

        return $this;
    }

    /**
     * Gets airlineConfirmationCode.
     *
     * @return string
     */
    public function getAirlineConfirmationCode()
    {
        return $this->container['airlineConfirmationCode'];
    }

    /**
     * Sets airlineConfirmationCode.
     *
     * @param string $airlineConfirmationCode Airline's record locator
     * @return $this
     */
    public function setAirlineConfirmationCode($airlineConfirmationCode)
    {
        $this->container['airlineConfirmationCode'] = $airlineConfirmationCode;

        return $this;
    }

    /**
     * Gets departure.
     *
     * @return \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\ImportAirportDetail
     */
    public function getDeparture()
    {
        return $this->container['departure'];
    }

    /**
     * Sets departure.
     *
     * @param \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\ImportAirportDetail $departure departure
     * @return $this
     */
    public function setDeparture($departure)
    {
        $this->container['departure'] = $departure;

        return $this;
    }

    /**
     * Gets arrival.
     *
     * @return \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\ImportAirportDetail
     */
    public function getArrival()
    {
        return $this->container['arrival'];
    }

    /**
     * Sets arrival.
     *
     * @param \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\ImportAirportDetail $arrival arrival
     * @return $this
     */
    public function setArrival($arrival)
    {
        $this->container['arrival'] = $arrival;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     * @return bool
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int $offset Offset
     * @param mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }
}
