<?php
/**
 * SpecificFlight.
 *
 * PHP version 5
 *
 * @category Class
 * @author   Swagger Codegen team
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FlightStats, Inc. Trip Solutions API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flightstats.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model;

use AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\ObjectSerializer;

/**
 * SpecificFlight Class Doc Comment.
 *
 * @category Class
 * @description A set of specific flights used to match trips to waivers. Matches any flight with the given criteria that departs between the firstDepartureDate and lastDepartureDate
 * @author   Swagger Codegen team
 * @see     https://github.com/swagger-api/swagger-codegen
 */
class SpecificFlight implements ModelInterface, \ArrayAccess
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $swaggerModelName = 'SpecificFlight';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $swaggerTypes = [
        'airlineCode' => 'string',
        'airlineFsCode' => 'string',
        'airlineIataCode' => 'string',
        'flightNumber' => 'string',
        'departureAirportCode' => 'string',
        'departureAirportFsCode' => 'string',
        'departureAirportIataCode' => 'string',
        'arrivalAirportCode' => 'string',
        'arrivalAirportFsCode' => 'string',
        'arrivalAirportIataCode' => 'string',
        'firstDepartureDate' => 'string',
        'lastDepartureDate' => 'string',    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $swaggerFormats = [
        'airlineCode' => null,
        'airlineFsCode' => null,
        'airlineIataCode' => null,
        'flightNumber' => null,
        'departureAirportCode' => null,
        'departureAirportFsCode' => null,
        'departureAirportIataCode' => null,
        'arrivalAirportCode' => null,
        'arrivalAirportFsCode' => null,
        'arrivalAirportIataCode' => null,
        'firstDepartureDate' => null,
        'lastDepartureDate' => null,    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'airlineCode' => 'airlineCode',
        'airlineFsCode' => 'airlineFsCode',
        'airlineIataCode' => 'airlineIataCode',
        'flightNumber' => 'flightNumber',
        'departureAirportCode' => 'departureAirportCode',
        'departureAirportFsCode' => 'departureAirportFsCode',
        'departureAirportIataCode' => 'departureAirportIataCode',
        'arrivalAirportCode' => 'arrivalAirportCode',
        'arrivalAirportFsCode' => 'arrivalAirportFsCode',
        'arrivalAirportIataCode' => 'arrivalAirportIataCode',
        'firstDepartureDate' => 'firstDepartureDate',
        'lastDepartureDate' => 'lastDepartureDate',    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'airlineCode' => 'setAirlineCode',
        'airlineFsCode' => 'setAirlineFsCode',
        'airlineIataCode' => 'setAirlineIataCode',
        'flightNumber' => 'setFlightNumber',
        'departureAirportCode' => 'setDepartureAirportCode',
        'departureAirportFsCode' => 'setDepartureAirportFsCode',
        'departureAirportIataCode' => 'setDepartureAirportIataCode',
        'arrivalAirportCode' => 'setArrivalAirportCode',
        'arrivalAirportFsCode' => 'setArrivalAirportFsCode',
        'arrivalAirportIataCode' => 'setArrivalAirportIataCode',
        'firstDepartureDate' => 'setFirstDepartureDate',
        'lastDepartureDate' => 'setLastDepartureDate',    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'airlineCode' => 'getAirlineCode',
        'airlineFsCode' => 'getAirlineFsCode',
        'airlineIataCode' => 'getAirlineIataCode',
        'flightNumber' => 'getFlightNumber',
        'departureAirportCode' => 'getDepartureAirportCode',
        'departureAirportFsCode' => 'getDepartureAirportFsCode',
        'departureAirportIataCode' => 'getDepartureAirportIataCode',
        'arrivalAirportCode' => 'getArrivalAirportCode',
        'arrivalAirportFsCode' => 'getArrivalAirportFsCode',
        'arrivalAirportIataCode' => 'getArrivalAirportIataCode',
        'firstDepartureDate' => 'getFirstDepartureDate',
        'lastDepartureDate' => 'getLastDepartureDate',    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['airlineCode'] = $data['airlineCode'] ?? null;
        $this->container['airlineFsCode'] = $data['airlineFsCode'] ?? null;
        $this->container['airlineIataCode'] = $data['airlineIataCode'] ?? null;
        $this->container['flightNumber'] = $data['flightNumber'] ?? null;
        $this->container['departureAirportCode'] = $data['departureAirportCode'] ?? null;
        $this->container['departureAirportFsCode'] = $data['departureAirportFsCode'] ?? null;
        $this->container['departureAirportIataCode'] = $data['departureAirportIataCode'] ?? null;
        $this->container['arrivalAirportCode'] = $data['arrivalAirportCode'] ?? null;
        $this->container['arrivalAirportFsCode'] = $data['arrivalAirportFsCode'] ?? null;
        $this->container['arrivalAirportIataCode'] = $data['arrivalAirportIataCode'] ?? null;
        $this->container['firstDepartureDate'] = $data['firstDepartureDate'] ?? null;
        $this->container['lastDepartureDate'] = $data['lastDepartureDate'] ?? null;
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets airlineCode.
     *
     * @return string
     */
    public function getAirlineCode()
    {
        return $this->container['airlineCode'];
    }

    /**
     * Sets airlineCode.
     *
     * @param string $airlineCode (deprecated - prefer airlineIataCode) The airline code that is applied as either the booked airline code or operating airline code for a flight segment. This code could be either IATA or FS. This is an account level configuration.
     * @return $this
     */
    public function setAirlineCode($airlineCode)
    {
        $this->container['airlineCode'] = $airlineCode;

        return $this;
    }

    /**
     * Gets airlineFsCode.
     *
     * @return string
     */
    public function getAirlineFsCode()
    {
        return $this->container['airlineFsCode'];
    }

    /**
     * Sets airlineFsCode.
     *
     * @param string $airlineFsCode (deprecated - prefer airlineIataCode) The FlightStats airline code that is applied as either the booked airline code or operating airline code for a flight segment
     * @return $this
     */
    public function setAirlineFsCode($airlineFsCode)
    {
        $this->container['airlineFsCode'] = $airlineFsCode;

        return $this;
    }

    /**
     * Gets airlineIataCode.
     *
     * @return string
     */
    public function getAirlineIataCode()
    {
        return $this->container['airlineIataCode'];
    }

    /**
     * Sets airlineIataCode.
     *
     * @param string $airlineIataCode The IATA airline code that is applied as either the booked airline code or operating airline code for a flight segment
     * @return $this
     */
    public function setAirlineIataCode($airlineIataCode)
    {
        $this->container['airlineIataCode'] = $airlineIataCode;

        return $this;
    }

    /**
     * Gets flightNumber.
     *
     * @return string
     */
    public function getFlightNumber()
    {
        return $this->container['flightNumber'];
    }

    /**
     * Sets flightNumber.
     *
     * @param string $flightNumber The flight number
     * @return $this
     */
    public function setFlightNumber($flightNumber)
    {
        $this->container['flightNumber'] = $flightNumber;

        return $this;
    }

    /**
     * Gets departureAirportCode.
     *
     * @return string
     */
    public function getDepartureAirportCode()
    {
        return $this->container['departureAirportCode'];
    }

    /**
     * Sets departureAirportCode.
     *
     * @param string $departureAirportCode The airport code for the departure airport. This code could be either IATA or FS. This is an account level configuration.
     * @return $this
     */
    public function setDepartureAirportCode($departureAirportCode)
    {
        $this->container['departureAirportCode'] = $departureAirportCode;

        return $this;
    }

    /**
     * Gets departureAirportFsCode.
     *
     * @return string
     */
    public function getDepartureAirportFsCode()
    {
        return $this->container['departureAirportFsCode'];
    }

    /**
     * Sets departureAirportFsCode.
     *
     * @param string $departureAirportFsCode The FlightStats airport code for the departure airport
     * @return $this
     */
    public function setDepartureAirportFsCode($departureAirportFsCode)
    {
        $this->container['departureAirportFsCode'] = $departureAirportFsCode;

        return $this;
    }

    /**
     * Gets departureAirportIataCode.
     *
     * @return string
     */
    public function getDepartureAirportIataCode()
    {
        return $this->container['departureAirportIataCode'];
    }

    /**
     * Sets departureAirportIataCode.
     *
     * @param string $departureAirportIataCode The IATA airport code for the departure airport
     * @return $this
     */
    public function setDepartureAirportIataCode($departureAirportIataCode)
    {
        $this->container['departureAirportIataCode'] = $departureAirportIataCode;

        return $this;
    }

    /**
     * Gets arrivalAirportCode.
     *
     * @return string
     */
    public function getArrivalAirportCode()
    {
        return $this->container['arrivalAirportCode'];
    }

    /**
     * Sets arrivalAirportCode.
     *
     * @param string $arrivalAirportCode The airport code for the arrival airport. This code could be either IATA or FS. This is an account level configuration.
     * @return $this
     */
    public function setArrivalAirportCode($arrivalAirportCode)
    {
        $this->container['arrivalAirportCode'] = $arrivalAirportCode;

        return $this;
    }

    /**
     * Gets arrivalAirportFsCode.
     *
     * @return string
     */
    public function getArrivalAirportFsCode()
    {
        return $this->container['arrivalAirportFsCode'];
    }

    /**
     * Sets arrivalAirportFsCode.
     *
     * @param string $arrivalAirportFsCode The FlightStats airport code for the arrival airport
     * @return $this
     */
    public function setArrivalAirportFsCode($arrivalAirportFsCode)
    {
        $this->container['arrivalAirportFsCode'] = $arrivalAirportFsCode;

        return $this;
    }

    /**
     * Gets arrivalAirportIataCode.
     *
     * @return string
     */
    public function getArrivalAirportIataCode()
    {
        return $this->container['arrivalAirportIataCode'];
    }

    /**
     * Sets arrivalAirportIataCode.
     *
     * @param string $arrivalAirportIataCode The IATA airport code for the arrival airport
     * @return $this
     */
    public function setArrivalAirportIataCode($arrivalAirportIataCode)
    {
        $this->container['arrivalAirportIataCode'] = $arrivalAirportIataCode;

        return $this;
    }

    /**
     * Gets firstDepartureDate.
     *
     * @return string
     */
    public function getFirstDepartureDate()
    {
        return $this->container['firstDepartureDate'];
    }

    /**
     * Sets firstDepartureDate.
     *
     * @param string $firstDepartureDate The earliest depature date this flight may apply to (yyyy-MM-dd)
     * @return $this
     */
    public function setFirstDepartureDate($firstDepartureDate)
    {
        $this->container['firstDepartureDate'] = $firstDepartureDate;

        return $this;
    }

    /**
     * Gets lastDepartureDate.
     *
     * @return string
     */
    public function getLastDepartureDate()
    {
        return $this->container['lastDepartureDate'];
    }

    /**
     * Sets lastDepartureDate.
     *
     * @param string $lastDepartureDate The latest depature date this flight may apply to (yyyy-MM-dd)
     * @return $this
     */
    public function setLastDepartureDate($lastDepartureDate)
    {
        $this->container['lastDepartureDate'] = $lastDepartureDate;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     * @return bool
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int $offset Offset
     * @param mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }
}
