<?php
/**
 * TripImport.
 *
 * PHP version 5
 *
 * @category Class
 * @author   Swagger Codegen team
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FlightStats, Inc. Trip Solutions API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flightstats.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model;

use AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\ObjectSerializer;

/**
 * TripImport Class Doc Comment.
 *
 * @category Class
 * @description The TripImport object spcified when import trips
 * @author   Swagger Codegen team
 * @see     https://github.com/swagger-api/swagger-codegen
 */
class TripImport implements ModelInterface, \ArrayAccess
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $swaggerModelName = 'TripImport';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $swaggerTypes = [
        'referenceNumber' => 'string',
        'cancelled' => 'bool',
        'flights' => '\AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\ImportFlight[]',
        'attributes' => 'map[string,string]',
        'passengers' => '\AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\ImportPassenger[]',
        'alerting' => '\AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\Alerting',
        'tickets' => '\AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\Ticket[]',    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $swaggerFormats = [
        'referenceNumber' => null,
        'cancelled' => null,
        'flights' => null,
        'attributes' => null,
        'passengers' => null,
        'alerting' => null,
        'tickets' => null,    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'referenceNumber' => 'referenceNumber',
        'cancelled' => 'cancelled',
        'flights' => 'flights',
        'attributes' => 'attributes',
        'passengers' => 'passengers',
        'alerting' => 'alerting',
        'tickets' => 'tickets',    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'referenceNumber' => 'setReferenceNumber',
        'cancelled' => 'setCancelled',
        'flights' => 'setFlights',
        'attributes' => 'setAttributes',
        'passengers' => 'setPassengers',
        'alerting' => 'setAlerting',
        'tickets' => 'setTickets',    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'referenceNumber' => 'getReferenceNumber',
        'cancelled' => 'getCancelled',
        'flights' => 'getFlights',
        'attributes' => 'getAttributes',
        'passengers' => 'getPassengers',
        'alerting' => 'getAlerting',
        'tickets' => 'getTickets',    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['referenceNumber'] = $data['referenceNumber'] ?? null;
        $this->container['cancelled'] = $data['cancelled'] ?? null;
        $this->container['flights'] = $data['flights'] ?? null;
        $this->container['attributes'] = $data['attributes'] ?? null;
        $this->container['passengers'] = $data['passengers'] ?? null;
        $this->container['alerting'] = $data['alerting'] ?? null;
        $this->container['tickets'] = $data['tickets'] ?? null;
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['referenceNumber'] === null) {
            $invalidProperties[] = "'referenceNumber' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets referenceNumber.
     *
     * @return string
     */
    public function getReferenceNumber()
    {
        return $this->container['referenceNumber'];
    }

    /**
     * Sets referenceNumber.
     *
     * @param string $referenceNumber Identifier for the trip that is unique amongst current and future trips. Most often set to the record locator from the PNR or a customer provided system key
     * @return $this
     */
    public function setReferenceNumber($referenceNumber)
    {
        $this->container['referenceNumber'] = $referenceNumber;

        return $this;
    }

    /**
     * Gets cancelled.
     *
     * @return bool
     */
    public function getCancelled()
    {
        return $this->container['cancelled'];
    }

    /**
     * Sets cancelled.
     *
     * @param bool $cancelled True if this trips is cancelled
     * @return $this
     */
    public function setCancelled($cancelled)
    {
        $this->container['cancelled'] = $cancelled;

        return $this;
    }

    /**
     * Gets flights.
     *
     * @return \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\ImportFlight[]
     */
    public function getFlights()
    {
        return $this->container['flights'];
    }

    /**
     * Sets flights.
     *
     * @param \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\ImportFlight[] $flights flights
     * @return $this
     */
    public function setFlights($flights)
    {
        $this->container['flights'] = $flights;

        return $this;
    }

    /**
     * Gets attributes.
     *
     * @return map[string,string]
     */
    public function getAttributes()
    {
        return $this->container['attributes'];
    }

    /**
     * Sets attributes.
     *
     * @param map[string,string] $attributes A Map of Attributes associated with the trip
     * @return $this
     */
    public function setAttributes($attributes)
    {
        $this->container['attributes'] = $attributes;

        return $this;
    }

    /**
     * Gets passengers.
     *
     * @return \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\ImportPassenger[]
     */
    public function getPassengers()
    {
        return $this->container['passengers'];
    }

    /**
     * Sets passengers.
     *
     * @param \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\ImportPassenger[] $passengers passengers
     * @return $this
     */
    public function setPassengers($passengers)
    {
        $this->container['passengers'] = $passengers;

        return $this;
    }

    /**
     * Gets alerting.
     *
     * @return \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\Alerting
     */
    public function getAlerting()
    {
        return $this->container['alerting'];
    }

    /**
     * Sets alerting.
     *
     * @param \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\Alerting $alerting alerting
     * @return $this
     */
    public function setAlerting($alerting)
    {
        $this->container['alerting'] = $alerting;

        return $this;
    }

    /**
     * Gets tickets.
     *
     * @return \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\Ticket[]
     */
    public function getTickets()
    {
        return $this->container['tickets'];
    }

    /**
     * Sets tickets.
     *
     * @param \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\Ticket[] $tickets tickets
     * @return $this
     */
    public function setTickets($tickets)
    {
        $this->container['tickets'] = $tickets;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     * @return bool
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int $offset Offset
     * @param mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }
}
