<?php
/**
 * TripImportResponse.
 *
 * PHP version 5
 *
 * @category Class
 * @author   Swagger Codegen team
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FlightStats, Inc. Trip Solutions API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flightstats.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model;

use AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\ObjectSerializer;

/**
 * TripImportResponse Class Doc Comment.
 *
 * @category Class
 * @author   Swagger Codegen team
 * @see     https://github.com/swagger-api/swagger-codegen
 */
class TripImportResponse implements ModelInterface, \ArrayAccess
{
    public const DISCRIMINATOR = null;

    public const STATUS_SUCCESS = 'Success';
    public const STATUS_IMPORT_FAILURE = 'Import Failure';
    public const STATUS_VALIDATION_ERROR_S = 'Validation Error(s)';
    public const STATUS_NOT_MONITORABLE__SOME_PART_OF_THE_TRIP_MAY_NOT_BE_MONITORABLE = 'Not Monitorable';

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $swaggerModelName = 'TripImportResponse';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $swaggerTypes = [
        'referenceNumber' => 'string',
        'status' => 'string',
        'importNotes' => 'string[]',
        'errors' => 'string[]',    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $swaggerFormats = [
        'referenceNumber' => null,
        'status' => null,
        'importNotes' => null,
        'errors' => null,    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'referenceNumber' => 'referenceNumber',
        'status' => 'status',
        'importNotes' => 'importNotes',
        'errors' => 'errors',    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'referenceNumber' => 'setReferenceNumber',
        'status' => 'setStatus',
        'importNotes' => 'setImportNotes',
        'errors' => 'setErrors',    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'referenceNumber' => 'getReferenceNumber',
        'status' => 'getStatus',
        'importNotes' => 'getImportNotes',
        'errors' => 'getErrors',    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['referenceNumber'] = $data['referenceNumber'] ?? null;
        $this->container['status'] = $data['status'] ?? null;
        $this->container['importNotes'] = $data['importNotes'] ?? null;
        $this->container['errors'] = $data['errors'] ?? null;
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_SUCCESS,
            self::STATUS_IMPORT_FAILURE,
            self::STATUS_VALIDATION_ERROR_S,
            self::STATUS_NOT_MONITORABLE__SOME_PART_OF_THE_TRIP_MAY_NOT_BE_MONITORABLE,        ];
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['referenceNumber'] === null) {
            $invalidProperties[] = "'referenceNumber' can't be null";
        }

        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        $allowedValues = $this->getStatusAllowableValues();

        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "Invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets referenceNumber.
     *
     * @return string
     */
    public function getReferenceNumber()
    {
        return $this->container['referenceNumber'];
    }

    /**
     * Sets referenceNumber.
     *
     * @param string $referenceNumber Identifier for the trip that is unique amongst current and future trips. Most often set to the record locator from the PNR or a customer provided system key
     * @return $this
     */
    public function setReferenceNumber($referenceNumber)
    {
        $this->container['referenceNumber'] = $referenceNumber;

        return $this;
    }

    /**
     * Gets status.
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status.
     *
     * @param string $status Indicates how the Trip was handled
     * @return $this
     */
    public function setStatus($status)
    {
        $allowedValues = $this->getStatusAllowableValues();

        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(sprintf("Invalid value '%s' for 'status', must be one of '%s'", $status, implode("', '", $allowedValues)));
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets importNotes.
     *
     * @return string[]
     */
    public function getImportNotes()
    {
        return $this->container['importNotes'];
    }

    /**
     * Sets importNotes.
     *
     * @param string[] $importNotes Notes pertaining to the trip import
     * @return $this
     */
    public function setImportNotes($importNotes)
    {
        $this->container['importNotes'] = $importNotes;

        return $this;
    }

    /**
     * Gets errors.
     *
     * @return string[]
     */
    public function getErrors()
    {
        return $this->container['errors'];
    }

    /**
     * Sets errors.
     *
     * @param string[] $errors List of errors that prevented the trip from being imported
     * @return $this
     */
    public function setErrors($errors)
    {
        $this->container['errors'] = $errors;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     * @return bool
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int $offset Offset
     * @param mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }
}
