<?php
/**
 * WaiverInfo.
 *
 * PHP version 5
 *
 * @category Class
 * @author   Swagger Codegen team
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FlightStats, Inc. Trip Solutions API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flightstats.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model;

use AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\ObjectSerializer;

/**
 * WaiverInfo Class Doc Comment.
 *
 * @category Class
 * @description Information detailing a waiver that matches a trip that may be eligible for the waiver
 * @author   Swagger Codegen team
 * @see     https://github.com/swagger-api/swagger-codegen
 */
class WaiverInfo implements ModelInterface, \ArrayAccess
{
    public const DISCRIMINATOR = null;

    public const WAIVER_TYPE_STANDING_POLICY_WAIVER = 'Standing Policy Waiver';
    public const WAIVER_TYPE_EXCEPTION_WAIVER = 'Exception Waiver';

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $swaggerModelName = 'WaiverInfo';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $swaggerTypes = [
        'issuingAirlineCode' => 'string',
        'issuingAirlineFsCode' => 'string',
        'issuingAirlineIataCode' => 'string',
        'waiverType' => 'string',
        'exceptionPolicy' => '\AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\ExceptionPolicyWaiver',
        'standingPolicy' => '\AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\StandingPolicyWaiver',    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $swaggerFormats = [
        'issuingAirlineCode' => null,
        'issuingAirlineFsCode' => null,
        'issuingAirlineIataCode' => null,
        'waiverType' => null,
        'exceptionPolicy' => null,
        'standingPolicy' => null,    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'issuingAirlineCode' => 'issuingAirlineCode',
        'issuingAirlineFsCode' => 'issuingAirlineFsCode',
        'issuingAirlineIataCode' => 'issuingAirlineIataCode',
        'waiverType' => 'waiverType',
        'exceptionPolicy' => 'exceptionPolicy',
        'standingPolicy' => 'standingPolicy',    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'issuingAirlineCode' => 'setIssuingAirlineCode',
        'issuingAirlineFsCode' => 'setIssuingAirlineFsCode',
        'issuingAirlineIataCode' => 'setIssuingAirlineIataCode',
        'waiverType' => 'setWaiverType',
        'exceptionPolicy' => 'setExceptionPolicy',
        'standingPolicy' => 'setStandingPolicy',    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'issuingAirlineCode' => 'getIssuingAirlineCode',
        'issuingAirlineFsCode' => 'getIssuingAirlineFsCode',
        'issuingAirlineIataCode' => 'getIssuingAirlineIataCode',
        'waiverType' => 'getWaiverType',
        'exceptionPolicy' => 'getExceptionPolicy',
        'standingPolicy' => 'getStandingPolicy',    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['issuingAirlineCode'] = $data['issuingAirlineCode'] ?? null;
        $this->container['issuingAirlineFsCode'] = $data['issuingAirlineFsCode'] ?? null;
        $this->container['issuingAirlineIataCode'] = $data['issuingAirlineIataCode'] ?? null;
        $this->container['waiverType'] = $data['waiverType'] ?? null;
        $this->container['exceptionPolicy'] = $data['exceptionPolicy'] ?? null;
        $this->container['standingPolicy'] = $data['standingPolicy'] ?? null;
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public function getWaiverTypeAllowableValues()
    {
        return [
            self::WAIVER_TYPE_STANDING_POLICY_WAIVER,
            self::WAIVER_TYPE_EXCEPTION_WAIVER,        ];
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['issuingAirlineCode'] === null) {
            $invalidProperties[] = "'issuingAirlineCode' can't be null";
        }

        if ($this->container['issuingAirlineFsCode'] === null) {
            $invalidProperties[] = "'issuingAirlineFsCode' can't be null";
        }

        if ($this->container['waiverType'] === null) {
            $invalidProperties[] = "'waiverType' can't be null";
        }
        $allowedValues = $this->getWaiverTypeAllowableValues();

        if (!is_null($this->container['waiverType']) && !in_array($this->container['waiverType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'waiverType', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets issuingAirlineCode.
     *
     * @return string
     */
    public function getIssuingAirlineCode()
    {
        return $this->container['issuingAirlineCode'];
    }

    /**
     * Sets issuingAirlineCode.
     *
     * @param string $issuingAirlineCode airline code for the flight that may be eligible for the waiver. This code could be either IATA or FS. This is an account level configuration.
     * @return $this
     */
    public function setIssuingAirlineCode($issuingAirlineCode)
    {
        $this->container['issuingAirlineCode'] = $issuingAirlineCode;

        return $this;
    }

    /**
     * Gets issuingAirlineFsCode.
     *
     * @return string
     */
    public function getIssuingAirlineFsCode()
    {
        return $this->container['issuingAirlineFsCode'];
    }

    /**
     * Sets issuingAirlineFsCode.
     *
     * @param string $issuingAirlineFsCode FlightStats airline code for the flight that may be eligible for the waiver
     * @return $this
     */
    public function setIssuingAirlineFsCode($issuingAirlineFsCode)
    {
        $this->container['issuingAirlineFsCode'] = $issuingAirlineFsCode;

        return $this;
    }

    /**
     * Gets issuingAirlineIataCode.
     *
     * @return string
     */
    public function getIssuingAirlineIataCode()
    {
        return $this->container['issuingAirlineIataCode'];
    }

    /**
     * Sets issuingAirlineIataCode.
     *
     * @param string $issuingAirlineIataCode IATA airline code for the flight that may be eligible for the waiver
     * @return $this
     */
    public function setIssuingAirlineIataCode($issuingAirlineIataCode)
    {
        $this->container['issuingAirlineIataCode'] = $issuingAirlineIataCode;

        return $this;
    }

    /**
     * Gets waiverType.
     *
     * @return string
     */
    public function getWaiverType()
    {
        return $this->container['waiverType'];
    }

    /**
     * Sets waiverType.
     *
     * @param string $waiverType The type of waiver
     * @return $this
     */
    public function setWaiverType($waiverType)
    {
        $allowedValues = $this->getWaiverTypeAllowableValues();

        if (!in_array($waiverType, $allowedValues, true)) {
            throw new \InvalidArgumentException(sprintf("Invalid value for 'waiverType', must be one of '%s'", implode("', '", $allowedValues)));
        }
        $this->container['waiverType'] = $waiverType;

        return $this;
    }

    /**
     * Gets exceptionPolicy.
     *
     * @return \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\ExceptionPolicyWaiver
     */
    public function getExceptionPolicy()
    {
        return $this->container['exceptionPolicy'];
    }

    /**
     * Sets exceptionPolicy.
     *
     * @param \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\ExceptionPolicyWaiver $exceptionPolicy exceptionPolicy
     * @return $this
     */
    public function setExceptionPolicy($exceptionPolicy)
    {
        $this->container['exceptionPolicy'] = $exceptionPolicy;

        return $this;
    }

    /**
     * Gets standingPolicy.
     *
     * @return \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\StandingPolicyWaiver
     */
    public function getStandingPolicy()
    {
        return $this->container['standingPolicy'];
    }

    /**
     * Sets standingPolicy.
     *
     * @param \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\StandingPolicyWaiver $standingPolicy standingPolicy
     * @return $this
     */
    public function setStandingPolicy($standingPolicy)
    {
        $this->container['standingPolicy'] = $standingPolicy;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     * @return bool
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int $offset Offset
     * @param mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }
}
