<?php

namespace AwardWallet\MainBundle\Service\RA\Hotel;

class TestApi extends Api
{
    protected function call(string $method, string $path, ?string $data = null): \HttpDriverResponse
    {
        if ($path === '/v1/search') {
            $query = json_decode($data, true);
            $query['userData'] = $userData = json_decode($query['userData'], true);
            $requestId = $userData['cacheKey'];

            $this->saveInCache(
                $requestId,
                [
                    'query' => $query,
                    'resultTs' => time() + random_int(15, 60),
                ]
            );

            return new \HttpDriverResponse(
                json_encode([
                    'requestId' => $userData['cacheKey'],
                ]),
                200
            );
        } elseif (preg_match('/^\/v1\/getResults\/(?<requestId>\w+)$/', $path, $matches)) {
            $requestId = $matches['requestId'];
            $cached = $this->getFromCache($requestId);

            if (!$cached) {
                return new \HttpDriverResponse(
                    json_encode([
                        'requestId' => $requestId,
                        'state' => 'queued_up',
                    ]),
                    200
                );
            }

            $query = $cached['query'];
            $resultTs = $cached['resultTs'];

            if (time() >= $resultTs) {
                return new \HttpDriverResponse(
                    json_encode([
                        'requestId' => $requestId,
                        'state' => 'success',
                        'message' => 'Success',
                        'requestDate' => date('c'),
                        'userData' => json_encode($query['userData']),
                        'hotels' => $this->getRandomHotel($query['userData']['provider']),
                    ]),
                    200
                );
            } else {
                return new \HttpDriverResponse(
                    json_encode([
                        'requestId' => $requestId,
                        'state' => 'queued_up',
                    ]),
                    200
                );
            }
        } elseif ($path === '/v1/providers/list') {
            return new \HttpDriverResponse(
                json_encode([
                    'providers' => [
                        [
                            'code' => 'goldpassport',
                            'displayName' => 'Hyatt (World of Hyatt)',
                            'shortName' => 'Hyatt',
                        ],
                        [
                            'code' => 'marriott',
                            'displayName' => 'Marriott Bonvoy',
                            'shortName' => 'Marriott',
                        ],
                        [
                            'code' => 'ichotelsgroup',
                            'displayName' => 'IHG Hotels & Resorts (One Rewards)',
                            'shortName' => 'IHG',
                        ],
                        [
                            'code' => 'hhonors',
                            'displayName' => 'Hilton (Honors)',
                            'shortName' => 'Hilton',
                        ],
                    ],
                ]),
                200
            );
        }

        return parent::call($method, $path, $data);
    }

    private function saveInCache(string $requestId, array $data): void
    {
        $this->memcached->set(
            sprintf('test_hotel_search_%s', $requestId),
            $data,
            60 * 60
        );
    }

    private function getFromCache(string $requestId)
    {
        return $this->memcached->get(sprintf('test_hotel_search_%s', $requestId));
    }

    private function getRandomHotel(string $parser): array
    {
        $hotels = [
            'goldpassport' => [
                [
                    'name' => 'GoldPassport City Resort',
                    'checkInDate' => date('Y-m-d', strtotime('+1 day')),
                    'checkOutDate' => date('Y-m-d', strtotime('+2 days')),
                    'roomType' => 'Deluxe Room',
                    'hotelDescription' => 'Luxurious resort with ocean views and exceptional service.',
                    'numberOfNights' => 2,
                    'pointsPerNight' => 35000,
                    'cashPerNight' => 250.00,
                    'distance' => 1.2,
                    'rating' => 4.8,
                    'numberOfReviews' => 3210,
                    'phone' => '+1 312-321-3211',
                    'hotelURL' => 'https://www.example.com/resort-city',
                    'address' => [
                        'text' => '123 Coastal Avenue, Malibu, California, 90265, USA',
                        'addressLine1' => '123 Coastal Avenue',
                        'city' => 'Malibu',
                        'stateName' => 'California',
                        'countryName' => 'USA',
                        'postalCode' => '90265',
                        'lat' => 34.025922,
                        'lng' => -118.779757,
                    ],
                ],
                [
                    'name' => 'GoldPassport Urban Hotel',
                    'checkInDate' => date('Y-m-d', strtotime('+3 days')),
                    'checkOutDate' => date('Y-m-d', strtotime('+4 days')),
                    'roomType' => 'Executive Suite',
                    'hotelDescription' => 'High-rise urban hotel with modern amenities and a rooftop bar.',
                    'numberOfNights' => 1,
                    'pointsPerNight' => 45000,
                    'cashPerNight' => 300.00,
                    'distance' => 0.3,
                    'rating' => 4.9,
                    'numberOfReviews' => 5287,
                    'phone' => '+1 213-213-2132',
                    'hotelURL' => 'https://www.example.com/urban-hotel',
                    'address' => [
                        'text' => '789 Downtown Blvd, Seattle, Washington, 98101, USA',
                        'addressLine1' => '789 Downtown Blvd',
                        'city' => 'Seattle',
                        'stateName' => 'Washington',
                        'countryName' => 'USA',
                        'postalCode' => '98101',
                        'lat' => 47.609722,
                        'lng' => -122.333056,
                    ],
                ],
                [
                    'name' => 'GoldPassport Mountain Lodge',
                    'checkInDate' => date('Y-m-d', strtotime('+5 days')),
                    'checkOutDate' => date('Y-m-d', strtotime('+10 days')),
                    'roomType' => 'Standard Room',
                    'hotelDescription' => 'Cozy lodge in the mountains with stunning views and nature trails.',
                    'numberOfNights' => 5,
                    'pointsPerNight' => 22000,
                    'cashPerNight' => 150.00,
                    'distance' => 2.5,
                    'rating' => 4.6,
                    'numberOfReviews' => 1945,
                    'phone' => '+1 406-406-4064',
                    'hotelURL' => 'https://www.example.com/mountain-lodge',
                    'address' => [
                        'text' => '456 Mountain Rd, Boulder, Colorado, 80302, USA',
                        'addressLine1' => '456 Mountain Rd',
                        'city' => 'Boulder',
                        'stateName' => 'Colorado',
                        'countryName' => 'USA',
                        'postalCode' => '80302',
                        'lat' => 40.0150,
                        'lng' => -105.2705,
                    ],
                ],
                [
                    'name' => 'Courtyard by Marriott Los Angeles L.A. LIVE',
                    'checkInDate' => date('Y-m-d', strtotime('+2 days')),
                    'checkOutDate' => date('Y-m-d', strtotime('+3 days')),
                    'roomType' => 'Deluxe Room',
                    'hotelDescription' => 'Contemporary hotel with modern amenities located in the heart of downtown Los Angeles.',
                    'numberOfNights' => 2,
                    'pointsPerNight' => 32000,
                    'cashPerNight' => 213.50,
                    'distance' => 1.2,
                    'rating' => 4.3,
                    'numberOfReviews' => 3675,
                    'phone' => '+1 213-443-9200',
                    'hotelURL' => 'https://www.marriott.com/hotels/travel/laxld-courtyard-los-angeles-la-live/',
                    'address' => [
                        'text' => '901 West Olympic Boulevard, Los Angeles, California, 90015, USA',
                        'addressLine1' => '901 West Olympic Boulevard',
                        'city' => 'Los Angeles',
                        'stateName' => 'California',
                        'countryName' => 'USA',
                        'postalCode' => '90015',
                        'lat' => 34.044677,
                        'lng' => -118.267314,
                    ],
                ],
                [
                    'name' => 'The Ritz-Carlton, Chicago',
                    'checkInDate' => date('Y-m-d', strtotime('+3 days')),
                    'checkOutDate' => date('Y-m-d', strtotime('+4 days')),
                    'roomType' => 'Executive Suite',
                    'hotelDescription' => 'Luxury hotel with stunning views of Lake Michigan and the Magnificent Mile.',
                    'numberOfNights' => 3,
                    'pointsPerNight' => 45000,
                    'cashPerNight' => 400.00,
                    'distance' => 1.8,
                    'rating' => 4.7,
                    'numberOfReviews' => 5250,
                    'phone' => '+1 312-266-1000',
                    'hotelURL' => 'https://www.ritzcarlton.com/en/hotels/chicago',
                    'address' => [
                        'text' => '160 East Pearson Street, Chicago, Illinois, 60611, USA',
                        'addressLine1' => '160 East Pearson Street',
                        'city' => 'Chicago',
                        'stateName' => 'Illinois',
                        'countryName' => 'USA',
                        'postalCode' => '60611',
                        'lat' => 41.897043,
                        'lng' => -87.623738,
                    ],
                ],
            ],
            'hhonors' => [
                [
                    'name' => 'Hilton Garden Inn Times Square',
                    'checkInDate' => date('Y-m-d', strtotime('+1 day')),
                    'checkOutDate' => date('Y-m-d', strtotime('+2 days')),
                    'roomType' => 'Standard Room',
                    'hotelDescription' => 'Centrally located in New York, close to Times Square, with modern amenities and comfortable rooms.',
                    'numberOfNights' => 1,
                    'pointsPerNight' => 30000,
                    'cashPerNight' => 150.00,
                    'distance' => 0.2,
                    'rating' => 4.7,
                    'numberOfReviews' => 3200,
                    'phone' => '+1 212-840-9600',
                    'hotelURL' => 'https://www.hilton.com/en/hotels/nycmdgi-hilton-garden-inn-new-york-times-square-central/',
                    'address' => [
                        'text' => '790 Eighth Ave, New York, NY 10019, USA',
                        'addressLine1' => '790 Eighth Ave',
                        'city' => 'New York',
                        'stateName' => 'NY',
                        'countryName' => 'USA',
                        'postalCode' => '10019',
                        'lat' => 40.759529,
                        'lng' => -73.984909,
                    ],
                ],
                [
                    'name' => 'Conrad Miami',
                    'checkInDate' => date('Y-m-d', strtotime('+3 days')),
                    'checkOutDate' => date('Y-m-d', strtotime('+6 days')),
                    'roomType' => 'Deluxe Room',
                    'hotelDescription' => 'Luxury hotel in Miami’s financial district, offering panoramic views of Biscayne Bay.',
                    'numberOfNights' => 3,
                    'pointsPerNight' => 45000,
                    'cashPerNight' => 250.00,
                    'distance' => 1.0,
                    'rating' => 4.6,
                    'numberOfReviews' => 2850,
                    'phone' => '+1 305-503-6500',
                    'hotelURL' => 'https://www.hilton.com/en/hotels/miacici-conrad-miami/',
                    'address' => [
                        'text' => '1395 Brickell Ave, Miami, FL 33131, USA',
                        'addressLine1' => '1395 Brickell Ave',
                        'city' => 'Miami',
                        'stateName' => 'FL',
                        'countryName' => 'USA',
                        'postalCode' => '33131',
                        'lat' => 25.760178,
                        'lng' => -80.193620,
                    ],
                ],
                [
                    'name' => 'The Waldorf Astoria Beverly Hills',
                    'checkInDate' => date('Y-m-d', strtotime('+5 days')),
                    'checkOutDate' => date('Y-m-d', strtotime('+10 days')),
                    'roomType' => 'Suite',
                    'hotelDescription' => 'Iconic Beverly Hills luxury property, featuring top-tier amenities and exquisite room service.',
                    'numberOfNights' => 5,
                    'pointsPerNight' => 55000,
                    'cashPerNight' => 500.00,
                    'distance' => 0.3,
                    'rating' => 4.8,
                    'numberOfReviews' => 1500,
                    'phone' => '+1 310-860-6666',
                    'hotelURL' => 'https://www.hilton.com/en/hotels/laxwawa-waldorf-astoria-beverly-hills/',
                    'address' => [
                        'text' => '9850 Wilshire Blvd, Beverly Hills, CA 90210, USA',
                        'addressLine1' => '9850 Wilshire Blvd',
                        'city' => 'Beverly Hills',
                        'stateName' => 'CA',
                        'countryName' => 'USA',
                        'postalCode' => '90210',
                        'lat' => 34.067460,
                        'lng' => -118.401950,
                    ],
                ],
                [
                    'name' => 'Embassy Suites by Hilton Portland Downtown',
                    'checkInDate' => date('Y-m-d', strtotime('+2 days')),
                    'checkOutDate' => date('Y-m-d', strtotime('+4 days')),
                    'roomType' => 'Suite',
                    'hotelDescription' => 'All-suite hotel in downtown Portland with complimentary breakfast and evening reception.',
                    'numberOfNights' => 2,
                    'pointsPerNight' => 35000,
                    'cashPerNight' => 180.00,
                    'distance' => 0.6,
                    'rating' => 4.6,
                    'numberOfReviews' => 4200,
                    'phone' => '+1 503-279-9000',
                    'hotelURL' => 'https://www.hilton.com/en/hotels/pdxpdes-embassy-suites-portland-downtown/',
                    'address' => [
                        'text' => '319 SW Pine St, Portland, OR 97204, USA',
                        'addressLine1' => '319 SW Pine St',
                        'city' => 'Portland',
                        'stateName' => 'Oregon',
                        'countryName' => 'USA',
                        'postalCode' => '97204',
                        'lat' => 45.521457,
                        'lng' => -122.675298,
                    ],
                ],
                [
                    'name' => 'Hilton Orlando Buena Vista Palace',
                    'checkInDate' => date('Y-m-d', strtotime('+3 days')),
                    'checkOutDate' => date('Y-m-d', strtotime('+5 days')),
                    'roomType' => 'Deluxe Room',
                    'hotelDescription' => 'Resort hotel near Disney Springs with multiple pools, restaurants, and spacious rooms.',
                    'numberOfNights' => 3,
                    'pointsPerNight' => 40000,
                    'cashPerNight' => 200.00,
                    'distance' => 1.2,
                    'rating' => 4.7,
                    'numberOfReviews' => 5890,
                    'phone' => '+1 407-827-2727',
                    'hotelURL' => 'https://www.hilton.com/en/hotels/mcobses-hilton-orlando-buena-vista-palace/',
                    'address' => [
                        'text' => '1900 E Buena Vista Dr, Lake Buena Vista, FL 32830, USA',
                        'addressLine1' => '1900 E Buena Vista Dr',
                        'city' => 'Lake Buena Vista',
                        'stateName' => 'Florida',
                        'countryName' => 'USA',
                        'postalCode' => '32830',
                        'lat' => 28.373355,
                        'lng' => -81.516456,
                    ],
                ],
                [
                    'name' => 'DoubleTree by Hilton Hotel New York City - Times Square South',
                    'checkInDate' => date('Y-m-d', strtotime('+4 days')),
                    'checkOutDate' => date('Y-m-d', strtotime('+5 days')),
                    'roomType' => 'King Room',
                    'hotelDescription' => 'Modern hotel near Times Square with comfortable rooms and rooftop bar.',
                    'numberOfNights' => 1,
                    'pointsPerNight' => 32000,
                    'cashPerNight' => 170.00,
                    'distance' => 0.5,
                    'rating' => 4.4,
                    'numberOfReviews' => 4780,
                    'phone' => '+1 212-607-8888',
                    'hotelURL' => 'https://www.hilton.com/en/hotels/nycdtdt-doubletree-times-square-south/',
                    'address' => [
                        'text' => '341 West 36th Street, New York, NY 10018, USA',
                        'addressLine1' => '341 West 36th Street',
                        'city' => 'New York',
                        'stateName' => 'New York',
                        'countryName' => 'USA',
                        'postalCode' => '10018',
                        'lat' => 40.753727,
                        'lng' => -73.992534,
                    ],
                ],
                [
                    'name' => 'Hampton Inn & Suites Miami Midtown',
                    'checkInDate' => date('Y-m-d', strtotime('+5 days')),
                    'checkOutDate' => date('Y-m-d', strtotime('+7 days')),
                    'roomType' => 'Standard Room',
                    'hotelDescription' => 'Conveniently located hotel in Miami with complimentary breakfast and outdoor pool.',
                    'numberOfNights' => 2,
                    'pointsPerNight' => 28000,
                    'cashPerNight' => 130.00,
                    'distance' => 0.8,
                    'rating' => 4.2,
                    'numberOfReviews' => 3200,
                    'phone' => '+1 305-571-6100',
                    'hotelURL' => 'https://www.hilton.com/en/hotels/miamicv-hampton-inn-miami-midtown/',
                    'address' => [
                        'text' => '3450 Biscayne Blvd, Miami, FL 33137, USA',
                        'addressLine1' => '3450 Biscayne Blvd',
                        'city' => 'Miami',
                        'stateName' => 'Florida',
                        'countryName' => 'USA',
                        'postalCode' => '33137',
                        'lat' => 25.811371,
                        'lng' => -80.189241,
                    ],
                ],
            ],
            'ichotelsgroup' => [
                [
                    'name' => 'InterContinental New York Times Square',
                    'checkInDate' => date('Y-m-d', strtotime('+3 days')),
                    'checkOutDate' => date('Y-m-d', strtotime('+6 days')),
                    'roomType' => 'Deluxe Room',
                    'hotelDescription' => 'Luxury hotel located in the heart of Times Square, offering stunning city views and upscale amenities.',
                    'numberOfNights' => 3,
                    'pointsPerNight' => 45000,
                    'cashPerNight' => 350.00,
                    'distance' => 0.1,
                    'rating' => 4.8,
                    'numberOfReviews' => 8921,
                    'phone' => '+1 212-803-4500',
                    'hotelURL' => 'https://www.ihg.com/intercontinental/hotels/us/en/new-york/nychc/hoteldetail',
                    'address' => [
                        'text' => '300 West 44th Street, New York, New York, 10036, USA',
                        'addressLine1' => '300 West 44th Street',
                        'city' => 'New York',
                        'stateName' => 'New York',
                        'countryName' => 'USA',
                        'postalCode' => '10036',
                        'lat' => 40.758896,
                        'lng' => -73.985130,
                    ],
                ],
                [
                    'name' => 'Crowne Plaza London - Kings Cross',
                    'checkInDate' => date('Y-m-d', strtotime('+1 day')),
                    'checkOutDate' => date('Y-m-d', strtotime('+2 days')),
                    'roomType' => 'Executive Room',
                    'hotelDescription' => 'Modern hotel with convenient access to major London attractions and business districts, including a spa and two restaurants.',
                    'numberOfNights' => 1,
                    'pointsPerNight' => 35000,
                    'cashPerNight' => 200.00,
                    'distance' => 1.0,
                    'rating' => 4.3,
                    'numberOfReviews' => 3100,
                    'phone' => '+44 20 7833 3900',
                    'hotelURL' => 'https://www.ihg.com/crowneplaza/hotels/us/en/london/lonlx/hoteldetail',
                    'address' => [
                        'text' => '1 Kings Cross Road, London, WC1X 9HX, United Kingdom',
                        'addressLine1' => '1 Kings Cross Road',
                        'city' => 'London',
                        'stateName' => 'London',
                        'countryName' => 'United Kingdom',
                        'postalCode' => 'WC1X 9HX',
                        'lat' => 51.528308,
                        'lng' => -0.125956,
                    ],
                ],
                [
                    'name' => 'Holiday Inn Express Berlin City Centre',
                    'checkInDate' => date('Y-m-d', strtotime('+4 days')),
                    'checkOutDate' => date('Y-m-d', strtotime('+9 days')),
                    'roomType' => 'Standard Room',
                    'hotelDescription' => 'Comfortable and affordable hotel in the heart of Berlin, close to major tourist attractions and business areas.',
                    'numberOfNights' => 5,
                    'pointsPerNight' => 15000,
                    'cashPerNight' => 100.00,
                    'distance' => 0.3,
                    'rating' => 4.1,
                    'numberOfReviews' => 4500,
                    'phone' => '+49 30 200520',
                    'hotelURL' => 'https://www.ihg.com/holidayinnexpress/hotels/us/en/berlin/berhc/hoteldetail',
                    'address' => [
                        'text' => 'Stresemannstr 49, Berlin, 10963, Germany',
                        'addressLine1' => 'Stresemannstr 49',
                        'city' => 'Berlin',
                        'stateName' => 'Berlin',
                        'countryName' => 'Germany',
                        'postalCode' => '10963',
                        'lat' => 52.501521,
                        'lng' => 13.391276,
                    ],
                ],
                [
                    'name' => 'Fairfield Inn & Suites Atlanta Downtown',
                    'checkInDate' => date('Y-m-d', strtotime('+1 day')),
                    'checkOutDate' => date('Y-m-d', strtotime('+2 days')),
                    'roomType' => 'Standard Room',
                    'hotelDescription' => 'Newly renovated historic downtown property with spacious suites & fully equipped kitchens.',
                    'numberOfNights' => 1,
                    'pointsPerNight' => mt_rand(20000, 30000),
                    'cashPerNight' => 127.00,
                    'distance' => 0.5,
                    'rating' => 4.5,
                    'numberOfReviews' => 4890,
                    'phone' => '+1 404-524-5555',
                    'hotelURL' => 'https://www.marriott.com/hotels/travel/atldt-fairfield-inn-and-suites-atlanta-downtown/',
                    'address' => [
                        'text' => '136 West 42nd Street, New York, New York, 10036, USA',
                        'addressLine1' => '136 West 42nd Street',
                        'city' => 'New York',
                        'stateName' => 'New York',
                        'countryName' => 'USA',
                        'postalCode' => '10036',
                        'lat' => 40.7551598381,
                        'lng' => -73.985726818,
                    ],
                ],
                [
                    'name' => 'Holiday Inn Express & Suites Boston',
                    'checkInDate' => date('Y-m-d', strtotime('+2 days')),
                    'checkOutDate' => date('Y-m-d', strtotime('+3 days')),
                    'roomType' => 'Deluxe Suite',
                    'hotelDescription' => 'Contemporary hotel offering bright rooms & a fitness center, plus free breakfast & WiFi.',
                    'numberOfNights' => 3,
                    'pointsPerNight' => mt_rand(18000, 28000),
                    'cashPerNight' => 155.00,
                    'distance' => 1.2,
                    'rating' => 4.3,
                    'numberOfReviews' => 3200,
                    'phone' => '+1 617-973-7300',
                    'hotelURL' => 'https://www.ihg.com/holidayinnexpress/hotels/us/en/boston/bosbs/hoteldetail',
                    'address' => [
                        'text' => '69R Boston Street, Boston, Massachusetts, 02125, USA',
                        'addressLine1' => '69R Boston Street',
                        'city' => 'Boston',
                        'stateName' => 'Massachusetts',
                        'countryName' => 'USA',
                        'postalCode' => '02125',
                        'lat' => 42.320848,
                        'lng' => -71.062828,
                    ],
                ],
                [
                    'name' => 'Crowne Plaza Times Square Manhattan',
                    'checkInDate' => date('Y-m-d', strtotime('+3 days')),
                    'checkOutDate' => date('Y-m-d', strtotime('+4 days')),
                    'roomType' => 'Executive Room',
                    'hotelDescription' => 'Stylish hotel featuring refined rooms, plus an upscale restaurant & a fitness center with city views.',
                    'numberOfNights' => 5,
                    'pointsPerNight' => mt_rand(25000, 35000),
                    'cashPerNight' => 225.00,
                    'distance' => 0.3,
                    'rating' => 4.6,
                    'numberOfReviews' => 5600,
                    'phone' => '+1 212-977-4000',
                    'hotelURL' => 'https://www.ihg.com/crowneplaza/hotels/us/en/new-york/nycsa/hoteldetail',
                    'address' => [
                        'text' => '1605 Broadway, New York, New York, 10019, USA',
                        'addressLine1' => '1605 Broadway',
                        'city' => 'New York',
                        'stateName' => 'New York',
                        'countryName' => 'USA',
                        'postalCode' => '10019',
                        'lat' => 40.7617169,
                        'lng' => -73.9852146,
                    ],
                ],
            ],
            'marriott' => [
                [
                    'name' => 'JW Marriott Essex House New York',
                    'checkInDate' => date('Y-m-d', strtotime('+3 days')),
                    'checkOutDate' => date('Y-m-d', strtotime('+6 days')),
                    'roomType' => 'Deluxe Room',
                    'hotelDescription' => 'An elegant stay with stunning Central Park views, located in the heart of NYC.',
                    'numberOfNights' => 3,
                    'pointsPerNight' => 40000,
                    'cashPerNight' => 350.00,
                    'distance' => 0.3,
                    'rating' => 4.8,
                    'numberOfReviews' => 3200,
                    'phone' => '+1 212-247-0300',
                    'hotelURL' => 'https://www.marriott.com/hotels/travel/nycex-jw-marriott-essex-house-new-york/',
                    'address' => [
                        'text' => '160 Central Park South, New York, NY 10019, USA',
                        'addressLine1' => '160 Central Park South',
                        'city' => 'New York',
                        'stateName' => 'New York',
                        'countryName' => 'USA',
                        'postalCode' => '10019',
                        'lat' => 40.766411,
                        'lng' => -73.977999,
                    ],
                ],
                [
                    'name' => 'Marriott Marquis San Diego Marina',
                    'checkInDate' => date('Y-m-d', strtotime('+2 days')),
                    'checkOutDate' => date('Y-m-d', strtotime('+5 days')),
                    'roomType' => 'Executive Suite',
                    'hotelDescription' => 'Waterfront luxury with exceptional service, steps from the Gaslamp Quarter.',
                    'numberOfNights' => 3,
                    'pointsPerNight' => 35000,
                    'cashPerNight' => 300.00,
                    'distance' => 0.2,
                    'rating' => 4.6,
                    'numberOfReviews' => 2550,
                    'phone' => '+1 619-234-1500',
                    'hotelURL' => 'https://www.marriott.com/hotels/travel/sandt-marriott-marquis-san-diego-marina/',
                    'address' => [
                        'text' => '333 W Harbor Dr, San Diego, CA 92101, USA',
                        'addressLine1' => '333 W Harbor Dr',
                        'city' => 'San Diego',
                        'stateName' => 'California',
                        'countryName' => 'USA',
                        'postalCode' => '92101',
                        'lat' => 32.709999,
                        'lng' => -117.163841,
                    ],
                ],
                [
                    'name' => 'The St. Regis Chicago',
                    'checkInDate' => date('Y-m-d', strtotime('+1 day')),
                    'checkOutDate' => date('Y-m-d', strtotime('+3 days')),
                    'roomType' => 'Premier Room',
                    'hotelDescription' => 'Luxurious rooms and unmatched service, with spectacular views of Lake Michigan.',
                    'numberOfNights' => 2,
                    'pointsPerNight' => 45000,
                    'cashPerNight' => 380.00,
                    'distance' => 0.4,
                    'rating' => 4.9,
                    'numberOfReviews' => 1500,
                    'phone' => '+1 312-856-1000',
                    'hotelURL' => 'https://www.marriott.com/hotels/travel/chisr-the-st-regis-chicago/',
                    'address' => [
                        'text' => '363 E Wacker Dr, Chicago, IL 60601, USA',
                        'addressLine1' => '363 E Wacker Dr',
                        'city' => 'Chicago',
                        'stateName' => 'Illinois',
                        'countryName' => 'USA',
                        'postalCode' => '60601',
                        'lat' => 41.888946,
                        'lng' => -87.623934,
                    ],
                ],
                [
                    'name' => 'Courtyard by Marriott San Francisco Downtown',
                    'checkInDate' => date('Y-m-d', strtotime('+2 days')),
                    'checkOutDate' => date('Y-m-d', strtotime('+4 days')),
                    'roomType' => 'Deluxe Room',
                    'hotelDescription' => 'Contemporary hotel in downtown San Francisco with modern amenities and scenic views.',
                    'numberOfNights' => 3,
                    'pointsPerNight' => 30000,
                    'cashPerNight' => 150.00,
                    'distance' => 1.2,
                    'rating' => 4.3,
                    'numberOfReviews' => 3520,
                    'phone' => '+1 415-947-0700',
                    'hotelURL' => 'https://www.marriott.com/hotels/travel/sfodt-courtyard-san-francisco-downtown/',
                    'address' => [
                        'text' => '299 2nd Street, San Francisco, California, 94105, USA',
                        'addressLine1' => '299 2nd Street',
                        'city' => 'San Francisco',
                        'stateName' => 'California',
                        'countryName' => 'USA',
                        'postalCode' => '94105',
                        'lat' => 37.785136,
                        'lng' => -122.396116,
                    ],
                ],
                [
                    'name' => 'JW Marriott Essex House New York',
                    'checkInDate' => date('Y-m-d', strtotime('+3 days')),
                    'checkOutDate' => date('Y-m-d', strtotime('+5 days')),
                    'roomType' => 'Executive Suite',
                    'hotelDescription' => 'Luxury hotel overlooking Central Park, featuring elegant rooms and exceptional dining options.',
                    'numberOfNights' => 5,
                    'pointsPerNight' => 40000,
                    'cashPerNight' => 300.00,
                    'distance' => 0.8,
                    'rating' => 4.7,
                    'numberOfReviews' => 6280,
                    'phone' => '+1 212-247-0300',
                    'hotelURL' => 'https://www.marriott.com/hotels/travel/nycex-jw-marriott-essex-house-new-york/',
                    'address' => [
                        'text' => '160 Central Park South, New York, New York, 10019, USA',
                        'addressLine1' => '160 Central Park South',
                        'city' => 'New York',
                        'stateName' => 'New York',
                        'countryName' => 'USA',
                        'postalCode' => '10019',
                        'lat' => 40.7656,
                        'lng' => -73.9753,
                    ],
                ],
            ],
        ];

        if (!isset($hotels[$parser])) {
            $parser = array_rand($hotels);
        }

        return array_slice($hotels[$parser], 0, mt_rand(1, count($hotels[$parser])));
    }
}
