<?php

namespace AwardWallet\Tests\FunctionalSymfony\MobileBundle\Controller;

use AwardWallet\MainBundle\Globals\ApiVersioning\MobileVersions;
use AwardWallet\MainBundle\Security\Authenticator\Step\Recaptcha\CaptchaStepHelper;
use AwardWallet\Tests\FunctionalSymfony\_steps\Mobile\UserSteps;
use AwardWallet\Tests\FunctionalSymfony\BaseTraitCest;
use AwardWallet\Tests\FunctionalSymfony\Security\EmailOtcCest;
use AwardWallet\Tests\FunctionalSymfony\Traits\FreeUser;
use AwardWallet\Tests\FunctionalSymfony\Traits\JsonHeaders;
use Codeception\Module\Aw;
use Google\Authenticator\GoogleAuthenticator;

/**
 * @group frontend-functional
 * @group mobile
 */
class UserControllerCest extends BaseTraitCest
{
    use \Awardwallet\Tests\Modules\AutoVerifyMocksTrait;
    use FreeUser;
    use JsonHeaders;

    /**
     * @var UserSteps
     */
    protected $userSteps;
    /**
     * @var GoogleAuthenticator
     */
    protected $googleAuthenticator;

    public function _before(\TestSymfonyGuy $I)
    {
        parent::_before($I);
        $scenario = $I->grabScenarioFrom($I);
        $this->userSteps = new UserSteps($scenario);
        $this->googleAuthenticator = new GoogleAuthenticator();
        $I->setMobileVersion('4.0.0');
        $I->sendGET('/m/api/login_status');
        $I->saveCsrfToken();
    }

    public function otcFromAppForVersion4_0_0(\TestSymfonyGuy $I)
    {
        $this->userSteps->createTwoFactorAuthCode($this->user->getUserid());
        $I->sendPOST('/m/api/login_check', [
            'login_password' => [
                'login' => $this->user->getLogin(),
                'pass' => Aw::DEFAULT_PASSWORD,
            ],
        ]);
        $I->seeResponseCodeIs(200);
        $I->seeResponseContainsJson([
            'success' => false,
            'one_time_code_by_app' => [
                'notice' => 'One-time code required',
                'label' => 'One-time code',
                'hint' => '(this is a 6-digit code generated by Google Authenticator or equivalent program)',
            ],
        ]);
    }

    public function otcFromEmailForVersion4_0_0(\TestSymfonyGuy $I)
    {
        $I->updateInDatabase('Usr', [
            'RegistrationIP' => EmailOtcCest::FAR_IP,
            'LastLogonIP' => EmailOtcCest::FAR_IP_2,
        ], ['UserID' => $this->user->getUserid()]);
        $I->setCookie("EnableEmailOtcCheck", "1");
        $I->sendPOST('/m/api/login_check', [
            'login_password' => [
                'login' => $this->user->getLogin(),
                'pass' => Aw::DEFAULT_PASSWORD,
            ],
        ]);
        $I->seeResponseCodeIs(200);
        $I->seeResponseContainsJson([
            'success' => false,
            'one_time_code_by_email' => [
                'notice' => 'One time access code from email',
                'hint' => 'We\'ve noticed that you are logging in from a new location, in order to protect your account we\'ve sent an email to the address you have with us on file. Please check your email and enter the one time access code from that email into the field below',
            ],
        ]);
    }

    public function recaptchaError(\TestSymfonyGuy $I)
    {
        $I->setMobileVersion('4.41.23', MobileVersions::ANDROID);
        $I->setHeader(CaptchaStepHelper::WANT_RECAPTCHA_HEADER, 'anystring');
        $I->sendPOST('/m/api/login_check', [
            'login_password' => [
                'login' => $this->user->getLogin(),
                'pass' => Aw::DEFAULT_PASSWORD,
            ],
        ]);
        $I->seeResponseContainsJson(['recaptcha' => [
            'required' => true,
            'vendor' => 'google_recaptcha',
        ]]);
    }
}
