# @no-redirect
GET {{scheme}}{{host}}/m/api/data/?{{xdebugParamName}}={{xdebugParamValue}}
Content-Type: application/json
X-Aw-Version: {{clientVersion}}
X-Aw-Platform: {{clientPlatform}}
X-Symfony-Env: {{symfonyEnv}}
Authorization: Basic {{basicAuthLogin}} {{basicAuthPassword}}
