<?php

namespace AwardWallet\MainBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130911033600 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql("
			CREATE TABLE AbBookerInfo (
				AbBookerInfoID INT NOT NULL AUTO_INCREMENT,
				UserID INT NOT NULL,
				Price NUMERIC(10, 2) NOT NULL,
				PricingDetails TEXT DEFAULT NULL,
				ServiceName VARCHAR(120) NOT NULL,
				ServiceShortName VARCHAR(100) NOT NULL,
				Address VARCHAR(255) NOT NULL,
				ServiceURL VARCHAR(250) DEFAULT NULL,
				OutboundPercent NUMERIC(10, 2) NOT NULL,
				InboundPercent NUMERIC(10, 2) NOT NULL,
				SmtpServer VARCHAR(250) DEFAULT NULL,
				SmtpPort INT DEFAULT NULL,
				SmtpUseSsl TINYINT(4) DEFAULT NULL,
				SmtpUsername VARCHAR(250) DEFAULT NULL,
				SmtpPassword VARCHAR(250) DEFAULT NULL,
				SmtpError VARCHAR(250) DEFAULT NULL,
				SmtpErrorDate DATETIME DEFAULT NULL,
				Greeting TEXT NOT NULL,
				AutoReplyMessage TEXT NOT NULL,
				SiteAdID INT DEFAULT NULL,
				PRIMARY KEY (AbBookerInfoID),
				KEY fk1_user (UserID),
				KEY SiteAdIDKey (SiteAdID)
			) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

            CREATE TABLE AbAccountProgram (
            	AbAccountProgramID INT AUTO_INCREMENT NOT NULL,
            	RequestID INT NOT NULL,
            	AccountID INT NOT NULL,
            	SubAccountID INT DEFAULT NULL,
            	INDEX IDX_199DBEBB18FCD26A (RequestID),
            	INDEX IDX_199DBEBBDB411183 (AccountID),
            	UNIQUE INDEX RequestAccount (RequestID, AccountID, SubAccountID),
            	PRIMARY KEY(AbAccountProgramID)
            ) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
			CREATE TABLE AbCustomProgram (
				AbCustomProgramID INT AUTO_INCREMENT NOT NULL,
				Name VARCHAR(255) NOT NULL,
				Owner VARCHAR(255) DEFAULT NULL,
				EliteStatus VARCHAR(255) DEFAULT NULL,
				Balance NUMERIC(15, 2) NOT NULL DEFAULT 0,
				RequestID INT NOT NULL,
				INDEX IDX_E5A4981E18FCD26A (RequestID),
				PRIMARY KEY(AbCustomProgramID)
			) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
			CREATE TABLE AbInvoice (
				AbInvoiceID INT AUTO_INCREMENT NOT NULL,
				Tickets INT NOT NULL,
				Price NUMERIC(10, 2) NOT NULL,
				Discount INT DEFAULT NULL,
				Taxes NUMERIC(10, 2) DEFAULT NULL,
				Status INT NOT NULL,
				PaymentType TINYINT(1) NOT NULL,
				MessageID INT NOT NULL,
				INDEX IDX_7F9A558A1D5C02B1 (MessageID),
				PRIMARY KEY(AbInvoiceID)
			) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
			CREATE TABLE AbInvoiceMiles (
				AbInvoiceMilesID INT AUTO_INCREMENT NOT NULL,
				CustomName VARCHAR(255) NOT NULL,
				Balance NUMERIC(10, 0) NOT NULL,
				InvoiceID INT NOT NULL,
				INDEX IDX_EF8251F084E47E3A (InvoiceID),
				PRIMARY KEY(AbInvoiceMilesID)
			) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
			CREATE TABLE AbMessage (
				AbMessageID BIGINT(15) AUTO_INCREMENT NOT NULL,
				CreateDate DATETIME NOT NULL,
				Post LONGTEXT DEFAULT NULL,
				Internal INT NOT NULL,
				Type INT DEFAULT NULL,
				Metadata VARCHAR(255) DEFAULT NULL,
				RequestID INT NOT NULL,
				UserID INT NOT NULL,
				INDEX IDX_594272B118FCD26A (RequestID),
				INDEX IDX_594272B158746832 (UserID),
				PRIMARY KEY(AbMessageID)
			) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
			CREATE TABLE AbPassenger (
				AbPassengerID INT AUTO_INCREMENT NOT NULL,
				FirstName VARCHAR(255) DEFAULT NULL,
				MiddleName VARCHAR(255) DEFAULT NULL,
				LastName VARCHAR(255) DEFAULT NULL,
				Birthday DATETIME DEFAULT NULL,
				Nationality VARCHAR(255) DEFAULT NULL,
				RequestID INT NOT NULL,
				INDEX IDX_F644DD5E18FCD26A (RequestID),
				PRIMARY KEY(AbPassengerID)
			) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
			CREATE TABLE AbRequest (
				AbRequestID INT AUTO_INCREMENT NOT NULL,
				ContactName VARCHAR(255) NOT NULL,
				ContactEmail VARCHAR(255) NOT NULL,
				ContactPhone VARCHAR(255) NOT NULL,
				Passengers INT NOT NULL,
				Status TINYINT(2) NOT NULL,
				Notes VARCHAR(4000) DEFAULT NULL,
				CreateDate DATETIME DEFAULT NULL,
				RemindDate DATETIME DEFAULT NULL,
				CabinFirst TINYINT(1) NOT NULL,
  				CabinBusiness TINYINT(1) NOT NULL,
  				PriorSearchResults VARCHAR(4000) DEFAULT NULL,
				FinalServiceFee NUMERIC(10, 2) DEFAULT NULL,
				FinalTaxes NUMERIC(10, 2) DEFAULT NULL,
				BookerUserID INT NOT NULL,
				AssignedUserID INT DEFAULT NULL,
				UserID INT NOT NULL,
				BookingTransactionID INT DEFAULT NULL,
				FeesPaidToUserID INT DEFAULT NULL,
				INDEX IDX_D468CD5190316B36 (BookerUserID),
				INDEX IDX_D468CD51DBA0CE34 (AssignedUserID),
				INDEX IDX_D468CD5158746832 (UserID),
				INDEX IDX_D468CD51E8DC8944 (BookingTransactionID),
				INDEX IDX_D468CD512BD53A6A (FeesPaidToUserID),
				PRIMARY KEY(AbRequestID)
			) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
			CREATE TABLE AbRequestRead (
				AbRequestReadID INT AUTO_INCREMENT NOT NULL,
				ReadDate DATETIME NOT NULL,
				UserID INT NOT NULL,
				RequestID INT NOT NULL,
				INDEX IDX_FE3974EF58746832 (UserID),
				INDEX IDX_FE3974EF18FCD26A (RequestID),
				UNIQUE INDEX RequestUser (RequestID, UserID),
				PRIMARY KEY(AbRequestReadID)
			) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
			CREATE TABLE AbSegment (
				AbSegmentID INT AUTO_INCREMENT NOT NULL,
				DepDateFrom DATETIME NOT NULL,
				DepDateTo DATETIME NOT NULL,
				DepDateIdeal DATETIME DEFAULT NULL,
				ArrDateFrom DATETIME NOT NULL,
				ArrDateTo DATETIME NOT NULL,
				ArrDateIdeal DATETIME DEFAULT NULL,
				Priority INT NOT NULL,
				RoundTrip INT NOT NULL,
				RequestID INT NOT NULL,
				Dep VARCHAR(250) NOT NULL,
				Arr VARCHAR(250) NOT NULL,
				INDEX IDX_F77EB7AB18FCD26A (RequestID),
				INDEX IDX_F77EB7AB29E8B855 (Dep),
				INDEX IDX_F77EB7AB829ED401 (Arr),
				PRIMARY KEY(AbSegmentID)
			) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
			CREATE TABLE AbTransaction (
				AbTransactionID INT AUTO_INCREMENT NOT NULL,
				ProcessDate DATETIME NOT NULL,
				Processed INT DEFAULT NULL,
				INDEX Processed (Processed),
				PRIMARY KEY(AbTransactionID)
			) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

			ALTER TABLE AbAccountProgram ADD CONSTRAINT FK_199DBEBB18FCD26A FOREIGN KEY (RequestID) REFERENCES AbRequest (AbRequestID) ON DELETE RESTRICT;
			ALTER TABLE AbAccountProgram ADD CONSTRAINT FK_199DBEBBDB411183 FOREIGN KEY (AccountID) REFERENCES Account (AccountID) ON DELETE RESTRICT;
			ALTER TABLE AbAccountProgram ADD CONSTRAINT FK_Subaccount FOREIGN KEY (SubAccountID) REFERENCES SubAccount (SubAccountID) ON DELETE RESTRICT;
			ALTER TABLE AbCustomProgram ADD CONSTRAINT FK_E5A4981E18FCD26A FOREIGN KEY (RequestID) REFERENCES AbRequest (AbRequestID) ON DELETE RESTRICT;
			ALTER TABLE AbInvoice ADD CONSTRAINT FK_7F9A558A1D5C02B1 FOREIGN KEY (MessageID) REFERENCES AbMessage (AbMessageID) ON DELETE RESTRICT;
			ALTER TABLE AbInvoiceMiles ADD CONSTRAINT FK_EF8251F084E47E3A FOREIGN KEY (InvoiceID) REFERENCES AbInvoice (AbInvoiceID);
			ALTER TABLE AbMessage ADD CONSTRAINT FK_594272B118FCD26A FOREIGN KEY (RequestID) REFERENCES AbRequest (AbRequestID) ON DELETE RESTRICT;
			ALTER TABLE AbMessage ADD CONSTRAINT FK_594272B158746832 FOREIGN KEY (UserID) REFERENCES Usr (UserID) ON DELETE RESTRICT;
			ALTER TABLE AbPassenger ADD CONSTRAINT FK_F644DD5E18FCD26A FOREIGN KEY (RequestID) REFERENCES AbRequest (AbRequestID) ON DELETE RESTRICT;
			ALTER TABLE AbRequest ADD CONSTRAINT FK_D468CD5190316B36 FOREIGN KEY (BookerUserID) REFERENCES Usr (UserID) ON DELETE RESTRICT;
			ALTER TABLE AbRequest ADD CONSTRAINT FK_D468CD51DBA0CE34 FOREIGN KEY (AssignedUserID) REFERENCES Usr (UserID) ON DELETE RESTRICT;
			ALTER TABLE AbRequest ADD CONSTRAINT FK_D468CD5158746832 FOREIGN KEY (UserID) REFERENCES Usr (UserID) ON DELETE RESTRICT;
			ALTER TABLE AbRequest ADD CONSTRAINT FK_D468CD51E8DC8944 FOREIGN KEY (BookingTransactionID) REFERENCES AbTransaction (AbTransactionID) ON DELETE RESTRICT;
			ALTER TABLE AbRequest ADD CONSTRAINT FK_D468CD512BD53A6A FOREIGN KEY (FeesPaidToUserID) REFERENCES Usr (UserID) ON DELETE RESTRICT;
			ALTER TABLE AbRequestRead ADD CONSTRAINT FK_FE3974EF58746832 FOREIGN KEY (UserID) REFERENCES Usr (UserID) ON DELETE RESTRICT;
			ALTER TABLE AbRequestRead ADD CONSTRAINT FK_FE3974EF18FCD26A FOREIGN KEY (RequestID) REFERENCES AbRequest (AbRequestID) ON DELETE RESTRICT;
			ALTER TABLE AbSegment ADD CONSTRAINT FK_F77EB7AB18FCD26A FOREIGN KEY (RequestID) REFERENCES AbRequest (AbRequestID) ON DELETE RESTRICT;
			ALTER TABLE AbBookerInfo ADD CONSTRAINT fk1_user FOREIGN KEY (UserID) REFERENCES Usr (UserID) ON DELETE RESTRICT;
        ");
    }

    public function down(Schema $schema): void
    {
        $this->addSql("
			DROP TABLE AbBookerInfo;
			DROP TABLE AbAccountProgram;
			DROP TABLE AbCustomProgram;
			DROP TABLE AbInvoiceMiles;
			DROP TABLE AbInvoice;
			DROP TABLE AbMessage;
			DROP TABLE AbPassenger;
			DROP TABLE AbRequestRead;
			DROP TABLE AbSegment;
			DROP TABLE AbRequest;
			DROP TABLE AbTransaction;
        ");
    }
}
