<?
global $Interface, $Connection, $CLOUD_CONFIG, $apacheHeaders;

if(!isset($apacheHeaders['Content-Only'])){
?>
</td></tr></table></div><!-- content -->

</td></tr>
<tr><td>

<? $bigFooter =  in_array($_SERVER['SCRIPT_NAME'], array('/trips/index.php', '/trips', '/trips/', '/trips/view.php'));?>

<div id="footer"<?= ($bigFooter ? ' style = "background-image: url(\'/images/bigFooter.png\');"  ' : '') ?>>
	<div class="footerYear">&copy; 2004 - <?=date("Y")?>  AwardWallet, LLC.</div>
	<div class="footerLinks">
        <a href="/privacy.php">Privacy Notice</a> |
        <a href="/terms.php">Terms of Use</a> |
        <a href="/about/">About Us</a> |
        <a href="/pr/">Media</a> |
        <a href="/services/">Services</a> |
        <? if(isset($_SESSION['UserID']) && SITE_MODE == SITE_MODE_PERSONAL) { ?>
            <a href="/rating/">Reviews</a> |
        <? } ?>
        <a href="/cards.php">Credit Card Offers</a> |
        <a href="/partners/">Partners</a> |
        <a href="/blog/">Blog</a>
        <?
		if($bigFooter)
			echo '<div><br />Maps generated by the <a target="_blank" href="http://www.gcmap.com/" rel="noopener noreferrer">Great Circle Mapper</a>&nbsp;copyright &#169; <a target="_blank" href="http://www.kls2.com/~karl/">Karl L. Swartz</a></div><br />';
		?>
		<!--</br><br/> Maps generated by the <a target="_blank" href="http://www.gcmap.com/">Great Circle Mapper</a>&nbsp;copyright &#169; <a target="_blank" href="http://www.kls2.com/~karl/">Karl L. Swartz</a> -->
	</div>
	<a href="http://itunes.apple.com/us/app/awardwallet/id388442727?mt=8" target="_blank" rel="noopener noreferrer"><div style="top: 15px; right: 10px; position:absolute;" class="footerMobileLogo"></div></a>
    <a href="https://market.android.com/details?id=com.itlogy.awardwallet&feature=search_result" target="_blank" rel="noopener noreferrer"><div style="top: 15px; right: 100px; position:absolute;" class="footerAndroidLogo"></div></a>
</div>
<div id="browserWarning" class="topWarning">
	<div class="warningIcon"></div>
	AwardWallet works in any modern browser, however you are using an old browser,
	we strongly recommend that you either switch to a <a href="http://www.microsoft.com/windows/internet-explorer/worldwide-sites.aspx" target="_blank" rel="noopener noreferrer">newer version</a> of your browser of choice or use <a href="http://www.getfirefox.net/" target="_blank" rel="noopener noreferrer">FireFox</a> or <a href="http://www.google.com/chrome" target="_blank" rel="noopener noreferrer">Google Chrome</a>.
</div>

</td></tr>
</tbody>
</table>

<?
$Interface->FooterScripts[] = "checkBrowser();";
require "footerCommon.php";
if(isset($Connection) && $Connection->Tracing && isset($_GET['SQLTrace']))
	$Connection->ShowTraceData();

if(!isset($_COOKIE['DisableFB']) && !$Interface->NoExternals){
?>
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({appId: '75330755697', status: true, cookie: true,
             xfbml: true});
  };
  (function() {
  	if (typeof($.browser) != "undefined" && $.browser.msie && $.browser.version == '6.0')
  		return;
    var e = document.createElement('script'); e.async = true;
    e.src = document.location.protocol +
      '//connect.facebook.net/en_US/all.js';
    document.getElementById('fb-root').appendChild(e);
  }());
</script>
<? } ?>
</body>
</html>
<?

}
?>
