# @no-redirect
POST {{scheme}}{{host}}/m/api/account/spent-analysis/merchants/data?{{xdebugParamName}}={{xdebugParamValue}}
Content-Type: application/json
X-Aw-Version: {{clientVersion}}
X-Aw-Platform: {{clientPlatform}}
X-Symfony-Env: {{symfonyEnv}}
Authorization: Basic {{basicAuthLogin}} {{basicAuthPassword}}
X-XSRF-TOKEN: {{csrfToken}}

> ../../scripts/csrfToken.js