<?php

namespace AwardWallet\Tests\Unit\BusinessTransaction;

use AwardWallet\MainBundle\Entity\BusinessInfo;
use AwardWallet\MainBundle\Entity\BusinessTransaction;
use AwardWallet\MainBundle\Entity\Useragent;
use AwardWallet\MainBundle\Service\BusinessTransaction\BusinessTransactionManager;
use AwardWallet\Tests\Unit\BaseUserTest;

class AbstractTest extends BaseUserTest
{
    /** @var \AwardWallet\MainBundle\Entity\Usr */
    protected $business;

    /**
     * @var BusinessInfo
     */
    protected $info;

    /** @var Useragent */
    protected $familyMember;

    /** @var \AwardWallet\MainBundle\Service\BusinessTransaction\BusinessTransactionManager */
    protected $manager;

    public function _before()
    {
        parent::_before();

        $userRep = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Usr::class);
        $uaRep = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Useragent::class);
        $userId = $this->aw->createBusinessUserWithBookerInfo('testbus' . $this->aw->grabRandomString(5), [
            'Company' => 'TestBooker',
        ]);
        $this->business = $userRep->find($userId);
        $this->business->getBusinessInfo()->setBalance(0)->setDiscount(0);
        $this->em->flush();
        $this->db->seeInDatabase("BusinessInfo", ["UserID" => $userId]);
        $this->assertInstanceOf(BusinessInfo::class, $this->business->getBusinessInfo());
        $this->info = $this->business->getBusinessInfo();
        // add family member
        $this->familyMember = $uaRep->find($this->aw->createFamilyMember(
            $this->business->getUserid(), 'Test', 'Testov')
        );

        $this->manager = $this->container->get(BusinessTransactionManager::class);
    }

    public function _after()
    {
        $this->manager =
        $this->familyMember =
        $this->info =
        $this->business = null;

        parent::_after(); // TODO: Change the autogenerated stub
    }

    /**
     * @return BusinessTransaction|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    protected function getLastTransaction()
    {
        $builder = $this->em->createQueryBuilder();
        $query = $builder
            ->select('t')
            ->from(BusinessTransaction::class, 't')
            ->where($builder->expr()->eq('t.user', ':user'))
            ->setMaxResults(1)
            ->orderBy('t.createDate', 'desc')
            ->addOrderBy('t.id', 'desc')
            ->setParameter('user', $this->business)
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
