<?php

namespace AwardWallet\Tests\Unit\BusinessTransaction;

use AwardWallet\MainBundle\Entity\Cart;
use AwardWallet\MainBundle\Entity\CartItem\AwPlusSubscription;
use AwardWallet\MainBundle\Entity\Useragent;
use AwardWallet\MainBundle\Service\BusinessTransaction\AwPlusProcessor;
use Codeception\Module\Aw;

/**
 * @group frontend-unit
 * @group billing
 */
class UpgradedtoAwPlusTest extends AbstractTest
{
    /** @var Useragent */
    protected $connectedMember;
    private ?AwPlusProcessor $awPlusProcessor;

    public function _before()
    {
        parent::_before();

        // add connected member
        $newUser = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Usr::class)
            ->find($this->aw->createAwUser('new-user-' . $this->aw->grabRandomString(5), Aw::DEFAULT_PASSWORD, []));

        $this->connectedMember = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Useragent::class)
            ->find($this->aw->createConnection($newUser->getUserid(), $this->business->getUserid(), true, true, [
                "AccessLevel" => ACCESS_NONE,
            ]));
        $this->aw->createConnection($this->business->getUserid(), $newUser->getUserid(), true, true, [
            "AccessLevel" => ACCESS_WRITE,
        ]);

        $this->awPlusProcessor = $this->container->get(AwPlusProcessor::class);
    }

    public function _after()
    {
        $this->connectedMember = null;
        $this->awPlusProcessor = null;

        parent::_after(); // TODO: Change the autogenerated stub
    }

    public function testUserMustHaveRegularAccountLevelException()
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessageRegExp('#must have a Regular account level#');
        $this->info->setTrialEndDate(null)->setBalance(100);
        $this->assertTrue($this->awPlusProcessor->upgradeToAwPlus($this->connectedMember));
        $this->assertBalanceWatchCredits(0);
        $this->awPlusProcessor->upgradeToAwPlus($this->connectedMember);
    }

    public function testTrial()
    {
        $this->info->setTrialEndDate(new \DateTime("+1 day"))->setBalance(0);
        $this->assertTrue($this->info->isTrial());
        $this->assertFalse($this->awPlusProcessor->upgradeToAwPlus($this->connectedMember));
        $this->assertEmpty($lastTransaction = $this->getLastTransaction());
    }

    public function testBalanceIsZero()
    {
        $this->info->setTrialEndDate(null)->setBalance(0);
        $this->assertFalse($this->info->isTrial());
        $this->assertFalse($this->awPlusProcessor->upgradeToAwPlus($this->connectedMember));
    }

    public function testBalanceIsNotEnough()
    {
        $this->info->setBalance(3);
        $this->assertFalse($this->info->isTrial());
        $this->assertFalse($this->awPlusProcessor->upgradeToAwPlus($this->connectedMember));
    }

    public function testDiscountHundred()
    {
        $this->info->setDiscount(100);
        $this->business->getBookerInfo()->setDiscount(100);
        $this->assertFalse($this->info->isTrial());
        $this->assertFalse($this->awPlusProcessor->upgradeToAwPlus($this->connectedMember));
    }

    public function testDiscountTen()
    {
        $this->info->setBalance(30)->setDiscount(10);
        $this->assertFalse($this->info->isTrial());
        $this->assertTrue($this->awPlusProcessor->upgradeToAwPlus($this->connectedMember));
        $this->assertNotEmpty($lastTransaction = $this->getLastTransaction());
        $this->assertEquals(30, $lastTransaction->getAmount());
        $this->assertEquals(0, $lastTransaction->getBalance());
        $this->assertEquals(0, $this->info->getBalance());
        $this->assertBalanceWatchCredits(0);

        $cartId = $this->db->grabFromDatabase('Cart', 'CartID', [
            'UserID' => $this->connectedMember->getClientid()->getUserid(),
            'PaymentType' => Cart::PAYMENTTYPE_BUSINESS_BALANCE,
        ]);
        $this->assertNotEmpty($cartId);
        /** @var Cart $cart */
        $cart = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Cart::class)->find($cartId);
        $this->assertNotEmpty($cart->getPaydate());
        $this->assertTrue($cart->hasItemsByType([AwPlusSubscription::TYPE]));
        $this->assertEquals(ACCOUNT_LEVEL_AWPLUS, $this->connectedMember->getClientid()->getAccountlevel());
    }

    public function testDiscountZero()
    {
        $this->info->setBalance(35)->setDiscount(0);
        $this->assertFalse($this->info->isTrial());
        $this->assertTrue($this->awPlusProcessor->upgradeToAwPlus($this->connectedMember));
        $this->assertNotEmpty($lastTransaction = $this->getLastTransaction());
        $this->assertEquals(30, $lastTransaction->getAmount());
        $this->assertEquals(5, $lastTransaction->getBalance());
        $this->assertEquals(5, $this->info->getBalance());
        $this->assertBalanceWatchCredits(0);
    }

    private function assertBalanceWatchCredits(int $credits)
    {
        $this->assertEquals($credits, $this->db->grabFromDatabase('Usr', 'BalanceWatchCredits', [
            'UserID' => $this->connectedMember->getClientid()->getUserid(),
        ]));
    }
}
