<?php

namespace AwardWallet\MobileBundle\Form\Type\Components;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class NativeDatePicker extends AbstractType
{
    public function getBlockPrefix()
    {
        return 'native_datepicker';
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }
}
