<?php

namespace AwardWallet\MainBundle\Service\Tripit\Serializer;

use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

class ActivityObject extends BaseSerializer
{
    /**
     * @var string
     * @Assert\NotBlank()
     * @Type("string")
     */
    protected $booking_site_conf_num;
    /**
     * @var string
     * @Type("string")
     */
    private $total_cost;
    /**
     * @var DateTimeObject
     * @Assert\NotBlank()
     * @Assert\Type(DateTimeObject::class)
     * @Type("AwardWallet\MainBundle\Service\Tripit\Serializer\DateTimeObject")
     */
    private $StartDateTime;
    /**
     * @var DateTimeObject|null
     * @Type("AwardWallet\MainBundle\Service\Tripit\Serializer\DateTimeObject")
     */
    private $EndDateTime;
    /**
     * @var AddressObject
     * @Assert\NotBlank()
     * @Assert\Valid()
     * @Assert\Type(AddressObject::class)
     * @Type("AwardWallet\MainBundle\Service\Tripit\Serializer\AddressObject")
     */
    private $Address;
    /**
     * @var GuestObject[]
     * @Type("array<AwardWallet\MainBundle\Service\Tripit\Serializer\GuestObject>")
     */
    private $Participant = [];

    public function getTotalCost()
    {
        return $this->total_cost;
    }

    public function getStartDateTime(): DateTimeObject
    {
        return $this->StartDateTime;
    }

    public function getEndDateTime(): ?DateTimeObject
    {
        return $this->EndDateTime;
    }

    public function getAddress(): AddressObject
    {
        return $this->Address;
    }

    public function getParticipant(): array
    {
        return $this->Participant;
    }

    /**
     * In TripIt, a reservation of type "Activity" can be saved without an "Event Name" parameter, or "Supplier Name"
     * may not exist at all.
     */
    public function getEventName(): string
    {
        return $this->getIsDisplayNameAutoGenerated() === false && $this->getSupplierName() === '' ?
            $this->getDisplayName() :
            $this->getSupplierName();
    }
}
