<?php

namespace AwardWallet\MainBundle\Service\Tripit\Serializer;

use JMS\Serializer\Annotation\Type;

class BaseSerializer
{
    /**
     * @var int
     * @Type("int")
     */
    protected $id;
    /**
     * @var int
     * @Type("int")
     */
    protected $trip_id;
    /**
     * @var string
     * @Type("string")
     */
    protected $display_name;
    /**
     * @var bool
     * @Type("boolean_custom")
     */
    protected $is_display_name_auto_generated = false;
    /**
     * Reservation details (Booking date).
     *
     * @var string
     * @Type("string")
     */
    protected $booking_date = '';
    /**
     * Reservation details (Booking reference #).
     *
     * @var string|null
     * @Type("string")
     */
    protected $booking_site_conf_num;
    /**
     * Reservation details (Booking site name).
     *
     * @var string
     * @Type("string")
     */
    protected $booking_site_name = '';
    /**
     * Reservation details (Booking site phone).
     *
     * @var string
     * @Type("string")
     */
    protected $booking_site_phone = '';
    /**
     * Reservation details (Booking site url).
     *
     * @var string
     * @Type("string")
     */
    protected $booking_site_url = '';
    /**
     * Confirmation #.
     *
     * @var string|null
     * @Type("string")
     */
    protected $supplier_conf_num;
    /**
     * Supplier name.
     *
     * @var string
     * @Type("string")
     */
    protected $supplier_name = '';
    /**
     * Reservation details (Supplier phone).
     *
     * @var string|null
     * @Type("string")
     */
    protected $supplier_phone;
    /**
     * Reservation details (Supplier url).
     *
     * @var string
     * @Type("string")
     */
    protected $supplier_url = '';

    public function getId(): int
    {
        return $this->id;
    }

    public function getTripId(): int
    {
        return $this->trip_id;
    }

    public function getDisplayName(): string
    {
        return $this->display_name;
    }

    public function getIsDisplayNameAutoGenerated(): bool
    {
        return $this->is_display_name_auto_generated;
    }

    public function getBookingDate(): string
    {
        return $this->booking_date;
    }

    public function getBookingSiteConfNum(): ?string
    {
        return $this->booking_site_conf_num;
    }

    public function getBookingSiteName(): string
    {
        return $this->booking_site_name;
    }

    public function getBookingSitePhone(): string
    {
        return $this->booking_site_phone;
    }

    public function getBookingSiteUrl(): string
    {
        return $this->booking_site_url;
    }

    public function getSupplierConfNum(): ?string
    {
        return $this->supplier_conf_num;
    }

    public function getSupplierName(): string
    {
        return $this->supplier_name;
    }

    public function getSupplierPhone(): ?string
    {
        return $this->supplier_phone;
    }

    public function getSupplierUrl(): string
    {
        return $this->supplier_url;
    }
}
