<?php

namespace AwardWallet\MainBundle\Service\Tripit\Serializer;

use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

class RestaurantObject extends BaseSerializer
{
    /**
     * @var string
     * @Assert\NotBlank()
     * @Type("string")
     */
    protected $supplier_conf_num;
    /**
     * @var DateTimeObject
     * @Assert\NotBlank()
     * @Assert\Type(DateTimeObject::class)
     * @Type("AwardWallet\MainBundle\Service\Tripit\Serializer\DateTimeObject")
     */
    private $DateTime;
    /**
     * @var AddressObject
     * @Assert\NotBlank()
     * @Assert\Valid()
     * @Assert\Type(AddressObject::class)
     * @Type("AwardWallet\MainBundle\Service\Tripit\Serializer\AddressObject")
     */
    private $Address;
    /**
     * @var GuestObject[]
     * @Type("array<AwardWallet\MainBundle\Service\Tripit\Serializer\GuestObject>")
     */
    private $ReservationHolder = [];
    /**
     * @var int
     * @Type("int")
     */
    private $number_patrons;

    public function getDateTime(): DateTimeObject
    {
        return $this->DateTime;
    }

    public function getAddress(): AddressObject
    {
        return $this->Address;
    }

    public function getReservationHolder(): array
    {
        return $this->ReservationHolder;
    }

    public function getNumberPatrons()
    {
        return $this->number_patrons;
    }

    /**
     * In TripIt, a reservation of type "Restaurant" can be saved without a "Restaurant" parameter, or "Supplier Name"
     * may not exist at all.
     */
    public function getRestaurantName(): string
    {
        return $this->getIsDisplayNameAutoGenerated() === false && $this->getSupplierName() === '' ?
            $this->getDisplayName() :
            $this->getSupplierName();
    }
}
