<?php

namespace AwardWallet\Tests\Unit\ItineraryMail;

use AwardWallet\MainBundle\Entity\Trip;
use AwardWallet\MainBundle\Entity\Tripsegment;
use AwardWallet\MainBundle\Entity\Useragent;
use AwardWallet\MainBundle\FrameworkExtension\Mailer\Mailer;
use AwardWallet\MainBundle\FrameworkExtension\Mailer\Message;
use AwardWallet\MainBundle\FrameworkExtension\Mailer\Template\AbstractTemplate;
use AwardWallet\MainBundle\FrameworkExtension\Mailer\Template\Itinerary\ReservationChanged;
use AwardWallet\MainBundle\FrameworkExtension\Mailer\Template\Itinerary\ReservationNew;
use AwardWallet\MainBundle\Service\ItineraryMail\Sender;
use AwardWallet\MainBundle\Timeline\Manager;
use AwardWallet\Tests\Unit\BaseUserTest;
use Codeception\Module\Aw;
use Codeception\Module\Mail;

/**
 * @group frontend-unit
 */
class SenderTest extends BaseUserTest
{
    private const TTL = 20;

    /**
     * @var DummyMailer
     */
    protected $mailer;
    /**
     * @var Sender
     */
    protected $itSender;

    /**
     * @var Mail
     */
    private $mail;

    public function _before()
    {
        parent::_before();
        $this->mailer = new DummyMailer($this->container->get("aw.email.mailer"));
        $this->itSender = $this->container->get(Sender::class);
        $this->itSender->setMailer($this->mailer);
        $this->mail = $this->getModule('Mail');
    }

    public function _after()
    {
        $this->itSender =
        $this->mailer = null;
        $this->mail = null;

        parent::_after(); // TODO: Change the autogenerated stub
    }

    public function testNoNewReservations()
    {
        $this->itSender->mailNewReservations($this->user);
        $this->assertEmpty($this->mailer->sent);
    }

    public function testEmailNewReservationToAwUser()
    {
        $this->user->setLanguage("ru");
        $this->em->flush();
        $accountId = $this->aw->createAwAccount($this->user->getUserid(), Aw::TEST_PROVIDER_ID, "future.trip.random.seats");
        $this->aw->checkAccount($accountId);

        $this->itSender->mailNewReservations($this->user, ['ttl' => self::TTL]);
        $this->assertNotEmpty($this->findMessageBy([
            'user' => $this->user,
        ]));
        $this->assertStringContainsString('Сборы:	7 $', $this->mail->grabLastMail()->getBody());

        $this->mailer->reset();
        $this->itSender->mailNewReservations($this->user, ['ttl' => self::TTL]);
        $this->assertEmpty($this->mailer->sent);
    }

    public function testNoForeignFeesCardsEmailNewReservationToAwUser()
    {
        $cards = $this->em->getConnection()->fetchAllAssociative("
            SELECT CreditCardID FROM CreditCard WHERE ForeignTransactionFee = '0.0' LIMIT 4
        ");

        foreach ($cards as $card) {
            $this->db->haveInDatabase('UserCreditCard', [
                'UserID' => $this->user->getId(),
                'CreditCardID' => $card['CreditCardID'],
            ]);
        }

        $this->user->setLanguage('en');
        $this->em->flush();
        $accountId = $this->aw->createAwAccount($this->user->getUserid(), Aw::TEST_PROVIDER_ID, 'trip.overnight');
        $this->aw->checkAccount($accountId);

        $this->itSender->mailNewReservations($this->user, ['ttl' => self::TTL]);
        $this->assertNotEmpty($this->findMessageBy(['user' => $this->user]));

        $this->mailer->reset();
        $this->itSender->mailNewReservations($this->user, ['ttl' => self::TTL]);
        $this->assertEmpty($this->mailer->sent);
    }

    public function testEmailNewReservationToFamilyMember()
    {
        $db = $this->getModule('CustomDb');
        $uaId = $db->haveInDatabase("UserAgent", [
            "AgentID" => $this->user->getUserid(),
            "FirstName" => 'Ivan',
            "LastName" => 'Ivanov',
            "IsApproved" => 1,
        ]);
        $ua = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Useragent::class)->find($uaId);
        $this->user->setEmailFamilyMemberAlert(true);
        $this->em->flush();

        $accountId = $this->aw->createAwAccount($this->user->getUserid(), Aw::TEST_PROVIDER_ID, "future.trip.random.seats", "", [
            'UserAgentID' => $uaId,
        ]);
        $this->aw->checkAccount($accountId);
        $this->itSender->mailNewReservations($this->user, ['ttl' => self::TTL]);
        $sent = $this->mailer->sent;
        $this->assertTrue(sizeof($sent) == 1);
        $this->assertNotEmpty($this->findMessageBy([
            'user' => $this->user,
            'originalRecipient' => $ua,
        ]));

        $db->executeQuery("DELETE FROM Trip WHERE AccountID = {$accountId}");
        $ua->setEmail('test@test.com');
        $ua->setSendemails(true);
        $this->em->flush();

        $this->aw->checkAccount($accountId);
        $this->mailer->reset();
        $this->itSender->mailNewReservations($this->user, ['ttl' => self::TTL]);
        $sent = $this->mailer->sent;
        $this->assertTrue(sizeof($sent) == 2);
        $this->assertNotEmpty($this->findMessageBy([
            'user' => $this->user,
            'originalRecipient' => $ua,
        ]));
        $this->assertNotEmpty($this->findMessageBy([
            'user' => $ua,
        ]));

        $db->executeQuery("DELETE FROM Trip WHERE AccountID = {$accountId}");
        $ua->setEmail('test@test.com');
        $ua->setSendemails(false);
        $this->user->setEmailFamilyMemberAlert(false);
        $this->em->flush();

        $this->aw->checkAccount($accountId);
        $this->mailer->reset();
        $this->itSender->mailNewReservations($this->user, ['ttl' => self::TTL]);
        $this->assertEmpty($this->mailer->sent);
    }

    public function testEmailNewReservationToBusinessUser()
    {
        $userId = $this->aw->createAwUser('test' . $this->aw->grabRandomString(5), Aw::DEFAULT_PASSWORD, [
            'AccountLevel' => ACCOUNT_LEVEL_BUSINESS,
        ], true);
        $user = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Usr::class)->find($userId);
        $accountId = $this->aw->createAwAccount($user->getUserid(), Aw::TEST_PROVIDER_ID, "future.trip.random.seats");
        $this->aw->checkAccount($accountId);

        $this->itSender->mailNewReservations($user, ['ttl' => self::TTL]);
        $this->assertEmpty($this->mailer->sent);
    }

    public function testEmailNewReservationToBusinessMember()
    {
        $startTime = time();
        $userId = $this->aw->createAwUser('test' . $this->aw->grabRandomString(5), Aw::DEFAULT_PASSWORD, [
            'AccountLevel' => ACCOUNT_LEVEL_BUSINESS,
        ], true);
        $user = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Usr::class)->find($userId);
        $db = $this->getModule('CustomDb');
        $uaId = $db->haveInDatabase("UserAgent", [
            "AgentID" => $user->getUserid(),
            "FirstName" => 'Ivan',
            "LastName" => 'Ivanov',
            "Email" => 'Ivanov@test.com',
            "SendEmails" => '1',
            "IsApproved" => 1,
        ]);
        $ua = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Useragent::class)->find($uaId);

        $accountId = $this->aw->createAwAccount($user->getUserid(), Aw::TEST_PROVIDER_ID, "future.trip.round", "", [
            'UserAgentID' => $uaId,
        ]);
        $this->aw->checkAccount($accountId);
        $this->itSender->mailNewReservations($user, ['ttl' => time() - $startTime + self::TTL]);
        $sent = $this->mailer->sent;
        $this->assertCount(1, $sent);
        $this->assertNotEmpty($this->findMessageBy([
            'user' => $ua,
        ]));
    }

    public function testEmailNewReservationWithOldSegment()
    {
        $accountId = $this->aw->createAwAccount($this->user->getUserid(), Aw::TEST_PROVIDER_ID, "future.trip.random.seats");
        $this->aw->checkAccount($accountId);

        $tripId = $this->db->grabFromDatabase("Trip", "TripID", ["AccountID" => $accountId, "UserID" => $this->user->getUserid()]);
        $this->assertNotEmpty($tripId);
        $trip = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Trip::class)->find($tripId);
        /** @var Tripsegment $firstTs */
        $firstTs = $trip->getSegments()[0];
        $secondTs = new Tripsegment();
        $trip->addSegment($secondTs);
        $secondTs->setTripid($trip);
        $secondTs->setDepcode("HKG");
        $secondTs->setDepname("Hong Kong");
        $secondTs->setDepdate(new \DateTime("-1 month"));
        $secondTs->setArrcode("LHR");
        $secondTs->setArrname("London, United Kingdom (Heathrow)");
        $secondTs->setArrdate(new \DateTime("-29 day"));
        $secondTs->setFlightnumber("321");
        $secondTs->setAirlineName("Cathay Pacific");
        $this->em->flush();

        $this->assertCount(2, $trip->getSegments());

        $this->itSender->mailNewReservations($this->user, ['ttl' => self::TTL]);
        $sent = $this->mailer->sent;
        $this->assertTrue(sizeof($sent) == 1);
        $this->assertNotEmpty($message = $this->findMessageBy([
            'user' => $this->user,
        ]));
        $this->assertCount(1, $message->itineraries);
        $this->assertCount(1, $message->itineraries[0]->getSegments());
        $this->assertEquals($firstTs->getTripsegmentid(), $message->itineraries[0]->getSegments()[0]->getItinerary()->getTripsegmentid());

        $this->mailer->reset();
        $this->em->refresh($trip);

        $trip->setMailDate(null);
        $secondTs->setDepdate(new \DateTime())
            ->setArrdate(new \DateTime());
        $this->em->flush();

        $this->itSender->mailNewReservations($this->user, ['ttl' => self::TTL]);
        $sent = $this->mailer->sent;
        $this->assertTrue(sizeof($sent) == 1);
        $this->assertNotEmpty($message = $this->findMessageBy([
            'user' => $this->user,
        ]));
        $this->assertCount(1, $message->itineraries);
        $this->assertCount(2, $message->itineraries[0]->getSegments());

        $this->mailer->reset();
        $this->em->refresh($trip);

        $trip->setMailDate(null);
        $firstTs->setDepdate(new \DateTime("-1 month"))
            ->setArrdate(new \DateTime("-29 day"));
        $this->em->flush();

        $this->itSender->mailNewReservations($this->user, ['ttl' => self::TTL]);
        $sent = $this->mailer->sent;
        $this->assertTrue(sizeof($sent) == 1);
        $this->assertNotEmpty($message = $this->findMessageBy([
            'user' => $this->user,
        ]));
        $this->assertCount(1, $message->itineraries);
        $this->assertCount(1, $message->itineraries[0]->getSegments());
        $this->assertEquals($secondTs->getTripsegmentid(), $message->itineraries[0]->getSegments()[0]->getItinerary()->getTripsegmentid());
    }

    public function testCheckboxEmailNewPlans()
    {
        $this->user->setEmailnewplans(false);
        $this->em->flush();
        $accountId = $this->aw->createAwAccount($this->user->getUserid(), Aw::TEST_PROVIDER_ID, "future.trip.random.seats");
        $this->aw->checkAccount($accountId);

        $this->itSender->mailNewReservations($this->user, ['ttl' => self::TTL]);
        $this->assertEmpty($this->mailer->sent);

        $this->mailer->reset();
        $this->getModule('CustomDb')->executeQuery("DELETE FROM Trip WHERE AccountID = {$accountId}");
        $this->user->setEmailnewplans(true);
        $this->em->flush();
        $this->aw->checkAccount($accountId);
        $this->itSender->mailNewReservations($this->user, ['ttl' => self::TTL]);
        $this->assertTrue(sizeof($this->mailer->sent) == 1);
    }

    public function testNoChangedReservations()
    {
        $this->itSender->mailChangedReservations($this->user);
        $this->assertEmpty($this->mailer->sent);
    }

    public function testEmailChangedReservationToAwUser()
    {
        $accountId = $this->aw->createAwAccount($this->user->getUserid(), Aw::TEST_PROVIDER_ID, "future.trip.random.seats");
        $this->aw->checkAccount($accountId);
        $this->aw->checkAccount($accountId);

        $this->itSender->mailChangedReservations($this->user, ['ttl' => self::TTL]);
        $this->assertNotEmpty($this->findMessageBy([
            'user' => $this->user,
        ]));

        $this->mailer->reset();
        $this->itSender->mailChangedReservations($this->user, ['ttl' => self::TTL]);
        $this->assertEmpty($this->mailer->sent);
    }

    public function testEmailChangedReservationToFamilyMember()
    {
        $db = $this->getModule('CustomDb');
        $uaId = $db->haveInDatabase("UserAgent", [
            "AgentID" => $this->user->getUserid(),
            "FirstName" => 'Ivan',
            "LastName" => 'Ivanov',
            "IsApproved" => 1,
        ]);
        $ua = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Useragent::class)->find($uaId);
        $this->user->setEmailFamilyMemberAlert(true);
        $this->em->flush();

        $accountId = $this->aw->createAwAccount($this->user->getUserid(), Aw::TEST_PROVIDER_ID, "future.trip.random.seats", "", [
            'UserAgentID' => $uaId,
        ]);
        $this->aw->checkAccount($accountId, true);
        $this->aw->checkAccount($accountId, true);
        $this->itSender->mailChangedReservations($this->user, ['ttl' => self::TTL]);
        $sent = $this->mailer->sent;
        $this->assertTrue(sizeof($sent) == 1);
        $this->assertNotEmpty($this->findMessageBy([
            'user' => $this->user,
            'originalRecipient' => $ua,
        ]));

        $db->executeQuery("DELETE FROM Trip WHERE AccountID = {$accountId}");
        $ua->setEmail('test@test.com');
        $ua->setSendemails(true);
        $this->em->flush();

        $this->aw->checkAccount($accountId, true);
        $this->aw->checkAccount($accountId, true);
        $this->mailer->reset();
        $this->itSender->mailChangedReservations($this->user, ['ttl' => self::TTL]);
        $sent = $this->mailer->sent;
        $this->assertTrue(sizeof($sent) == 2);
        $this->assertNotEmpty($this->findMessageBy([
            'user' => $this->user,
            'originalRecipient' => $ua,
        ]));
        $this->assertNotEmpty($this->findMessageBy([
            'user' => $ua,
        ]));

        $db->executeQuery("DELETE FROM Trip WHERE AccountID = {$accountId}");
        $ua->setEmail('test@test.com');
        $ua->setSendemails(false);
        $this->user->setEmailFamilyMemberAlert(false);
        $this->em->flush();

        $this->aw->checkAccount($accountId, true);
        $this->aw->checkAccount($accountId, true);
        $this->mailer->reset();
        $this->itSender->mailChangedReservations($this->user, ['ttl' => self::TTL]);
        $this->assertEmpty($this->mailer->sent);
    }

    public function testEmailChangedReservationToBusinessUser()
    {
        $userId = $this->aw->createAwUser('test' . $this->aw->grabRandomString(5), Aw::DEFAULT_PASSWORD, [
            'AccountLevel' => ACCOUNT_LEVEL_BUSINESS,
        ], true);
        $user = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Usr::class)->find($userId);
        $accountId = $this->aw->createAwAccount($user->getUserid(), Aw::TEST_PROVIDER_ID, "future.trip.random.seats");
        $this->aw->checkAccount($accountId, true);
        $this->aw->checkAccount($accountId, true);

        $this->itSender->mailChangedReservations($user, ['ttl' => self::TTL]);
        $this->assertEmpty($this->mailer->sent);
    }

    public function testEmailChangedReservationToBusinessMember()
    {
        $userId = $this->aw->createAwUser('test' . $this->aw->grabRandomString(5), Aw::DEFAULT_PASSWORD, [
            'AccountLevel' => ACCOUNT_LEVEL_BUSINESS,
        ], true);
        $user = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Usr::class)->find($userId);
        $db = $this->getModule('CustomDb');
        $uaId = $db->haveInDatabase("UserAgent", [
            "AgentID" => $user->getUserid(),
            "FirstName" => 'Ivan',
            "LastName" => 'Ivanov',
            "Email" => 'Ivanov@test.com',
            "SendEmails" => '1',
            "IsApproved" => 1,
        ]);
        $ua = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Useragent::class)->find($uaId);

        $accountId = $this->aw->createAwAccount($user->getUserid(), Aw::TEST_PROVIDER_ID, "future.trip.random.seats", "", [
            'UserAgentID' => $uaId,
        ]);
        $this->aw->checkAccount($accountId, true);
        $this->aw->checkAccount($accountId, true);
        $this->itSender->mailChangedReservations($user, ['ttl' => self::TTL]);
        $sent = $this->mailer->sent;
        $this->assertTrue(sizeof($sent) == 1);
        $this->assertNotEmpty($this->findMessageBy([
            'user' => $ua,
        ]));
    }

    public function testCheckboxEmailChangedPlans()
    {
        $this->user->setEmailplanschanges(false);
        $this->em->flush();
        $accountId = $this->aw->createAwAccount($this->user->getUserid(), Aw::TEST_PROVIDER_ID, "future.trip.random.seats");
        $this->aw->checkAccount($accountId, true);
        $this->aw->checkAccount($accountId, true);

        $this->itSender->mailChangedReservations($this->user, ['ttl' => self::TTL]);
        $this->assertEmpty($this->mailer->sent);

        $this->mailer->reset();
        $this->getModule('CustomDb')->executeQuery("DELETE FROM Trip WHERE AccountID = {$accountId}");
        $this->user->setEmailplanschanges(true);
        $this->em->flush();
        $this->aw->checkAccount($accountId, true);
        $this->aw->checkAccount($accountId, true);
        $this->itSender->mailChangedReservations($this->user, ['ttl' => self::TTL]);
        $this->assertTrue(sizeof($this->mailer->sent) == 1);
    }

    public function testMultiReservations()
    {
        $db = $this->getModule('CustomDb');
        $uaId = $db->haveInDatabase("UserAgent", [
            "AgentID" => $this->user->getUserid(),
            "FirstName" => 'Ivan',
            "LastName" => 'Ivanov',
            "IsApproved" => 1,
        ]);
        /** @var Useragent $ua */
        $ua = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Useragent::class)->find($uaId);
        $ua->setEmail('test@test.com');
        $ua->setSendemails(true);
        $this->user->setEmailFamilyMemberAlert(true);
        $this->em->flush();

        // account #1
        $accountId1 = $this->aw->createAwAccount($this->user->getUserid(), Aw::TEST_PROVIDER_ID, "future.trip.random.seats", "", [
            'UserAgentID' => $uaId,
        ]);
        $this->aw->checkAccount($accountId1, true);
        // account #2
        $accountId2 = $this->aw->createAwAccount($this->user->getUserid(), Aw::TEST_PROVIDER_ID, "future.reservation");
        $this->aw->checkAccount($accountId2, true);
        // account #3
        $accountId3 = $this->aw->createAwAccount($this->user->getUserid(), Aw::TEST_PROVIDER_ID, "future.trip.random.props");
        $this->aw->checkAccount($accountId3, true);

        $this->itSender->mailNewReservations($this->user, ['ttl' => self::TTL]);
        $sent = $this->mailer->sent;
        $this->assertCount(3, $sent);

        $userMessage = $this->findMessageBy([
            'user' => $this->user,
            'originalRecipient' => null,
        ]);
        $userCopyMessage = $this->findMessageBy([
            'user' => $this->user,
            'originalRecipient' => $ua,
        ]);
        $uaMessage = $this->findMessageBy([
            'user' => $ua,
        ]);

        $this->assertNotEmpty($userMessage);
        $this->assertEquals(2, count($userMessage->itineraries));
        $this->assertNotEmpty($userCopyMessage);
        $this->assertEquals(1, count($userCopyMessage->itineraries));
        $this->assertNotEmpty($uaMessage);
        $this->assertEquals(1, count($uaMessage->itineraries));

        $this->mailer->reset();
        sleep(2);
        $this->aw->checkAccount($accountId1, true);
        $this->aw->checkAccount($accountId2, true);
        $this->aw->checkAccount($accountId3, true);

        $this->itSender->mailChangedReservations($this->user, ['ttl' => self::TTL]);
        $sent = $this->mailer->sent;
        $this->assertCount(3, $sent);
        $userMessage = $this->findMessageBy([
            'user' => $this->user,
        ]);
        $userCopyMessage = $this->findMessageBy([
            'user' => $this->user,
            'originalRecipient' => $ua,
        ]);
        $uaMessage = $this->findMessageBy([
            'user' => $ua,
        ]);

        $this->assertNotEmpty($userMessage);
        $this->assertEquals(1, count($userMessage->itineraries));
        $this->assertNotEmpty($userCopyMessage);
        $this->assertEquals(1, count($userCopyMessage->itineraries));
        $this->assertNotEmpty($uaMessage);
        $this->assertEquals(1, count($uaMessage->itineraries));
    }

    public function testCopiedReservations()
    {
        $db = $this->getModule('CustomDb');
        // family member 1
        $uaId = $db->haveInDatabase("UserAgent", [
            "AgentID" => $this->user->getUserid(),
            "FirstName" => 'Ivan',
            "LastName" => 'Ivanov',
            "IsApproved" => 1,
        ]);
        /** @var Useragent $ua */
        $ua = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Useragent::class)->find($uaId);
        $ua->setEmail('test@test.com');
        $ua->setSendemails(true);

        // family member 2
        $uaId2 = $db->haveInDatabase("UserAgent", [
            "AgentID" => $this->user->getUserid(),
            "FirstName" => 'Jessica',
            "LastName" => 'Petrova',
            "IsApproved" => 1,
        ]);
        /** @var Useragent $ua */
        $ua2 = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Useragent::class)->find($uaId2);
        $ua2->setEmail('test@test2.com');
        $ua2->setSendemails(true);

        $this->user->setEmailFamilyMemberAlert(true);
        $this->em->flush();

        // account #1
        $accountId1 = $this->aw->createAwAccount($this->user->getUserid(), Aw::TEST_PROVIDER_ID, "future.trip.random.seats", "", [
            'UserAgentID' => $uaId,
        ]);
        $this->aw->checkAccount($accountId1, true);
        /** @var Trip $trip */
        $trip = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Trip::class)->findOneBy([
            'account' => $accountId1,
        ]);
        /** @var Tripsegment $segment */
        $segment = $trip->getSegments()->first();
        $this->container->get(Manager::class)->moveItinerary(
            "T." . $segment->getTripsegmentid(),
            $ua2,
            true
        );

        $this->itSender->mailNewReservations($this->user, ['ttl' => self::TTL]);
        $sent = $this->mailer->sent;
        $this->assertCount(4, $sent);

        $ua1CopyMessage = $this->findMessageBy([
            'user' => $this->user,
            'originalRecipient' => $ua,
        ]);
        $ua2CopyMessage = $this->findMessageBy([
            'user' => $this->user,
            'originalRecipient' => $ua2,
        ]);
        $ua1Message = $this->findMessageBy([
            'user' => $ua,
        ]);
        $ua2Message = $this->findMessageBy([
            'user' => $ua2,
        ]);

        $this->assertNotEmpty($ua1CopyMessage);
        $this->assertEquals(1, count($ua1CopyMessage->itineraries));
        $this->assertNotEmpty($ua2CopyMessage);
        $this->assertEquals(1, count($ua2CopyMessage->itineraries));
        $this->assertNotEmpty($ua1Message);
        $this->assertEquals(1, count($ua1Message->itineraries));
        $this->assertNotEmpty($ua2Message);
        $this->assertEquals(1, count($ua2Message->itineraries));
    }

    public function testExpiredChanges()
    {
        $accountId = $this->aw->createAwAccount($this->user->getUserid(), Aw::TEST_PROVIDER_ID, "future.trip.random.seats");
        $this->aw->checkAccount($accountId, true);
        $this->aw->checkAccount($accountId, true);
        /** @var Trip $trip */
        $trip = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Trip::class)->findOneBy([
            'account' => $accountId,
        ]);
        /** @var Tripsegment $segment */
        $segment = $trip->getSegments()->first();
        $this->db->executeQuery("UPDATE DiffChange SET ChangeDate = NOW() - INTERVAL 3601 SECOND WHERE SourceID = 'S." . $segment->getTripsegmentid() . "'");
        $this->itSender->mailChangedReservations($this->user, ['ttl' => self::TTL]);
        $this->assertEmpty($this->mailer->sent);
        $this->mailer->reset();
        $this->aw->checkAccount($accountId, true);
        $this->itSender->mailChangedReservations($this->user, ['ttl' => self::TTL]);
        $this->assertNotEmpty($this->mailer->sent);
        $this->assertCount(1, $this->mailer->sent);
    }

    public function testWhiteList()
    {
        $db = $this->getModule('CustomDb');
        $uaId = $db->haveInDatabase("UserAgent", [
            "AgentID" => $this->user->getUserid(),
            "FirstName" => 'Ivan',
            "LastName" => 'Ivanov',
            "IsApproved" => 1,
        ]);
        /** @var Useragent $ua */
        $ua = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Useragent::class)->find($uaId);
        $ua->setSendemails(false);
        $this->user->setEmailFamilyMemberAlert(true);
        $this->em->flush();

        // account #1
        $accountId1 = $this->aw->createAwAccount($this->user->getUserid(), Aw::TEST_PROVIDER_ID, "future.trip.random.props.not_white_list", "", [
            'UserAgentID' => $uaId,
        ]);
        $this->aw->checkAccount($accountId1, true);
        $this->aw->checkAccount($accountId1, true);

        // account #2
        $accountId2 = $this->aw->createAwAccount($this->user->getUserid(), Aw::TEST_PROVIDER_ID, "future.trip.random.seats");
        $this->aw->checkAccount($accountId2, true);
        $this->aw->checkAccount($accountId2, true);

        $this->itSender->mailChangedReservations($this->user, ['ttl' => self::TTL]);
        $this->assertEmpty($this->findMessageBy([
            'user' => $this->user,
            'originalRecipient' => $ua,
        ]));
        $this->assertNotEmpty($this->findMessageBy([
            'user' => $this->user,
        ]));
        $sent = $this->mailer->sent;
        $this->assertEquals(1, sizeof($sent));
    }

    /**
     * @param array $data
     * @return ReservationChanged|ReservationNew
     */
    protected function findMessageBy($data)
    {
        $messages = $this->mailer->sent;

        /** @var AbstractTemplate $message */
        foreach ($messages as $message) {
            $vars = $message->getTemplateVars();

            foreach ($data as $name => $value) {
                if (!array_key_exists($name, $vars) || ((!is_null($value) && $value != $vars[$name]) || (is_null($value) && !is_null($vars[$name])))) {
                    continue 2;
                }
            }

            return $message;
        }

        return null;
    }
}

class DummyMailer extends Mailer
{
    public $messages;

    public $sent = [];
    /**
     * @var Mailer
     */
    private $delegate;

    public function __construct(Mailer $delegate)
    {
        $this->delegate = $delegate;
    }

    public function reset()
    {
        $this->sent = [];
    }

    public function send($messages, $options = [])
    {
        $this->messages = $messages;

        if (isset($options[Mailer::OPTION_ON_SUCCESSFUL_SEND])) {
            call_user_func($options[Mailer::OPTION_ON_SUCCESSFUL_SEND]);
        }

        return $this->delegate->send($messages, $options);
    }

    public function getMessageByTemplate(AbstractTemplate $template, $extTemplateVars = []): Message
    {
        $this->sent[] = $template;

        return $this->delegate->getMessageByTemplate($template, $extTemplateVars);
    }

    public function getEmail($kind)
    {
        return $this->delegate->getEmail($kind);
    }

    public function getMessages()
    {
        return $this->messages;
    }
}
