export const HEADER_CONSTANTS = {
    MAX_SCROLL: 100,

    MIN_PADDING_TOP_DESKTOP: 29,
    MIN_PADDING_BOTTOM_DESKTOP: 28,
    MAX_PADDING_TOP_DESKTOP_LARGE: 41,
    MAX_PADDING_BOTTOM_DESKTOP_LARGE: 40,

    MIN_PADDING_TOP_MOBILE: 16,
    MIN_PADDING_BOTTOM_MOBILE: 12,
    MAX_PADDING_TOP_MOBILE_LARGE: 23,
    MAX_PADDING_BOTTOM_MOBILE_LARGE: 12,
    MAX_PADDING_TOP_MOBILE_SMALL: 18,
    MAX_PADDING_BOTTOM_MOBILE_SMALL: 12,

    MOBILE_BREAKPOINT: 1360,
    MOBILE_SMALL_BREAKPOINT: 700,

    POPOVER_OFFSET_FROM_ANCHOR: 10,
    POPOVER_OFFSET_FROM_WINDOW: 30,
};
