<?php
/**
 * PullTripAlertsApi
 * PHP version 5.
 *
 * @category Class
 * @author   Swagger Codegen team
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FlightStats, Inc. Trip Solutions API.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flightstats.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Api;

use AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\ApiException;
use AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Configuration;
use AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\HeaderSelector;
use AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\ObjectSerializer;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;

/**
 * PullTripAlertsApi Class Doc Comment.
 *
 * @category Class
 * @author   Swagger Codegen team
 * @see     https://github.com/swagger-api/swagger-codegen
 */
class PullTripAlertsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation alertsGet.
     *
     * Returns the next trip alerts for you to process
     *
     * @param  string $appId Application ID (required)
     * @param  string $appKey Application Key (required)
     * @param  int $maxAlerts The maximum number of alerts to return in a single call (default &#x3D; 1, limit&#x3D;100) (optional, default to 1)
     * @param  bool $peek Allows you to retrieve alerts without changing the position of the last alert retrieved (optional)
     * @return \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\Alert[]
     * @throws \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function alertsGet($appId, $appKey, $maxAlerts = '1', $peek = null)
    {
        [$response] = $this->alertsGetWithHttpInfo($appId, $appKey, $maxAlerts, $peek);

        return $response;
    }

    /**
     * Operation alertsGetWithHttpInfo.
     *
     * Returns the next trip alerts for you to process
     *
     * @param  string $appId Application ID (required)
     * @param  string $appKey Application Key (required)
     * @param  int $maxAlerts The maximum number of alerts to return in a single call (default &#x3D; 1, limit&#x3D;100) (optional, default to 1)
     * @param  bool $peek Allows you to retrieve alerts without changing the position of the last alert retrieved (optional)
     * @return array of \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\Alert[], HTTP status code, HTTP response headers (array of strings)
     * @throws \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function alertsGetWithHttpInfo($appId, $appKey, $maxAlerts = '1', $peek = null)
    {
        $returnType = '\AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\Alert[]';
        $request = $this->alertsGetRequest($appId, $appKey, $maxAlerts, $peek);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null);
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $request->getUri()), $statusCode, $response->getHeaders(), $response->getBody());
            }

            $responseBody = $response->getBody();

            if ($returnType === '\SplFileObject') {
                $content = $responseBody; // stream goes to serializer
            } else {
                $content = $responseBody->getContents();

                if (!in_array($returnType, ['string', 'integer', 'bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\Alert[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation alertsGetAsync.
     *
     * Returns the next trip alerts for you to process
     *
     * @param  string $appId Application ID (required)
     * @param  string $appKey Application Key (required)
     * @param  int $maxAlerts The maximum number of alerts to return in a single call (default &#x3D; 1, limit&#x3D;100) (optional, default to 1)
     * @param  bool $peek Allows you to retrieve alerts without changing the position of the last alert retrieved (optional)
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @throws \InvalidArgumentException
     */
    public function alertsGetAsync($appId, $appKey, $maxAlerts = '1', $peek = null)
    {
        return $this->alertsGetAsyncWithHttpInfo($appId, $appKey, $maxAlerts, $peek)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation alertsGetAsyncWithHttpInfo.
     *
     * Returns the next trip alerts for you to process
     *
     * @param  string $appId Application ID (required)
     * @param  string $appKey Application Key (required)
     * @param  int $maxAlerts The maximum number of alerts to return in a single call (default &#x3D; 1, limit&#x3D;100) (optional, default to 1)
     * @param  bool $peek Allows you to retrieve alerts without changing the position of the last alert retrieved (optional)
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @throws \InvalidArgumentException
     */
    public function alertsGetAsyncWithHttpInfo($appId, $appKey, $maxAlerts = '1', $peek = null)
    {
        $returnType = '\AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\Model\Alert[]';
        $request = $this->alertsGetRequest($appId, $appKey, $maxAlerts, $peek);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();

                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; // stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();

                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), $response->getBody());
                }
            );
    }

    /**
     * Operation alertsResetPost.
     *
     * Reset the alerts service to a particular point in time
     *
     * @param  string $appId Application ID (required)
     * @param  string $appKey Application Key (required)
     * @param  string $timestamp The timestamp to set the cursor position to in UTC (\&quot;YYYY-MM-DDThh:mm:ssZ\&quot;) (required)
     * @return void
     * @throws \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function alertsResetPost($appId, $appKey, $timestamp)
    {
        $this->alertsResetPostWithHttpInfo($appId, $appKey, $timestamp);
    }

    /**
     * Operation alertsResetPostWithHttpInfo.
     *
     * Reset the alerts service to a particular point in time
     *
     * @param  string $appId Application ID (required)
     * @param  string $appKey Application Key (required)
     * @param  string $timestamp The timestamp to set the cursor position to in UTC (\&quot;YYYY-MM-DDThh:mm:ssZ\&quot;) (required)
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \AwardWallet\MainBundle\Service\FlightStats\TripAlerts\API\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function alertsResetPostWithHttpInfo($appId, $appKey, $timestamp)
    {
        $returnType = '';
        $request = $this->alertsResetPostRequest($appId, $appKey, $timestamp);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null);
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $request->getUri()), $statusCode, $response->getHeaders(), $response->getBody());
            }

            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }
    }

    /**
     * Operation alertsResetPostAsync.
     *
     * Reset the alerts service to a particular point in time
     *
     * @param  string $appId Application ID (required)
     * @param  string $appKey Application Key (required)
     * @param  string $timestamp The timestamp to set the cursor position to in UTC (\&quot;YYYY-MM-DDThh:mm:ssZ\&quot;) (required)
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @throws \InvalidArgumentException
     */
    public function alertsResetPostAsync($appId, $appKey, $timestamp)
    {
        return $this->alertsResetPostAsyncWithHttpInfo($appId, $appKey, $timestamp)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation alertsResetPostAsyncWithHttpInfo.
     *
     * Reset the alerts service to a particular point in time
     *
     * @param  string $appId Application ID (required)
     * @param  string $appKey Application Key (required)
     * @param  string $timestamp The timestamp to set the cursor position to in UTC (\&quot;YYYY-MM-DDThh:mm:ssZ\&quot;) (required)
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @throws \InvalidArgumentException
     */
    public function alertsResetPostAsyncWithHttpInfo($appId, $appKey, $timestamp)
    {
        $returnType = '';
        $request = $this->alertsResetPostRequest($appId, $appKey, $timestamp);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), $response->getBody());
                }
            );
    }

    /**
     * Create request for operation 'alertsGet'.
     *
     * @param  string $appId Application ID (required)
     * @param  string $appKey Application Key (required)
     * @param  int $maxAlerts The maximum number of alerts to return in a single call (default &#x3D; 1, limit&#x3D;100) (optional, default to 1)
     * @param  bool $peek Allows you to retrieve alerts without changing the position of the last alert retrieved (optional)
     * @return \GuzzleHttp\Psr7\Request
     * @throws \InvalidArgumentException
     */
    protected function alertsGetRequest($appId, $appKey, $maxAlerts = '1', $peek = null)
    {
        // verify the required parameter 'appId' is set
        if ($appId === null || (is_array($appId) && count($appId) === 0)) {
            throw new \InvalidArgumentException('Missing the required parameter $appId when calling alertsGet');
        }

        // verify the required parameter 'appKey' is set
        if ($appKey === null || (is_array($appKey) && count($appKey) === 0)) {
            throw new \InvalidArgumentException('Missing the required parameter $appKey when calling alertsGet');
        }

        $resourcePath = '/alerts';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($appId !== null) {
            $queryParams['appId'] = ObjectSerializer::toQueryValue($appId, null);
        }

        // query params
        if ($appKey !== null) {
            $queryParams['appKey'] = ObjectSerializer::toQueryValue($appKey, null);
        }

        // query params
        if ($maxAlerts !== null) {
            $queryParams['maxAlerts'] = ObjectSerializer::toQueryValue($maxAlerts, null);
        }

        // query params
        if ($peek !== null) {
            $queryParams['peek'] = ObjectSerializer::toQueryValue($peek, null);
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];

                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue,
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        $defaultHeaders = [];

        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);

        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create request for operation 'alertsResetPost'.
     *
     * @param  string $appId Application ID (required)
     * @param  string $appKey Application Key (required)
     * @param  string $timestamp The timestamp to set the cursor position to in UTC (\&quot;YYYY-MM-DDThh:mm:ssZ\&quot;) (required)
     * @return \GuzzleHttp\Psr7\Request
     * @throws \InvalidArgumentException
     */
    protected function alertsResetPostRequest($appId, $appKey, $timestamp)
    {
        // verify the required parameter 'appId' is set
        if ($appId === null || (is_array($appId) && count($appId) === 0)) {
            throw new \InvalidArgumentException('Missing the required parameter $appId when calling alertsResetPost');
        }

        // verify the required parameter 'appKey' is set
        if ($appKey === null || (is_array($appKey) && count($appKey) === 0)) {
            throw new \InvalidArgumentException('Missing the required parameter $appKey when calling alertsResetPost');
        }

        // verify the required parameter 'timestamp' is set
        if ($timestamp === null || (is_array($timestamp) && count($timestamp) === 0)) {
            throw new \InvalidArgumentException('Missing the required parameter $timestamp when calling alertsResetPost');
        }

        $resourcePath = '/alerts/reset';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($appId !== null) {
            $queryParams['appId'] = ObjectSerializer::toQueryValue($appId, null);
        }

        // query params
        if ($appKey !== null) {
            $queryParams['appKey'] = ObjectSerializer::toQueryValue($appKey, null);
        }

        // query params
        if ($timestamp !== null) {
            $queryParams['timestamp'] = ObjectSerializer::toQueryValue($timestamp, null);
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];

                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue,
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        $defaultHeaders = [];

        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);

        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option.
     *
     * @return array of http client options
     * @throws \RuntimeException on file opening failure
     */
    protected function createHttpClientOption()
    {
        $options = [];

        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');

            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
