<?php

namespace AwardWallet\Tests\Unit\PushNotifications;

use AwardWallet\MainBundle\Entity\MobileDevice;
use AwardWallet\MainBundle\Manager\MobileDeviceManager;
use AwardWallet\MainBundle\Service\BackgroundCheckScheduler;
use AwardWallet\MainBundle\Worker\PushNotification\DTO\Notification;
use AwardWallet\Tests\Unit\BaseUserTest;
use Codeception\Module\Aw;
use Codeception\Stub\Expected;
use Doctrine\Common\Persistence\ObjectRepository;

/**
 * @covers \AwardWallet\MainBundle\Manager\MobileDeviceManager
 * @group mobile
 * @group push
 * @group frontend-unit
 */
class MobileDeviceManagerTest extends BaseUserTest
{
    public const DEVICE_KEY_1 = 'ABCDEFG123456';
    public const DEVICE_KEY_2 = 'ABCDEFG1234567800';
    /**
     * @var MobileDeviceManager
     */
    private $manager;

    /**
     * @var ObjectRepository
     */
    private $rep;

    public function _before()
    {
        parent::_before();
        $this->manager = $this->container->get('aw.manager.mobile_device_manager');
        $this->rep = $this->em->getRepository(\AwardWallet\MainBundle\Entity\MobileDevice::class);
    }

    public function _after()
    {
        $this->manager =
        $this->rep = null;

        parent::_after(); // TODO: Change the autogenerated stub
    }

    public function testManagerShouldReuseExistingDeviceForSameUser()
    {
        $this->mockBackgroundCheckScheduler(2);
        $device1 = $this->manager->addDevice($this->user->getUserid(), 'android', self::DEVICE_KEY_1, 'en', '1.1.1', '127.0.0.1');
        $this->clearEm();
        $device2 = $this->manager->addDevice($this->user->getUserid(), 'android', self::DEVICE_KEY_1, 'en', '1.1.1', '127.0.0.1');
        $this->assertEquals($device1->getMobileDeviceId(), $device2->getMobileDeviceId());
    }

    public function testManagerShouldRemoveDevicesForOtherUsers()
    {
        $this->mockBackgroundCheckScheduler(2);
        $device1 = $this->manager->addDevice($this->user->getUserid(), 'android', self::DEVICE_KEY_1, 'en', '1.1.1', '127.0.0.1');
        $newUserId = $this->aw->createAwUser('test' . $this->aw->grabRandomString(5), Aw::DEFAULT_PASSWORD, [], true /* staff user has access to test provider */);
        $device2 = $this->manager->addDevice($newUserId, 'android', self::DEVICE_KEY_1, 'en', '1.1.1', '127.0.0.1');
        $this->assertNotEquals($device1->getMobileDeviceId(), $device2->getMobileDeviceId());
        $this->clearEm();
        $this->assertEquals(0, count($this->rep->findBy(['userId' => $this->user->getUserid(), 'deviceType' => MobileDevice::TYPE_ANDROID, 'deviceKey' => self::DEVICE_KEY_1])));
        $this->assertEquals(1, count($this->rep->findBy(['userId' => $newUserId, 'deviceType' => MobileDevice::TYPE_ANDROID, 'deviceKey' => self::DEVICE_KEY_1])));
    }

    public function testManagerShouldRemoveDeviceById()
    {
        $this->mockBackgroundCheckScheduler(2);
        $device1 = $this->manager->addDevice($this->user->getUserid(), 'android', self::DEVICE_KEY_1, 'en', '1.1.1', '127.0.0.1');
        $this->manager->removeDeviceById($device1->getMobileDeviceId());
        $this->clearEm();
        $this->assertEquals(0, count($this->rep->findBy(['mobileDeviceId' => $device1->getMobileDeviceId()])));
    }

    public function testManagerShouldRemoveDeviceByKey()
    {
        $this->mockBackgroundCheckScheduler(2);
        $device1 = $this->manager->addDevice($this->user->getUserid(), 'android', self::DEVICE_KEY_1, 'en', '1.1.1', '127.0.0.1');
        $this->manager->removeDeviceByKey($device1->getDeviceKey(), 'android');
        $this->clearEm();
        $this->assertEquals(0, count($this->rep->findBy(['mobileDeviceId' => $device1->getMobileDeviceId()])));
    }

    public function testManagerShouldRemoveDesktopDevicesByUser()
    {
        $this->mockBackgroundCheckScheduler(6);
        $this->manager->addDevice($this->user->getUserid(), MobileDevice::getTypeName(MobileDevice::TYPE_CHROME), 'chrome', 'en', 'web:personal', '127.0.0.1');
        $this->manager->addDevice($this->user->getUserid(), MobileDevice::getTypeName(MobileDevice::TYPE_SAFARI), 'safari', 'en', 'web:personal', '127.0.0.1');
        $this->manager->addDevice($this->user->getUserid(), MobileDevice::getTypeName(MobileDevice::TYPE_FIREFOX), 'firefox', 'en', 'web:personal', '127.0.0.1');
        $device1 = $this->manager->addDevice($this->user->getUserid(), MobileDevice::getTypeName(MobileDevice::TYPE_ANDROID), self::DEVICE_KEY_1, 'en', '1.1.1', '127.0.0.1');
        $device2 = $this->manager->addDevice($this->user->getUserid(), MobileDevice::getTypeName(MobileDevice::TYPE_IOS), self::DEVICE_KEY_2, 'en', '1.1.1', '127.0.0.1');
        $this->manager->removeDesktopDevicesByUser($this->user);
        $this->clearEm();
        $this->assertEquals(2, count($this->rep->findBy(['userId' => $this->user->getUserid()])));
        $this->db->seeInDatabase('MobileDevice', ['DeviceKey' => $device1->getDeviceKey()]);
        $this->db->seeInDatabase('MobileDevice', ['DeviceKey' => $device2->getDeviceKey()]);
    }

    public function testManagerShouldRenewDeviceKey()
    {
        $this->mockBackgroundCheckScheduler(6);
        $device1 = $this->manager->addDevice($this->user->getUserid(), 'android', self::DEVICE_KEY_1, 'en', '1.1.1', '127.0.0.1');
        $this->manager->renewDeviceKeyByNotification(new Notification('', [], $device1), self::DEVICE_KEY_2);
        $this->clearEm();
        $this->assertEquals(0, count($this->rep->findBy(['deviceType' => MobileDevice::TYPE_ANDROID, 'deviceKey' => self::DEVICE_KEY_1])));
        $this->assertEquals(1, count($this->rep->findBy(['deviceType' => MobileDevice::TYPE_ANDROID, 'deviceKey' => self::DEVICE_KEY_2])));
        $this->clearEm();
        $device2 = $this->manager->addDevice($this->user->getUserid(), 'android', self::DEVICE_KEY_1, 'en', '1.1.1', '127.0.0.1');
        $this->manager->renewDeviceKeyByNotification(new Notification('', [], $device2), self::DEVICE_KEY_2);
        $this->clearEm();
        $this->assertEquals(0, count($this->rep->findBy(['deviceType' => MobileDevice::TYPE_ANDROID, 'deviceKey' => self::DEVICE_KEY_1])));
        $this->assertEquals(1, count($this->rep->findBy(['deviceType' => MobileDevice::TYPE_ANDROID, 'deviceKey' => self::DEVICE_KEY_2])));
    }

    public function testManagerShouldUpdateDeviceInfo()
    {
        $this->mockBackgroundCheckScheduler(1);
        $device1 = $this->manager->addDevice($this->user->getUserid(), 'android', self::DEVICE_KEY_1, 'en', '1.1.1', '127.0.0.1');
        $this->manager->updateDeviceInfo($this->user->getUserid(), $device1->getMobileDeviceId(), 'en', '1.1.9999');
        $this->em->refresh($device1);
        $this->assertEquals('en', $device1->getLang());
        $this->assertEquals('1.1.9999', $device1->getAppVersion());
        $this->manager->updateDeviceInfo($this->user->getUserid(), $device1->getMobileDeviceId(), 'ru', '2.1.9999');
        $this->em->refresh($device1);
        $this->assertEquals('ru', $device1->getLang());
        $this->assertEquals('2.1.9999', $device1->getAppVersion());
    }

    public function testWebOnlyLastBrowser()
    {
        $this->mockBackgroundCheckScheduler(2);
        $device1 = $this->manager->addDevice($this->user->getUserid(), MobileDevice::getTypeName(MobileDevice::TYPE_CHROME), 'chrome1', 'en', 'web:personal', '127.0.0.1');
        $device2 = $this->manager->addDevice($this->user->getUserid(), MobileDevice::getTypeName(MobileDevice::TYPE_CHROME), 'chrome2', 'en', 'web:personal', '127.0.0.1');
        $this->assertNotEquals($device1->getMobileDeviceId(), $device2->getMobileDeviceId());
        $this->assertEquals(1, $this->db->query("select count(*) from MobileDevice where UserID = ?", [$this->user->getUserid()])->fetchColumn());
    }

    public function testMobileDeviceExist()
    {
        $id = $this->db->haveInDatabase('MobileDevice', [
            'UserID' => $this->user->getId(),
            'DeviceKey' => $this->aw->grabRandomString(30),
            'DeviceType' => MobileDevice::TYPE_ANDROID,
            'Lang' => 'en',
        ]);
        $this->assertTrue($this->manager->deviceExists($id));
    }

    public function testMobileDeviceDoesNotExist()
    {
        $this->assertFalse($this->manager->deviceExists(9999999999));
    }

    protected function clearEm()
    {
        $this->em->clear('AwardWallet\\MainBundle\\Entity\\MobileDevice');
    }

    private function mockBackgroundCheckScheduler(int $expectedCalls)
    {
        $this->mockService(BackgroundCheckScheduler::class, $this->makeEmpty(BackgroundCheckScheduler::class, [
            'onUserPushDeviceChanged' => Expected::exactly($expectedCalls),
        ]));
    }
}
