<?php

namespace AwardWallet\Tests\Unit\Timeline;

use AwardWallet\MainBundle\Timeline\Formatter\ItemFormatterInterface;
use AwardWallet\MainBundle\Timeline\Item;
use AwardWallet\MainBundle\Timeline\Manager;
use AwardWallet\MainBundle\Timeline\QueryOptions;
use AwardWallet\Tests\Unit\BaseUserTest;
use Codeception\Module\Aw;

use function PHPUnit\Framework\assertEquals;

/**
 * @group frontend-unit
 */
class DisplayPlanTest extends BaseUserTest
{
    /**
     * @var Manager
     */
    private $manager;

    public function _before()
    {
        parent::_before();
        $this->manager = $this->container->get(Manager::class);
    }

    public function testCreateOnEmpty()
    {
        $this->createSimpleData();

        $items = $this->manager->query((new QueryOptions())->setFormat(ItemFormatterInterface::DESKTOP)->setUser($this->user));

        $types = array_map(function (Item\ItemInterface $item) { return get_class($item); }, $items);
        $this->assertEquals([
            Item\PlanStart::class,
            Item\Date::class,
            Item\Event::class,
            Item\PlanEnd::class,
        ], $types);
    }

    public function testDisabledPlans()
    {
        $this->createSimpleData();

        $items = $this->manager->query(
            (new QueryOptions())
                ->setFormat(ItemFormatterInterface::DESKTOP)
                ->setShowPlans(false)
                ->setUser($this->user)
        );

        $types = array_map(function (Item\ItemInterface $item) { return get_class($item); }, $items);

        assertEquals([
            Item\Date::class,
            Item\Event::class,
        ], $types);
    }

    public function _after()
    {
        $this->manager;

        parent::_after(); // TODO: Change the autogenerated stub
    }

    protected function createSimpleData()
    {
        $startTime = strtotime("tomorrow");
        $this->db->haveInDatabase("Restaurant", [
            "UserID" => $this->user->getId(),
            "ConfNo" => 'Rest1',
            "Name" => "Birthday",
            "Address" => Aw::GMT_AIRPORT,
            "StartDate" => date("Y-m-d H:i:s", $startTime),
            "EndDate" => date("Y-m-d H:i:s", $startTime + SECONDS_PER_HOUR * 5),
        ]);
        $this->db->haveInDatabase("Plan", [
            "UserID" => $this->user->getId(),
            "Name" => "Intersection1",
            "StartDate" => date("Y-m-d H:i:s", $startTime - SECONDS_PER_HOUR * 1),
            "EndDate" => date("Y-m-d H:i:s", $startTime + SECONDS_PER_HOUR),
        ]);
    }
}
