<?php

namespace AwardWallet\MainBundle\Service\OneCard;

use AwardWallet\MainBundle\Globals\AccountList\Mapper\DesktopListMapper;

class OneCardMapper extends DesktopListMapper
{
    protected const DATA_TEMPLATE = [
        'ID' => null,
        'FID' => null,
        'UserName' => null,
        'UserAgentID' => null,
        'ProviderID' => null,
        'ProviderName' => null,
        'TableName' => null,
        'State' => null,
        'isCustom' => null,
        'AccountOwner' => null,
        'Kind' => null,
        'DisplayName' => null,
        'DisplayNameFormated' => null,
        'SavePassword' => null,
        'Balance' => null,
        'BalanceRaw' => null,
        'TotalBalance' => null,
        'LastChange' => null,
        'LastChangeRaw' => null,
        'ChangesConfirmed' => null,
        'ChangedText' => null,
        'LastChangeDate' => null,
        'LastChangeDateTs' => null,
        'ChangeCount' => null,
        'ChangedOverPeriodPositive' => null,
        'AllianceAlias' => null,
        'AllianceIcon' => null,
        'AllianceLevel' => null,
        'EliteStatuses' => null,
        'EliteLevelsCount' => null,
        'Elitism' => null,
        'Rank' => null,
        'ExpirationDate' => null,
        'ExpirationDateYMD' => null,
        'ExpirationDateTs' => null,
        'ExpirationDateTip' => null,
        'ExpirationKnown' => null,
        'ExpirationState' => null,
        'ExpirationStateType' => null,
        'ExpirationMode' => null,
        'ExpirationModeType' => null,
        'ExpirationDetails' => null,
        'ErrorCode' => null,
        'AutoLogin' => null,
        'LoginURL' => null,
        'DisableClientPasswordAccess' => null,
        'Goal' => null,
        'GoalProgress' => null,
        'GoalIndicators' => null,
        'UpdateDate' => null,
        'UpdateDateTs' => null,
        'SubAccountsArray' => null,
        'Access' => null,
        'Shares' => null,
        'ProgramMessage' => null,
        'ProviderCode' => null,
        'CheckInBrowser' => null,
        // Login cell in account/list (First line, last line)
        'LoginFieldFirst' => null,
        'LoginFieldLast' => null,
        // Status (from main properties)
        'AccountStatus' => null,
        'ConnectedAccount' => null,
        'StatusIndicators' => null,
        'StateBar' => null,
        'LastDurationWithoutPlans' => null,
        'LastDurationWithPlans' => null,
        'HasCurrentTrips' => null,
        'IsActiveTab' => null,
        'SuccessCheckDateTs' => null,
        'SuccessCheckDateYMD' => null,
        'UserEmail' => null,
        'FamilyMemberName' => null,
        'EmailDate' => null,
        'EmailDateTs' => null,
        'CanSavePassword' => null,
        'CanReceiveEmail' => null,
        'HistoryName' => null,
        'CanCheck' => null,
        'IsActive' => null,
        'IsShareable' => null,
        'Disabled' => null,
        'DetectedCards' => null,
        'BackgroundCheck' => null,
        'KeyWords' => null,
        'CardImages' => [
            'ProviderID' => null,
            'AccountID' => null,
            'SubAccountID' => null,
            'CardImageID' => null,
            'UserID' => null,
            'ProviderCouponID' => null,
            'Kind' => null,
            'Width' => null,
            'Height' => null,
            'FileName' => null,
            'FileSize' => null,
            'Format' => null,
            'UploadDate' => null,
            'StorageKey' => null,
        ],
        'DocumentImages' => null,
        'BackgroundCheckState' => null,
        'BalanceWatchExpirationDate' => null,
        'BalanceWatchStartDate' => null,
        'CustomFields' => null,
        'PwnedTimes' => null,
    ];
}
