<?php

namespace AwardWallet\Tests\Unit;

class AaTest extends BaseTest
{
    /**
     * @var \AaNewAPIChecker
     */
    private $checker;

    public function _before()
    {
        $this->markTestSkipped('proxy required');

        require_once __DIR__ . '/../../web/engine/aa/AaNewAPIChecker.php';
        $this->checker = new \AaNewAPIChecker();
        $this->checker->http = new \HttpBrowser('none', new \CurlDriver());
        $this->checker->AccountFields = [
            'Login' => 'blah',
            'Login2' => '',
            'Pass' => 'heh',
        ];
    }

    public function testInvalidLogin()
    {
        $this->expectException('CheckException');
        $this->expectExceptionMessage('Member Account Not Found');
        $this->checker->Parse();
    }

    public function testInvalidPassword()
    {
        $this->expectException('CheckException');
        $this->expectExceptionMessage('Incorrect password');
        $this->checker->Login();
    }

    public function testValidLogin()
    {
        $this->checker->AccountFields['Login'] = '1L211P4'; // veresch
        $this->checker->Parse();
        $this->assertEquals(ACCOUNT_CHECKED, $this->checker->ErrorCode);
        $this->assertEquals("1L211P4", $this->checker->Properties['Number']);
        $this->assertEquals("Member", $this->checker->Properties['Status']);
        $this->assertEquals("Alexi Vereschaga", $this->checker->Properties['Name']);
        $this->assertNotEmpty($this->checker->Properties['AccountExpirationDate']);
        $this->assertGreaterThanOrEqual(0, $this->checker->Balance);
    }

    public function testParseItinerary()
    {
        $this->checker->AccountFields['Login'] = '843RHB0';
        $it = $this->checker->parseItinerary("GQGRWB");
        $this->assertEquals("PURCHASED", $it["Status"]);
        $this->assertEquals("MUC", $it["TripSegments"][0]["DepCode"]);
        $this->assertEquals("LHR", $it["TripSegments"][0]["ArrCode"]);
    }

    protected function _after()
    {
        $this->checker = null;

        parent::_after(); // TODO: Change the autogenerated stub
    }
}
