<?php

namespace AwardWallet\Tests\Unit;

use AwardWallet\MainBundle\Globals\ApiVersioning\ApiVersioningService;
use AwardWallet\MainBundle\Globals\ApiVersioning\VersionsProviderInterface;
use Codeception\Test\Unit;
use Herrera\Version\Parser;

/**
 * @group frontend-unit
 */
class ApiVersioningServiceTest extends BaseTest
{
    /**
     * @var ApiVersioningService
     */
    protected $svc;

    public function _before()
    {
        parent::_before();
        $this->svc = new ApiVersioningService();
    }

    public function testReadWriteVersion()
    {
        $version = Parser::toVersion('0.0.1');
        $this->svc->setVersion($version);
        $this->assertEquals($version, $this->svc->getVersion());

        $this->svc->setVersionsProvider(new TestVersionsProvider());

        $this->assertFalse($this->svc->supports('feature'));
        $this->assertTrue($this->svc->supports('feature0'));
        $this->assertFalse($this->svc->supports('feature1'));
        $this->assertFalse($this->svc->supports('feature2'));

        $this->svc->setVersion(Parser::toVersion('0.1.2'));
        $this->assertTrue($this->svc->supports('feature0'));
        $this->assertTrue($this->svc->supports('feature1'));
        $this->assertFalse($this->svc->supports('feature2'));

        $this->svc->setVersion(Parser::toVersion('1.0.11'));
        $this->assertTrue($this->svc->supports('feature0'));
        $this->assertTrue($this->svc->supports('feature1'));
        $this->assertTrue($this->svc->supports('feature2'));
    }

    protected function _after()
    {
        $this->svc = null;

        parent::_after(); // TODO: Change the autogenerated stub
    }
}

class TestVersionsProvider implements VersionsProviderInterface
{
    /**
     * @return array[Version => string[]]
     */
    public function getVersions()
    {
        return [
            [Parser::toVersion('0.0.1'), ['feature0']],
            [Parser::toVersion('0.1.0'), ['feature0', 'feature1']],
            [Parser::toVersion('1.0.0'), ['feature0', 'feature1', 'feature2']],
        ];
    }
}
