<?php

namespace AwardWallet\Tests\Unit;

use AwardWallet\MainBundle\Controller\ContactUsController;

/**
 * @group frontend-unit
 */
class ContactUsTest extends BaseContainerTest
{
    private $strings = [
        "cancel my account",
        "cancel the account",
        "delete my account",
        "close my account",
        "close the account",
        "my account deleted",
        "my account closed",
        "delete the AwardWallet account",
        "delete the Award Wallet account",
        "close the AwardWallet account",
        "close the Award Wallet account",
        "cancel the AwardWallet account",
        "cancel the Award Wallet account",
        "deactivate my awardwallet.com account",
        "deactivate my awardwallet account",
        "deactivate my award wallet account",
        "deactivate my account",
        "cancel my awardwallet account",
        "cancel my award wallet account",
        "delete my AwardWallet account",
        "delete my Award Wallet account",
        "close my AwardWallet account",
        "close my Award Wallet account",
        "terminate my awardwallet.com account",
        "terminate my awardwallet account",
        "terminate my award wallet account",
        "terminate my account",
        "cancel my acct",
        "cancel the acct",
        "delete my acct",
        "close my acct",
        "close the acct",
        "my acct deleted",
        "my acct closed",
        "delete the AwardWallet acct",
        "delete the Award Wallet acct",
        "close the AwardWallet acct",
        "close the Award Wallet acct",
        "cancel the AwardWallet acct",
        "cancel the Award Wallet acct",
        "deactivate my awardwallet.com acct",
        "deactivate my awardwallet acct",
        "deactivate my award wallet acct",
        "deactivate my acct",
        "cancel my awardwallet acct",
        "cancel my award wallet acct",
        "delete my AwardWallet acct",
        "delete my Award Wallet acct",
        "close my AwardWallet acct",
        "close my Award Wallet acct",
        "terminate my awardwallet.com acct",
        "terminate my awardwallet acct",
        "terminate my award wallet acct",
        "terminate my acct",
        "cancel my accnt",
        "cancel the accnt",
        "delete my accnt",
        "close my accnt",
        "close the accnt",
        "my accnt deleted",
        "my accnt closed",
        "delete the AwardWallet accnt",
        "delete the Award Wallet accnt",
        "close the AwardWallet accnt",
        "close the Award Wallet accnt",
        "cancel the AwardWallet accnt",
        "cancel the Award Wallet accnt",
        "deactivate my awardwallet.com accnt",
        "deactivate my awardwallet accnt",
        "deactivate my award wallet accnt",
        "deactivate my accnt",
        "cancel my awardwallet accnt",
        "cancel my award wallet accnt",
        "delete my AwardWallet accnt",
        "delete my Award Wallet accnt",
        "close my AwardWallet accnt",
        "close my Award Wallet accnt",
        "terminate my awardwallet.com accnt",
        "terminate my awardwallet accnt",
        "terminate my award wallet accnt",
        "terminate my accnt",
        "cancel my profile",
        "cancel the profile",
        "delete my profile",
        "close my profile",
        "close the profile",
        "my profile deleted",
        "my profile closed",
        "delete the AwardWallet profile",
        "delete the Award Wallet profile",
        "close the AwardWallet profile",
        "close the Award Wallet profile",
        "cancel the AwardWallet profile",
        "cancel the Award Wallet profile",
        "deactivate my awardwallet.com profile",
        "deactivate my awardwallet profile",
        "deactivate my award wallet profile",
        "deactivate my profile",
        "cancel my awardwallet profile",
        "cancel my award wallet profile",
        "delete my AwardWallet profile",
        "delete my whole profile",
        "delete my Award Wallet profile",
        "close my AwardWallet profile",
        "close my Award Wallet profile",
        "terminate my awardwallet.com profile",
        "terminate my awardwallet profile",
        "terminate my award wallet profile",
        "terminate my profile",
        "cancel my membership",
        "close my membership",
        "my membership deleted",
        "my membership closed",
        "delete the AwardWallet membership",
        "delete the Award Wallet membership",
        "close the AwardWallet membership",
        "close the Award Wallet membership",
        "cancel the AwardWallet membership",
        "cancel the Award Wallet membership",
        "deactivate my awardwallet.com membership",
        "deactivate my awardwallet membership",
        "deactivate my award wallet membership",
        "deactivate my membership",
        "cancel my awardwallet membership",
        "cancel my award wallet membership",
        "delete my AwardWallet membership",
        "delete my Award Wallet membership",
        "close my AwardWallet membership",
        "close my Award Wallet membership",
        "terminate my awardwallet.com membership",
        "terminate my awardwallet membership",
        "terminate my award wallet membership",
        "terminate my membership",
        "cancel my AW accnt",
        "cancel the AW  accnt",
        "delete my AW accnt",
        "close my AW accnt",
        "close the AW accnt",
        "my AW accnt closed",
        "delete the AW accnt",
        "cancel the AW accnt",
        "deactivate my AW accnt",
        "terminate my AW accnt",
        "cancel my AW account",
        "cancel the AW  account",
        "delete my AW account",
        "close my AW account",
        "close the AW account",
        "my AW account closed",
        "delete the AW account",
        "cancel the AW account",
        "deactivate my AW account",
        "terminate my AW account",
        "cancel my AW profile",
        "cancel the AW  profile",
        "delete my AW profile",
        "close my AW profile",
        "close the AW profile",
        "my AW profile closed",
        "delete the AW profile",
        "cancel the AW profile",
        "deactivate my AW profile",
        "terminate my AW profile",
        "cancel my AW user",
        "cancel the AW  user",
        "delete my AW user",
        "close my AW user",
        "close the AW user",
        "my AW user closed",
        "delete the AW user",
        "cancel the AW user",
        "deactivate my AW user",
        "terminate my AW user",
        "close/disable my account",
        "I would like to cancel this account",
        "delete my entire account",
    ];

    public function testRegexAccountDeleting()
    {
        $regex = "/(" . implode(")|(", ContactUsController::ACCOUNT_REMOVE_PHRASES) . ")/ims";

        foreach ($this->strings as $string) {
            $this->assertMatchesRegularExpression($regex, $string);
        }
    }
}
