<?php

namespace AwardWallet\Tests\Unit;

use AwardWallet\MainBundle\Entity\Account;
use AwardWallet\MainBundle\Entity\Provider;
use AwardWallet\MainBundle\Entity\Providercoupon;
use AwardWallet\MainBundle\Entity\Useragent;
use AwardWallet\MainBundle\Entity\Usr;
use AwardWallet\MainBundle\Manager\AccountManager;
use AwardWallet\MainBundle\Service\Cache;
use AwardWallet\MainBundle\Service\Counter;
use AwardWallet\Tests\Modules\DbBuilder\Account as DbAccount;
use AwardWallet\Tests\Modules\DbBuilder\ProviderCoupon as DbProviderCoupon;
use AwardWallet\Tests\Modules\DbBuilder\User as DbUser;
use AwardWallet\Tests\Modules\DbBuilder\UserAgent as DbUserAgent;

/**
 * @group frontend-unit
 */
class CounterTest extends BaseContainerTest
{
    /**
     * @var Counter
     */
    private $counter;

    /**
     * @var \Memcached
     */
    private $cache;

    /**
     * @var Cache\Invalidator
     */
    private $invalidator;

    /**
     * @var AccountManager
     */
    private $accountManager;

    /**
     * @var Provider
     */
    private $provider;

    /**
     * @var Usr
     */
    private $firstUser;

    /**
     * @var Usr
     */
    private $secondUser;

    public function _before()
    {
        parent::_before();
        $this->counter = $this->container->get(Counter::class);
        $this->cache = $this->container->get(\Memcached::class);
        $this->invalidator = $this->container->get(Cache\Invalidator::class);
        $this->accountManager = $this->container->get(AccountManager::class);

        // provider
        $providerRep = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Provider::class);
        $providerId = $this->aw->createAwProvider(null, null, [
            'State' => PROVIDER_ENABLED,
        ]);
        $this->provider = $providerRep->find($providerId);

        // add first user
        $this->firstUser = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Usr::class)->find(
            $this->aw->createAwUser('counter' . $this->aw->grabRandomString(5), 'testpass', [], false)
        );

        // add second user
        $this->secondUser = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Usr::class)->find(
            $this->aw->createAwUser('counter2' . $this->aw->grabRandomString(5), 'testpass', [], false)
        );

        // connection
        $ua1 = new Useragent();
        $ua1->setAgentid($this->firstUser);
        $ua1->setClientid($this->secondUser);
        $ua1->setAccesslevel(ACCESS_WRITE);
        $ua1->setIsapproved(1);
        $this->em->persist($ua1);

        $ua2 = new Useragent();
        $ua2->setAgentid($this->secondUser);
        $ua2->setClientid($this->firstUser);
        $ua2->setAccesslevel(ACCESS_WRITE);
        $ua2->setIsapproved(1);
        $this->em->persist($ua2);

        $ua3 = new Useragent();
        $ua3->setAgentid($this->firstUser);
        $ua3->setClientid(null);
        $ua3->setFirstname('Family')->setLastname('Member');
        $ua3->setAccesslevel(ACCESS_WRITE);
        $ua3->setIsapproved(true);
        $this->em->persist($ua3);
        $this->em->flush();
    }

    public function _after()
    {
        $this->em->remove($this->firstUser);
        $this->em->remove($this->secondUser);

        $this->accountManager =
        $this->invalidator =
        $this->cache =
        $this->counter =
        $this->provider =
        $this->firstUser =
        $this->secondUser = null;

        parent::_after(); // TODO: Change the autogenerated stub
    }

    public function testEmptyUser()
    {
        $user = $this->firstUser;
        $userID = $user->getUserid();
        $allCacheKey = Cache\Tags::getAllAccountsKey($userID);
        $userCacheKey = Cache\Tags::getUserAccountsKey($userID);
        $this->assertFalse(unserialize($this->cache->get($allCacheKey)));
        $this->assertEquals(0, $this->counter->getTotalAccounts($userID));
        $this->assertEquals(0, $this->counter->getTotalAccounts($userID, 0));
        $this->assertEquals(0, unserialize($this->cache->get($allCacheKey)['data']));
        $this->assertEquals(0, unserialize($this->cache->get($userCacheKey)['data']));
        $this->hasAccountsAndCoupons($user, 'all', 0);
    }

    public function testAfterAddingAccount()
    {
        $account = $this->createAccount($this->provider, $this->firstUser, '123');
        $user = $account->getUserid();
        $userID = $user->getUserid();
        $this->em->persist($account);
        $this->em->flush();

        $allCacheKey = Cache\Tags::getAllAccountsKey($userID);
        $userCacheKey = Cache\Tags::getUserAccountsKey($userID);
        $this->assertEquals(1, $this->counter->getTotalAccounts($userID));
        $this->assertEquals(1, $this->counter->getTotalAccounts($userID, 0));
        $this->assertEquals(1, unserialize($this->cache->get($allCacheKey)['data']));
        $this->assertEquals(1, unserialize($this->cache->get($userCacheKey)['data']));
        $this->hasAccountsAndCoupons($user, null, 1);
        $this->hasAccounts($user, null, 1);
        $this->hasCoupons($user, null, 0);
    }

    public function testAfterAddingCoupon()
    {
        $account = $this->createProviderCoupon($this->firstUser, "Program", PROVIDER_KIND_AIRLINE, "Test Desc");
        $user = $account->getUserid();
        $userID = $user->getUserid();
        $this->em->persist($account);
        $this->em->flush();

        $allCacheKey = Cache\Tags::getAllAccountsKey($userID);
        $userCacheKey = Cache\Tags::getUserAccountsKey($userID);
        $this->assertEquals(1, $this->counter->getTotalAccounts($userID));
        $this->assertEquals(1, $this->counter->getTotalAccounts($userID, 0));
        $this->assertEquals(1, unserialize($this->cache->get($allCacheKey)['data']));
        $this->assertEquals(1, unserialize($this->cache->get($userCacheKey)['data']));
        $this->hasAccountsAndCoupons($user, null, 1);
        $this->hasAccounts($user, null, 0);
        $this->hasCoupons($user, null, 1);
    }

    public function testAfterChangeOwnerCoupon()
    {
        $coupon = $this->createProviderCoupon($this->firstUser, "Program", PROVIDER_KIND_AIRLINE, "Test Desc");
        $this->em->persist($coupon);
        $this->em->flush();

        $userID = $this->firstUser->getUserid();
        $userID2 = $this->secondUser->getUserid();
        $this->assertEquals(1, $this->counter->getTotalAccounts($userID));
        $this->assertEquals(0, $this->counter->getTotalAccounts($userID2));

        $ua = $this->firstUser->findUserAgent($this->secondUser->getUserid());
        $this->container->get("aw.manager.user_manager")->loadToken($this->firstUser, false);
        $this->accountManager->setOwner($coupon, $this->secondUser, $ua);
        $this->em->flush();

        $uaCacheKey = Cache\Tags::getUserAccountsKey($userID, $ua->getUseragentid());
        $allCacheKey = Cache\Tags::getAllAccountsKey($userID);
        $userCacheKey = Cache\Tags::getUserAccountsKey($userID);
        $this->assertEquals(1, $this->counter->getTotalAccounts($userID));
        $this->assertEquals(0, $this->counter->getTotalAccounts($userID, 0));
        $this->assertEquals(1, $this->counter->getTotalAccounts($userID, $ua->getUseragentid()));
        $this->assertEquals(1, $this->counter->getTotalAccounts($userID2));
        $this->assertEquals(1, unserialize($this->cache->get($allCacheKey)['data']));
        $this->assertEquals(0, unserialize($this->cache->get($userCacheKey)['data']));
        $this->assertEquals(1, unserialize($this->cache->get($uaCacheKey)['data']));
        $this->hasAccountsAndCoupons($this->firstUser, null, 0);
        $this->hasAccounts($this->firstUser, $ua->getUseragentid(), 0);
        $this->hasCoupons($this->firstUser, $ua->getUseragentid(), 1);
    }

    public function testAfterChangeOwnerAccount()
    {
        $account = $this->createAccount($this->provider, $this->firstUser, '123');
        $this->em->persist($account);
        $this->em->flush();

        $userID = $this->firstUser->getUserid();
        $userID2 = $this->secondUser->getUserid();
        $this->assertEquals(1, $this->counter->getTotalAccounts($userID));
        $this->assertEquals(0, $this->counter->getTotalAccounts($userID2));

        $ua = $this->firstUser->findUserAgent($this->secondUser->getUserid());
        $this->container->get("aw.manager.user_manager")->loadToken($this->firstUser, false);
        $this->accountManager->setOwner($account, $this->secondUser, $ua);
        $this->em->flush();

        $uaCacheKey = Cache\Tags::getUserAccountsKey($userID, $ua->getUseragentid());
        $allCacheKey = Cache\Tags::getAllAccountsKey($userID);
        $userCacheKey = Cache\Tags::getUserAccountsKey($userID);
        $this->assertEquals(1, $this->counter->getTotalAccounts($userID));
        $this->assertEquals(0, $this->counter->getTotalAccounts($userID, 0));
        $this->assertEquals(1, $this->counter->getTotalAccounts($userID, $ua->getUseragentid()));
        $this->assertEquals(1, $this->counter->getTotalAccounts($userID2));
        $this->assertEquals(1, unserialize($this->cache->get($allCacheKey)['data']));
        $this->assertEquals(0, unserialize($this->cache->get($userCacheKey)['data']));
        $this->assertEquals(1, unserialize($this->cache->get($uaCacheKey)['data']));
        $this->hasAccountsAndCoupons($this->firstUser, null, 0);
        $this->hasAccounts($this->firstUser, $ua->getUseragentid(), 1);
        $this->hasCoupons($this->firstUser, $ua->getUseragentid(), 0);
    }

    public function testSetOwner()
    {
        $userID = $this->firstUser->getUserid();
        $allCacheKey = Cache\Tags::getAllAccountsKey($userID);
        $ua = $this->firstUser->findUserAgent($this->secondUser->getUserid());
        $uaCacheKey = Cache\Tags::getUserAccountsKey($userID, $ua->getUseragentid());
        $this->assertEquals(0, $this->counter->getTotalAccounts($userID));
        $this->assertEquals(0, unserialize($this->cache->get($allCacheKey)['data']));

        $account = $this->createAccount($this->provider, $this->firstUser, '123');
        $this->container->get("aw.manager.user_manager")->loadToken($this->firstUser, false);
        $this->accountManager->setOwner($account, $this->secondUser, $ua);
        $this->em->persist($account);
        $this->em->flush();
        $this->assertEquals(1, $this->counter->getTotalAccounts($userID));
        $this->assertEquals(1, $this->counter->getTotalAccounts($userID, $ua->getUseragentid()));
        $this->assertEquals(1, unserialize($this->cache->get($allCacheKey)['data']));
        $this->assertEquals(1, unserialize($this->cache->get($uaCacheKey)['data']));
    }

    public function testFamilyMember()
    {
        $members = $this->firstUser->getFamilyMembers();
        $this->assertNotEmpty($members);
        $userID = $this->firstUser->getUserid();
        $familyMember = $members[0];
        $account = $this->createAccount($this->provider, $this->firstUser, '1234');
        $this->container->get("aw.manager.user_manager")->loadToken($this->firstUser, false);
        $this->accountManager->setOwner($account, $this->firstUser, $familyMember);
        $this->em->persist($account);
        $this->em->flush();

        $this->assertEquals(1, $this->counter->getTotalAccounts($userID));
        $this->assertEquals(0, $this->counter->getTotalAccounts($userID, 0));
        $this->assertEquals(1, $this->counter->getTotalAccounts($userID, $familyMember->getUseragentid()));
        $this->hasAccountsAndCoupons($this->firstUser, 'all', 1);
        $this->hasAccounts($this->firstUser, $familyMember->getUseragentid(), 1);
        $this->hasCoupons($this->firstUser, $familyMember->getUseragentid(), 0);

        $coupon = $this->createProviderCoupon($this->firstUser, "Program", PROVIDER_KIND_AIRLINE, "Test Desc");
        $this->em->persist($coupon);
        $this->em->flush();
        $this->assertEquals(2, $this->counter->getTotalAccounts($userID));
        $this->assertEquals(1, $this->counter->getTotalAccounts($userID, 0));
        $this->assertEquals(1, $this->counter->getTotalAccounts($userID, $familyMember->getUseragentid()));
    }

    public function testAfterRemove()
    {
        $userID = $this->firstUser->getUserid();
        $account = $this->createAccount($this->provider, $this->firstUser, '123');
        $this->em->persist($account);
        $this->em->flush();
        $this->assertEquals(1, $this->counter->getTotalAccounts($userID));
        $this->em->remove($account);
        $this->em->flush();
        $this->assertEquals(0, $this->counter->getTotalAccounts($userID));
        $coupon = $this->createProviderCoupon($this->firstUser, "Program", PROVIDER_KIND_AIRLINE, "Test Desc");
        $this->em->persist($coupon);
        $this->em->flush();
        $this->assertEquals(1, $this->counter->getTotalAccounts($userID));
        $this->em->remove($coupon);
        $this->em->flush();
        $this->assertEquals(0, $this->counter->getTotalAccounts($userID));
    }

    public function testAfterRemoveSharing()
    {
        $ua = $this->firstUser->findUserAgent($this->secondUser->getUserid());
        $account = $this->createAccount($this->provider, $this->firstUser, '123');
        $this->container->get("aw.manager.user_manager")->loadToken($this->firstUser, false);
        $this->accountManager->setOwner($account, $this->secondUser, $ua);
        $this->em->persist($account);
        $this->em->flush();
        $this->assertEquals(1, $this->counter->getTotalAccounts($this->firstUser->getUserid()));
        $this->assertEquals(1, $this->counter->getTotalAccounts($this->secondUser->getUserid()));

        $this->em->remove($account);
        $this->em->flush();
        $this->assertEquals(0, $this->counter->getTotalAccounts($this->firstUser->getUserid()));
        $this->assertEquals(0, $this->counter->getTotalAccounts($this->secondUser->getUserid()));
    }

    public function testAfterChangeStateProvider()
    {
        $account = $this->createAccount($this->provider, $this->firstUser, '123');
        $this->em->persist($account);
        $this->em->flush();
        $this->assertEquals(1, $this->counter->getTotalAccounts($this->firstUser->getUserid()));
        $this->provider->setState(PROVIDER_DISABLED);
        $this->em->flush($this->provider);
        $this->assertEquals(0, $this->counter->getTotalAccounts($this->firstUser->getUserid()));
        $this->provider->setState(PROVIDER_ENABLED);
        $this->em->flush($this->provider);
        $this->assertEquals(1, $this->counter->getTotalAccounts($this->firstUser->getUserid()));
    }

    public function testOldConnection()
    {
        global $Connection;
        $account = $this->createAccount($this->provider, $this->firstUser, '123');
        $this->em->persist($account);
        $this->em->flush();
        $this->assertEquals(1, $this->counter->getTotalAccounts($this->firstUser->getUserid()));
        $Connection->Delete('Account', $account->getAccountid());
        $this->assertEquals(0, $this->counter->getTotalAccounts($this->firstUser->getUserid()));
    }

    public function testProviderStateHook()
    {
        $account = $this->createAccount($this->provider, $this->firstUser, '123');
        $this->em->persist($account);
        $this->em->flush();
        $userID = $this->firstUser->getUserid();
        $allCacheKey = Cache\Tags::getAllAccountsKey($userID);

        $this->assertEquals(false, $this->getCacheExtended($allCacheKey, null, $casTokenBefore));
        $this->invalidator->providerStateChanged();
        $this->assertEquals(false, $this->getCacheExtended($allCacheKey, null, $casTokenAfter));
        $this->assertEquals($casTokenBefore, $casTokenAfter);
        $this->counter->getTotalAccounts($userID);
        $this->assertEquals(1, unserialize($this->getCacheExtended($allCacheKey, null, $casTokenAfter2)['data']));
        $this->assertNotEquals($casTokenAfter, $casTokenAfter2);
    }

    /**
     * @dataProvider attachCouponToAccountProvider
     */
    public function testAttachedAccountToCoupon(
        DbAccount $account,
        DbProviderCoupon $providerCoupon,
        array $expected
    ) {
        // invalidate cache via hook
        $this->invalidator->providerStateChanged();
        $this->dbBuilder->makeAccount($account);
        $this->dbBuilder->makeProviderCoupon($providerCoupon);

        /**
         * @var DbUser $user
         * @var int $expectedCount
         */
        foreach ($expected as [$user, $expectedCount]) {
            $this->assertEquals($expectedCount, $this->counter->getTotalAccounts($user->getId()));
        }
    }

    public function attachCouponToAccountProvider(): array
    {
        return [
            /**
             * The owner of the account and the coupon is one user who shared them with another user.
             */
            [
                (new DbAccount($user1 = new DbUser()))
                    ->shareTo($ua = new DbUserAgent($user2 = new DbUser(), $user1)),
                (new DbProviderCoupon('Test Provider Coupon', 500, $user1))
                    ->shareTo($ua),
                [
                    [$user1, 2],
                    [$user2, 2],
                ],
            ],

            /**
             * The owner of the account and the coupon is one user who shared them with another user.
             * The coupon is attached to the account.
             */
            [
                $account = (new DbAccount($user1 = new DbUser()))
                    ->shareTo($ua = new DbUserAgent($user2 = new DbUser(), $user1)),
                (new DbProviderCoupon('Test Provider Coupon', 500, $user1))
                    ->shareTo($ua)
                    ->setAccount($account),
                [
                    [$user1, 1],
                    [$user2, 1],
                ],
            ],

        /**
         * TODO: Need to fix the following tests, as it is not clear how to count the number of accounts and coupons,
         * especially considering the mobile application.
         */
        /**
         * The owner of the account and the coupon is one user who shared them with another user.
         * The archived coupon is attached to the account.
         */
            //            [
            //                $account = (new DbAccount($user1 = new DbUser()))
            //                    ->shareTo($ua = new DbUserAgent($user2 = new DbUser(), $user1)),
            //                (new DbProviderCoupon('Test Provider Coupon', 500, $user1, PROVIDER_KIND_AIRLINE, [
            //                    'IsArchived' => 1,
            //                ]))
            //                    ->shareTo($ua)
            //                    ->setAccount($account),
            //                [
            //                    [$user1, 2],
            //                    [$user2, 2],
            //                ]
            //            ],

        /**
         * The owner of the account and the coupon is one user who shared them with another user.
         * The account is archived.
         */
            //            [
            //                $account = (new DbAccount($user1 = new DbUser(), null, [], [
            //                    'IsArchived' => 1,
            //                ]))
            //                    ->shareTo($ua = new DbUserAgent($user2 = new DbUser(), $user1)),
            //                (new DbProviderCoupon('Test Provider Coupon', 500, $user1))
            //                    ->shareTo($ua)
            //                    ->setAccount($account),
            //                [
            //                    [$user1, 2],
            //                    [$user2, 2],
            //                ]
            //            ],

        /**
         * The owner of the account and the coupon is one user who shared them with another user.
         * Both the account and the coupon are archived.
         */
            //            [
            //                $account = (new DbAccount($user1 = new DbUser(), null, [], [
            //                    'IsArchived' => 1,
            //                ]))
            //                    ->shareTo($ua = new DbUserAgent($user2 = new DbUser(), $user1)),
            //                (new DbProviderCoupon('Test Provider Coupon', 500, $user1, PROVIDER_KIND_AIRLINE, [
            //                    'IsArchived' => 1,
            //                ]))
            //                    ->shareTo($ua)
            //                    ->setAccount($account),
            //                [
            //                    [$user1, 2],
            //                    [$user2, 2],
            //                ]
            //            ],
        ];
    }

    private function getCacheExtended($key, $cb = null, &$casToken = null)
    {
        $result = $this->cache->get($key, $cb, \Memcached::GET_EXTENDED);

        if (false === $result) {
            return $result;
        }

        $casToken = $result['cas'];

        return $result['value'];
    }

    private function createAccount(
        Provider $provider,
        Usr $user,
        $login,
        $state = ACCOUNT_CHECKED
    ) {
        $account = new Account();
        $account->setProviderid($provider);
        $account->setUserid($user);
        $account->setLogin($login);
        $account->setState($state);

        return $account;
    }

    private function createProviderCoupon(
        Usr $user,
        $programName,
        $kind = 1,
        $desc = "",
        $value = 123
    ) {
        $coupon = new Providercoupon();
        $coupon->setUserid($user);
        $coupon->setProgramname($programName);
        $coupon->setKind($kind);
        $coupon->setDescription($desc);
        $coupon->setValue($value);
        $coupon->setTypeid(Providercoupon::TYPE_COUPON);
        $coupon->setCardNumber(md5(time() . $value . $desc));

        return $coupon;
    }

    private function getAccountDetails(Usr $user, $ua)
    {
        foreach ($this->counter->getDetailsCountAccountsByUser($user, false) as $c) {
            if ($ua == 'all' && $c['UserName'] == 'All' && is_null($c['UserAgentID'])) {
                return $c;
            } elseif (is_null($ua) && $c['UserName'] != 'All' && is_null($c['UserAgentID'])) {
                return $c;
            } elseif (!is_null($ua) && $ua == $c['UserAgentID']) {
                return $c;
            }
        }

        return null;
    }

    private function hasAccounts(Usr $user, $ua, $count)
    {
        $c = $this->getAccountDetails($user, $ua);
        $this->assertNotEmpty($c);
        $this->assertEquals($count, $c['Accounts']);
    }

    private function hasCoupons(Usr $user, $ua, $count)
    {
        $c = $this->getAccountDetails($user, $ua);
        $this->assertNotEmpty($c);
        $this->assertEquals($count, $c['Coupons']);
    }

    private function hasAccountsAndCoupons(Usr $user, $ua, $count)
    {
        $c = $this->getAccountDetails($user, $ua);
        $this->assertNotEmpty($c);
        $this->assertEquals($count, $c['Count']);
    }
}
