<?php

namespace AwardWallet\Tests\Unit;

use AwardWallet\MainBundle\Command\NotifyExpiredCommand;
use AwardWallet\MainBundle\Entity\Usr;
use Codeception\Module\Aw;
use Codeception\Module\Mail;
use Symfony\Component\Console\Tester\CommandTester;

/**
 * @group frontend-unit
 */
class EmailAdTest extends BaseUserTest
{
    /**
     * @var Mail
     */
    private $mail;

    public function _before()
    {
        /** @var Mail mail */
        $this->mail = $this->getModule('Mail');
        parent::_before();
    }

    public function testExpirationMail()
    {
        $providerName = 'testexpiration' . RandomStr(ord('a'), ord('z'), 6);
        $providerId = $this->aw->createAwProvider($providerName, $providerName, [
            'State' => PROVIDER_ENABLED,
        ]);
        $accountId = $this->aw->createAwAccount($userId = $this->user->getId(), $providerId, 'expiration.close', null, [
            'Balance' => 3000,
            'ExpirationDate' => date('Y-m-d', strtotime('+1 week')),
            'SuccessCheckDate' => date('Y-m-d', strtotime('-1 day')),
            'UpdateDate' => date('Y-m-d', strtotime('-1 day')),
        ]);

        $this->command = $this->container->get(NotifyExpiredCommand::class);
        $commandTester = new CommandTester($this->command);
        $commandTester->execute(['-u' => [$userId]]);

        $this->assertEquals(0, $commandTester->getStatusCode(), 'non-zero exit code');
        $this->mail->seeEmailTo($this->user->getEmail(), sprintf('3,000 %s points', $providerName));
    }

    public function testNoExpirationMail()
    {
        $providerName = 'testexpiration' . RandomStr(ord('a'), ord('z'), 6);
        $providerId = $this->aw->createAwProvider($providerName, $providerName, [
            'State' => PROVIDER_ENABLED,
        ]);
        $accountId = $this->aw->createAwAccount($userId = $this->user->getId(), $providerId, 'expiration.close', null, [
            'Balance' => 3000,
            'ExpirationDate' => date('Y-m-d', strtotime('+1 week')),
            'SuccessCheckDate' => date('Y-m-d', strtotime('-1 day')),
            'UpdateDate' => date('Y-m-d', strtotime('-1 day')),
        ]);

        $this->user->setEmailexpiration(Usr::EMAIL_EXPIRATION_NEVER);
        $this->em->flush();

        $this->command = $this->container->get(NotifyExpiredCommand::class);
        $commandTester = new CommandTester($this->command);
        $commandTester->execute(['-u' => [$userId]]);

        $this->assertEquals(0, $commandTester->getStatusCode(), 'non-zero exit code');
        $this->mail->dontSeeEmailTo($this->user->getEmail(), sprintf('3,000 %s points expire on ', $providerName));
    }

    public function testCheckInReminderMail()
    {
        //        global $sPath;

        //        $accountId = $this->aw->createAwAccount($userId = $this->user->getUserid(), 'testprovider', 'future.trip');
        //        $this->aw->checkAccount($accountId);
        //        $this->db->executeQuery(sprintf('
        //            UPDATE TripSegment ts
        //
        //        '))
        //
        //        $command = realpath("/usr/bin/php") . " $sPath/../util/emailScripts/mailCheckin.php -l 1 -u " . $userId;
        //        exec($command, $output, $exitCode);
        //        $this->assertEquals(0, $exitCode, 'non-zero exit code');
        //        $this->mail->seeEmailTo($this->user->getEmail(), sprintf('3,000 %s points expire on ', $providerName));
    }

    public function _after()
    {
        $this->mail = null;

        parent::_after(); // TODO: Change the autogenerated stub
    }

    protected function addUser($prefix)
    {
        $userId = $this->aw->createAwUser($login = "ihg_{$prefix}_" . $this->aw->grabRandomString(5), Aw::DEFAULT_PASSWORD, ['Email' => $login . '@fakemail.com'], true);
        $userEntity = $this->em->getRepository(\AwardWallet\MainBundle\Entity\Usr::class)->find($userId);
        $userEntity->setFirstname("MyFirstName{$prefix}");
        $this->em->persist($userEntity);

        return [$userId, $userEntity];
    }
}
