<?php

namespace AwardWallet\Tests\Unit;

use AwardWallet\MainBundle\Manager\GeoTagManager;

/**
 * @group frontend-unit
 */
class GeoTagManagerTest extends BaseUserTest
{
    /**
     * @var GeoTagManager
     */
    private $geoManager;

    public function _before()
    {
        parent::_before();
        $this->geoManager = $this->container->get("aw.manager.geotag");
    }

    public function testFillRental()
    {
        $rentalId = $this->db->haveInDatabase('Rental', [
            'UserID' => $this->user->getUserid(),
            'PickupLocation' => 'Test from',
            'PickupDatetime' => date("Y-m-d H:i:s"),
            'DropoffLocation' => 'Test to',
            'DropoffDatetime' => date("Y-m-d H:i:s"),
        ]);

        $this->em->getConnection()->executeUpdate("DELETE FROM GeoTag WHERE Address in ('Test from', 'Test to')");
        $this->geoManager->restoreUserGeoTags($this->user);

        $row = $this->em->getConnection()->executeQuery("SELECT PickupGeoTagID, DropoffGeoTagID FROM Rental WHERE RentalID = ?", [$rentalId])->fetch(\PDO::FETCH_ASSOC);
        $this->assertNotEmpty($row['PickupGeoTagID']);
        $this->assertNotEmpty($row['DropoffGeoTagID']);
    }

    public function testFillRestaurant()
    {
        $id = $this->db->haveInDatabase('Restaurant', [
            'UserID' => $this->user->getUserid(),
            'Name' => 'Test restaurant',
            'Address' => 'Test rest',
            'StartDate' => date('Y-m-d'),
        ]);

        $this->em->getConnection()->executeUpdate("DELETE FROM GeoTag WHERE Address in ('Test rest')");
        $this->geoManager->restoreUserGeoTags($this->user);

        $tagId = $this->em->getConnection()->executeQuery("SELECT GeoTagID FROM Restaurant WHERE RestaurantID = ?", [$id])->fetchColumn(0);
        $this->assertNotEmpty($tagId);
    }

    public function testFillReservation()
    {
        $id = $this->db->haveInDatabase('Reservation', [
            'UserID' => $this->user->getUserid(),
            'HotelName' => 'Test hotel',
            'Address' => 'Test hotel',
            'CheckInDate' => date("Y-m-d H:i:s"),
            'CheckOutDate' => date("Y-m-d H:i:s"),
        ]);

        $this->em->getConnection()->executeUpdate("DELETE FROM GeoTag WHERE Address in ('Test hotel')");
        $this->geoManager->restoreUserGeoTags($this->user);

        $tagId = $this->em->getConnection()->executeQuery("SELECT GeoTagID FROM Reservation WHERE ReservationID = ?", [$id])->fetchColumn(0);
        $this->assertNotEmpty($tagId);
    }

    public function testFillTrip()
    {
        $tripId = $this->db->haveInDatabase('Trip', [
            'UserID' => $this->user->getUserid(),
        ]);
        $segmentId = $this->aw->createTripSegment([
            'TripID' => $tripId,
            'DepCode' => 'TFR',
            'DepName' => 'Test from',
            'ArrCode' => 'TTO',
            'ArrName' => 'Test to',
            'DepDate' => date("Y-m-d H:i:s"),
            'ArrDate' => date("Y-m-d H:i:s"),
        ]);

        $this->em->getConnection()->executeUpdate("DELETE FROM GeoTag WHERE Address in ('TFR', 'TTO')");
        $this->geoManager->restoreUserGeoTags($this->user);

        $row = $this->em->getConnection()->executeQuery("SELECT DepGeoTagID, ArrGeoTagID FROM TripSegment WHERE TripSegmentID = ?", [$segmentId])->fetch(\PDO::FETCH_ASSOC);
        $this->assertNotEmpty($row['DepGeoTagID']);
        $this->assertNotEmpty($row['ArrGeoTagID']);
    }

    public function _after()
    {
        $this->geoManager = null;

        parent::_after(); // TODO: Change the autogenerated stub
    }
}
