<?php

namespace AwardWallet\MainBundle\Admin;

use AwardWallet\MainBundle\Entity\CreditCard;
use AwardWallet\MainBundle\Entity\EmailTemplate;
use AwardWallet\MainBundle\Entity\Usr;
use AwardWallet\MainBundle\Form\Type\HtmleditorType;
use AwardWallet\MainBundle\Form\Type\HtmlType;
use AwardWallet\MainBundle\FrameworkExtension\AwTokenStorageInterface;
use AwardWallet\MainBundle\Globals\Localizer\LocalizeService;
use AwardWallet\MainBundle\Globals\StringHandler;
use AwardWallet\MainBundle\Service\EmailTemplate\DataProvider\Group;
use AwardWallet\MainBundle\Service\EmailTemplate\DataProviderLoader;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\FieldDescription\FieldDescriptionInterface;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Route\RouteCollectionInterface;
use Sonata\DoctrineORMAdminBundle\Filter\DateTimeFilter;
use Sonata\DoctrineORMAdminBundle\Filter\StringFilter;
use Sonata\Form\Type\DateTimePickerType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Finder\Finder;
use Symfony\Component\Finder\SplFileInfo;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Validator\Constraints\Callback;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

use function AwardWallet\MainBundle\Globals\Utils\iterFluent\it;
use function AwardWallet\MainBundle\Globals\Utils\stmt\stmtAssoc;

class EmailTemplateAdmin extends AbstractAdmin
{
    public const EXCLUSION_EMAIL = 'email';
    public const EXCLUSION_PROVIDER = 'data';

    public ?string $asyncRequestId = null;
    protected RouterInterface $router;
    protected DataProviderLoader $dataProviderLoader;
    protected EntityManager $em;
    protected ?Usr $user;
    protected EntityRepository $emailTemplateRepo;
    protected LocalizeService $localizer;

    public function __construct(
        RouterInterface $router,
        DataProviderLoader $loader,
        EntityManager $em,
        AwTokenStorageInterface $tokenStorage,
        LocalizeService $localizer
    ) {
        $this->router = $router;
        $this->dataProviderLoader = $loader;
        $this->em = $em;
        $this->user = $tokenStorage->getUser();
        $this->asyncRequestId = StringHandler::getRandomCode(20);
        $this->emailTemplateRepo = $this->em->getRepository(\AwardWallet\MainBundle\Entity\EmailTemplate::class);
        $this->localizer = $localizer;
        $this->setUniqId('email_template');
    }

    protected function configureFormOptions(array &$formOptions): void
    {
        parent::configureFormOptions($formOptions); // TODO: Change the autogenerated stub

        $formOptions['constraints'] = \array_merge(
            $formOptions['constraints'] ?? [],
            [new Callback(['callback' => function (EmailTemplate $data, ExecutionContextInterface $context) {
                $userCode = $data->getCode();
                $dataProvider = $this->dataProviderLoader->getDataProviderByEmailTemplate($data);
                $classCode = DataProviderLoader::getCodeByClass(\get_class($dataProvider));
                $sparkpostCampaignId = "{$userCode}-{$classCode}";
                $idLen = \strlen($sparkpostCampaignId);

                if ($idLen > 64) {
                    $context
                        ->buildViolation("Resulting SparkPost Campaign ID is {$idLen} characters long (exceeds the 64-character limit): {$sparkpostCampaignId}. It may not appear correctly in the SparkPost admin interface. Please ensure the ID is short enough.")
                        ->atPath('code')
                        ->addViolation();
                }
            }])]
        );
    }

    protected function configureRoutes(RouteCollectionInterface $collection): void
    {
        $collection->add('send', $this->getRouterIdParameter() . '/send');
        $collection->add('showEmail', $this->getRouterIdParameter() . '/showEmail');
        $collection->add('stats', $this->getRouterIdParameter() . '/stats/{requestId}', [], ['requestId' => '[a-z0-9]{20}']);
        $collection->add('searchUser', $this->getRouterIdParameter() . '/searchUser/{requestId}', ['requestId' => '[a-z0-9]{20}']);
        $collection->add('duplicate', $this->getRouterIdParameter() . '/duplicate');
    }

    protected function configureFormFields(FormMapper $form): void
    {
        /** @var EmailTemplate $template */
        $template = $this->getSubject();
        $providers = $replacements = $testInfo = $descriptions = [];

        $exclusions =
            it($template->getExclusions() ?? [])
            ->fold([], function (array $exclusions, string $exclusion) {
                $parts = \explode(':', $exclusion);

                if (\count($parts) !== 2) {
                    throw new \LogicException('Invalid exclusion definition');
                }

                switch ($parts[0]) {
                    case self::EXCLUSION_EMAIL:
                        $exclusions['Email template'][$exclusion] = "[Email] !!! UNKNOWN EXCLUSION !!! FIX ME !!! (id: {$parts[1]})";

                        break;

                    case self::EXCLUSION_PROVIDER:
                        $exclusions['Data provider'][$exclusion] = "[Provider] !!! UNKNOWN EXCLUSION !!! FIX ME !!! (id: {$parts[1]})";

                        break;
                }

                return $exclusions;
            });

        $exclusions['Email template'] =
            \array_merge(
                $exclusions['Email template'] ?? [],
                stmtAssoc(
                    $this->em
                    ->getConnection()
                    ->executeQuery('
                        select 
                           Subject,
                           EmailTemplateID,
                           CreateDate
                        from EmailTemplate
                        order by CreateDate desc
                    ')
                )
                ->flatMap(function (array $row) {
                    $date = $this->localizer->formatDate(new \DateTime($row['CreateDate']), 'short');

                    return ['email:' . $row['EmailTemplateID'] => "[Email] {$row['Subject']} ($date) (id: {$row['EmailTemplateID']})"];
                })
                ->toArrayWithKeys()
            );

        foreach ($this->dataProviderLoader->getFreeDataProviders() as $row) {
            $providers[$row['group']]["{$row['title']} (id: {$row['code']})"] = $row['code'];
            $replacements[$row['code']] = $row['replacements'];
            $testInfo[$row['code']] = $row['testInfo'];
            $descriptions[$row['code']] = $row['desc'];

            if ($row['canBeExcluded']) {
                $exclusions["Data provider"]["data:" . $row['code']] = '[Provider] ' . $row['title'] . " (id: {$row['code']})";
            }
        }

        if (isset($exclusions['Data provider'])) {
            $exclusions['Data provider'] = \array_flip($exclusions['Data provider']);
        }

        if (isset($exclusions['Email template'])) {
            $exclusions['Email template'] = \array_flip($exclusions['Email template']);
        }

        \uksort($providers, function (string $group1, string $group2) {
            return Group::getGroupPriority($group2) <=> Group::getGroupPriority($group1); // desc
        });

        $layouts = $this->getLayouts();

        $form
            ->tab('Start')
                ->with("Options", [
                    'class' => 'col-md-6',
                    'box_class' => 'box box-solid box-primary',
                ])
                    ->add('code', TextType::class, [
                        /** @Ignore */
                        'label' => 'Code',
                        'allow_tags' => true,
                        'allow_quotes' => true,
                        'allow_urls' => true,
                        'help' => 'Identification code should be added',
                    ])
                    ->add('dataProvider', ChoiceType::class, [
                        /** @Ignore */
                        'label' => 'Data provider',
                        'choices' => $providers,
                        'help' => '
                            <div id="dataProviderDesc" style="font-style: italic; font-size: large"></div><br/>
                            <div>
                                Required for searching plugin which derives certain users and data for creating emails. 
                                Having created a plugin, developer saves code in a case and you should choose it here. 
                                After specifying the code you will see a block with information about the possible replacements in templates.
                            </div>',
                        'help_html' => true,
                        'placeholder' => '[Please select]',
                        'required' => false,
                    ])
                    ->add('exclusions', ChoiceType::class, [
                        'label' => 'Exclusions',
                        'choices' => $exclusions,
                        'help' => '
                            <b>[Email]</b> - excludes all users who have received an email from the selected email template<br/>
                            <b>[Provider]</b> - excludes all users who are <b>currently</b> in the provider set. Dynamic data sets may not be the same as the last time used.',
                        'help_html' => true,
                        'multiple' => true,
                        'required' => false,
                        'placeholder' => '[Please select]',
                    ])
                    ->add('excludedCreditCards', EntityType::class, [
                        'class' => CreditCard::class,
                        'choice_label' => fn (CreditCard $cc) => $cc->getName() . ' (' . $cc->getProvider()->getShortname() . ') (' . $cc->getId() . ')',
                        'multiple' => true,
                        'group_by' => fn (CreditCard $cc) => $cc->getProvider()->getShortname(),
                        'required' => false,
                    ])
                    ->add('type', ChoiceType::class, [
                        /** @Ignore */
                        'label' => 'Email Type',
                        'choices' => EmailTemplate::getEmailTypes(),
                        'help' => 'Email type defines the way you unsubscribe from it. For example, you can unsubscribe from "Offer" via unchecking the "Promotional Offers" checkbox in profile, "Product Update" - unchecking the "Product Updates" checkbox. But you are unable to unsubscribe from "All Users" emails.',
                    ])
                    ->add('renderEngine', ChoiceType::class, [
                        /** @Ignore */
                        'label' => 'Render Engine',
                        'disabled' => true,
                        'required' => false,
                        'empty_data' => EmailTemplate::RENDER_REPLACE,
                        'choices' => [
                            'REPLACE' => EmailTemplate::RENDER_REPLACE,
                            'TWIG' => EmailTemplate::RENDER_TWIG,
                        ],
                        'help' => '
                            Template language. Used for generating email subject and body.
                            <ul>
                                <li>
                                    REPLACE -  simple replacements in the text (example., <code>{{ userName }}</code>, <code>{{ userLogin }}</code>).
                                    Conditions are impossible because there\'re cycles inside templates.
                                </li>
                                <li>TWIG - twig syntax support</li>
                            </ul>
                        ',
                        'help_html' => true,
                    ])
                    ->add('_helps', HtmlType::class, [
                        'html' => '
                            <script>
                                var replacements = ' . json_encode($replacements) . ';
                                var testInfo = ' . json_encode($testInfo) . ';
                                var descriptions = ' . json_encode($descriptions) . ';
                            </script>',
                        /** @Ignore */
                        'label' => false,
                        'mapped' => false,
                    ], ['type' => 'text'])
                ->end()
            ->end()

            ->tab('Working with Templates')
                ->with("Basic settings", [
                    'class' => 'col-md-6',
                    'box_class' => 'box box-solid box-primary',
                ])
                    ->add('subject', TextareaType::class, [
                        /** @Ignore */
                        'label' => 'Subject',
                        'required' => false,
                        'allow_tags' => true,
                        'allow_quotes' => true,
                        'allow_urls' => true,
                        'help' => 'Replacements could be used in the text here',
                    ])
                    ->add('layout', ChoiceType::class, [
                        /** @Ignore */
                        'label' => 'Layout',
                        'required' => false,
                        'choices' => array_combine($layouts, $layouts),
                        'help' => '
                            The main template, inserted below template will depend on it.
                            Templates can be added/updated via path:
                            <code>/bundles/<wbr>AwardWallet/MainBundle/<wbr>FrameworkExtension/Mailer/<wbr>Template/Layout/Offer</code>
                        ',
                        'help_html' => true,
                    ])
                    ->add('ListBlogPostID', TextType::class, [
                        /** @Ignore */
                        'label' => 'List BlogPost ID',
                        'allow_tags' => false,
                        'allow_quotes' => false,
                        'required' => false,
                        'help' => 'List of Comma separated PostIDs',
                    ])
                    ->add('CID', TextType::class, [
                        /** @Ignore */
                        'label' => 'CID',
                        'required' => false,
                        'allow_tags' => false,
                        'allow_quotes' => false,
                    ])
                    ->add('MID', TextType::class, [
                        /** @Ignore */
                        'label' => 'MID',
                        'required' => false,
                        'allow_tags' => false,
                        'allow_quotes' => false,
                    ])
                ->end()

                ->with("Logo", [
                    'class' => 'col-md-12',
                    'box_class' => 'box box-solid box-default collapsed-box',
                ])
                    ->add('logo', HtmleditorType::class, [
                        /** @Ignore */
                        'label' => false,
                        'required' => false,
                        'ui_color' => null,
                        'allow_tags' => true,
                        'allow_quotes' => true,
                        'allow_urls' => true,
                        'filebrowser_browse_url' => ['url' => '/elfinder/default'],
                        'on' => "{
                                    pluginsLoaded: function(e) {
                                        e.editor.dataProcessor.dataFilter.addRules({
                                            elements: {
                                                $: function(element) {
                                                    if (element.attributes.id) {
                                                        delete element.attributes.id;
                                                    }
                                                    return element;
                                                }
                                            }
                                        });
                                    }
                                }",
                        'help' => 'logo',
                    ])
                ->end()

                ->with("Preview", [
                    'class' => 'col-md-12',
                    'box_class' => 'box box-solid box-default collapsed-box',
                ])
                    ->add('Preview', HtmleditorType::class, [
                        /** @Ignore */
                        'label' => false,
                        'required' => false,
                        'ui_color' => null,
                        'allow_tags' => true,
                        'allow_quotes' => true,
                        'allow_urls' => true,
                        'filebrowser_browse_url' => ['url' => '/elfinder/default'],
                        'on' => "{
                                    pluginsLoaded: function(e) {
                                        e.editor.dataProcessor.dataFilter.addRules({
                                            elements: {
                                                $: function(element) {
                                                    if (element.attributes.id) {
                                                        delete element.attributes.id;
                                                    }
                                                    return element;
                                                }
                                            }
                                        });
                                    }
                                }",
                        'help' => 'preview for email clients',
                    ])
                ->end()

                ->with("Body", [
                    'class' => 'col-md-12',
                    'box_class' => 'box box-solid box-default collapsed-box',
                ])
                    ->add('body', HtmleditorType::class, [
                        /** @Ignore */
                        'label' => false,
                        'required' => false,
                        'ui_color' => null,
                        'allow_tags' => true,
                        'allow_quotes' => true,
                        'allow_urls' => true,
                        'filebrowser_browse_url' => ['url' => '/elfinder/default'],
                        'on' => "{
                                    pluginsLoaded: function(e) {
                                        e.editor.dataProcessor.dataFilter.addRules({
                                            elements: {
                                                $: function(element) {
                                                    if (element.attributes.id) {
                                                        delete element.attributes.id;
                                                    }
                                                    return element;
                                                }
                                            }
                                        });
                                    }
                                }",
                        'help' => 'Main email content',
                    ])
                ->end()

                ->with("Head", [
                    'class' => 'col-md-12',
                    'box_class' => 'box box-solid box-default collapsed-box',
                ])
                    ->add('head', HtmleditorType::class, [
                        /** @Ignore */
                        'label' => false,
                        'required' => false,
                        'ui_color' => null,
                        'allow_tags' => true,
                        'allow_quotes' => true,
                        'allow_urls' => true,
                        'filebrowser_browse_url' => ['url' => '/elfinder/default'],
                        'on' => "{
                            pluginsLoaded: function(e) {
                                e.editor.dataProcessor.dataFilter.addRules({
                                    elements: {
                                        $: function(element) {
                                            if (element.attributes.id) {
                                                delete element.attributes.id;
                                            }
                                            return element;
                                        }
                                    }
                                });
                            }
                        }",
                        'help' => 'Will be inserted in <head> block',
                    ])
                ->end()

                ->with("Style", [
                    'class' => 'col-md-12',
                    'box_class' => 'box box-solid box-default collapsed-box',
                ])
                    ->add('style', HtmleditorType::class, [
                        /** @Ignore */
                        'label' => false,
                        'required' => false,
                        'ui_color' => null,
                        'allow_tags' => true,
                        'allow_quotes' => true,
                        'allow_urls' => true,
                        'filebrowser_browse_url' => ['url' => '/elfinder/default'],
                        'on' => "{
                            pluginsLoaded: function(e) {
                                e.editor.dataProcessor.dataFilter.addRules({
                                    elements: {
                                        $: function(element) {
                                            if (element.attributes.id) {
                                                delete element.attributes.id;
                                            }
                                            return element;
                                        }
                                    }
                                });
                            }
                        }",
                        'help' => 'Prior to closing </body> tag',
                    ])
                ->end()
            ->end()

            ->tab('Testing')
                ->with("Show/Send email", [
                    'class' => 'col-md-8',
                    'box_class' => 'box box-primary',
                ])
                    ->add('testUsers', TextareaType::class, [
                        /** @Ignore */
                        'label' => 'Users',
                        'required' => false,
                        'mapped' => false,
                        'allow_tags' => true,
                        'allow_quotes' => true,
                        'allow_urls' => true,
                        'data' => $this->user->getEmail(),
                        'help' => '
                            <p>Filtering by users. Along with filters created by a developer for a specific plugin (for deriving certain email recipient users), other parameters could be set to narrow the field of users for testing.
                                Specifying users does not guarantee that they will be included in the mailing list if they do not meet other mailing conditions.</p>
                            <p>If you leave the field blank, query will be performed according to the original conditions.</p>
                            <p><mark>Enter 1 user per line. UserID, Login or Email are allowed</mark></p>
                        ',
                        'help_html' => true,
                    ])
                    ->add('testFixture', CheckboxType::class, [
                        /** @Ignore */
                        'label' => 'Add test data',
                        'required' => false,
                        'mapped' => false,
                        'help' => '
                            Add test data (users) to the database for mailing.
                            All data will be erased after test sending.
                            Developer is responsible for adding and removing test data. If test users are added, they are automatically added to the filter.
                        ',
                    ])
                    ->add('testEmails', TextareaType::class, [
                        /** @Ignore */
                        'label' => 'Email address',
                        'required' => false,
                        'mapped' => false,
                        'allow_tags' => true,
                        'allow_quotes' => true,
                        'allow_urls' => true,
                        'data' => $this->user->getEmail(),
                        'help' => '
                            <p>Test email recipients. If several email addresses are indicated, an email would be sent to each one.</p>
                            <p><mark>Enter 1 email address per line</mark></p>
                            <p><mark>Default Email: ' . $this->user->getEmail() . '</mark></p>
                        ',
                        'help_html' => true,
                    ])
                    ->add('testLimit', NumberType::class, [
                        /** @Ignore */
                        'label' => 'Limit',
                        'required' => false,
                        'mapped' => false,
                        'data' => 1,
                        'help' => "Max quantity of sending emails (users). If you specify 5 but the actual number of email addresses is 3, then 5 emails will be sent, each of which will contain the recipient's first email address and 2 recipients of the copy. The max quantity is 20. If the field left empty, the max emails would be sent - 20.",
                    ])
                ->end()
            ->end()

            ->tab('Finish')
                ->with("Ready?", [
                    'class' => 'col-md-10',
                    'box_class' => 'box box-solid box-success',
                ])
                    ->add('enabled', CheckboxType::class, [
                        /** @Ignore */
                        'label' => 'Enable',
                        'required' => false,
                        'help' => '
                            <p>If the email is ready and tested, then turn it on and try sending:</p>
                            jenkins:
                            <a class="command-code" target="_blank">https://jenkins.awardwallet.com/job/Frontend/job/send-offer/parambuild?offer=<span class="command-code"></span></a>
                            <br/><br/>
                            console:
                            <br/>
                            <code>php /www/awardwallet/app/console aw:send-email:template <span class="command-code"></span> --env=prod --no-debug</code>
                            <br/><br/>
                            nohup:
                            <br/>
                            <code>nohup php /www/awardwallet/app/console aw:send-email:template <span class="command-code"></span> --env=prod --no-debug >> nohup_<span class="command-code"></span>.log &</code>
                            <br/><br/>
                            progress:
                            <br/>
                            <code>watch -n 0.2 \'LOG_FILE="nohup_<span class="command-code"></span>.log"; SENT=$((`wc -l $LOG_FILE | grep -o "^[0\-9]\+"`-3)); TOTAL=$((`head -n 3 $LOG_FILE | grep -o "[0\-9]\+"`)); tail -n 10 $LOG_FILE && echo "################\n$(echo "scale=2;$SENT/$TOTAL*100" | bc)%: $SENT of $TOTAL"\'</code>
                        ',
                        'help_html' => true,
                    ])
                ->end()
            ->end()
        ;

        $form->get('excludedCreditCards')->addModelTransformer(new CallbackTransformer(
            fn ($value) => $this->em->getRepository(CreditCard::class)->findBy(['id' => $value]),
            fn ($value) =>
                it($value)
                ->map(fn (CreditCard $cc) => $cc->getId())
                ->toArray()
        ));

        $form->get('dataProvider')->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
            $data = $event->getData();
            $form = $event->getForm();
            /** @var EmailTemplate $emailTemplate */
            $emailTemplate = $form->getParent()->getData();

            if (isset($data)) {
                try {
                    $this->dataProviderLoader->getDataProviderByEmailTemplate($emailTemplate);
                } catch (\InvalidArgumentException $e) {
                    $event->setData('');
                }
            }
        });
    }

    protected function configureListFields(ListMapper $list): void
    {
        $list
            ->addIdentifier('code', null, ['route' => ['name' => 'edit']])
            ->add('subject')
            ->add('layout')
            ->add('type', FieldDescriptionInterface::TYPE_CHOICE, [
                'choices' => array_flip(EmailTemplate::getEmailTypes()),
            ])
            ->add('createDate')
            ->add('updateDate')
            ->add('enabled', FieldDescriptionInterface::TYPE_BOOLEAN, ['editable' => true])
            ->add(ListMapper::NAME_ACTIONS, ListMapper::TYPE_ACTIONS, [
                'actions' => [
                    'edit' => [],
                    'delete' => [],
                    'testing' => [
                        'template' => '@AwardWalletMain/Sonata/CRUD/EmailTemplate/list_action_email_testing.html.twig',
                    ],
                    'duplicate' => [
                        'template' => '@AwardWalletMain/Sonata/CRUD/EmailTemplate/list_action_email_duplicate.html.twig',
                    ],
                ],
            ]);
    }

    protected function configureDatagridFilters(DatagridMapper $filter): void
    {
        $filter
            ->add('subject')
            ->add(
                'type',
                StringFilter::class,
                [
                    'field_type' => ChoiceType::class,
                    'field_options' => [
                        'choices' => EmailTemplate::getEmailTypes(),
                    ],
                ],
            )
            ->add(
                'createDate',
                DateTimeFilter::class,
                [
                    'field_type' => DateTimePickerType::class,
                ],
            )
            ->add(
                'updateDate',
                DateTimeFilter::class,
                [
                    'field_type' => DateTimePickerType::class,
                ],
            )
        ;
    }

    protected function generateBaseRouteName(bool $isChildAdmin = false): string
    {
        return 'email_template';
    }

    protected function generateBaseRoutePattern(bool $isChildAdmin = false): string
    {
        return 'email-template';
    }

    protected function getAccessMapping(): array
    {
        return [
            'send' => 'EDIT',
            'showEmail' => 'EDIT',
            'stats' => 'EDIT',
            'searchUser' => 'EDIT',
            'duplicate' => 'EDIT',
        ];
    }

    private function getLayouts()
    {
        $layouts = [];
        $finder = (new Finder())
            ->files()
            ->name('*.twig')
            ->in(__DIR__ . '/../FrameworkExtension/Mailer/Template/Layout/Offer')
            ->depth('== 0')
            ->sortByName();

        /** @var SplFileInfo $file */
        foreach ($finder as $file) {
            $layouts[] = $file->getBasename('.twig');
        }

        return $layouts;
    }
}
