POST https://api.capitalone.com/oauth2/token
User-Agent: awardwallet
Content-Type: application/x-www-form-urlencoded

client_id={{client_id}}&client_secret={{client_secret}}&grant_type=refresh_token&refresh_token={{refresh_token}}